urql-graphql/urql

.npmignore, package.json
- Fix script escaping for Windows
- Only run jest on `src` directory
- Exclude tests from npm publishing
=> [BUG] Fix appveyor

.babelrc, .prettierrc, package.json, yarn.lock
For whatever reason, Prettier is refusing to run with the `|>` operator. I've tried swapping the parser but haven't found other ways to get around it. Because of this, the precommit hook currently fails. Once that is resolved (or removed) this should work like a charm after you add `"precommit": "lint-staged"` to `scripts` in the `package.json`.
Not sure what to do with this PR other than leaving it up for the time being.
=> Add prettier task to package.json

.npmignore
- Adds extra blacklist to `.npmignore` as not all files match `*.test.js`
/cc @kenwheeler
=> Fix test blacklist for publishing.

.gitignore, .npmignore, package.json, src/components/client.tsx, src/components/connect.tsx, src/components/context.tsx, tsconfig.dts.json, tsconfig.json
Fixes #25.
Here's the summary of what I did just so you feel more confident accepting this PR.
First, I added a new `tsconfig.dts.json` that extends the usual config, but turns emit back on. Building with `tsconfig.dts.json` will emit `.d.ts` files. Note this also produces `.js` files, but I've updated the `.npmignore` to ignore anything other than `.d.ts` files.
To get `--declaration` working, first I turned on `--declaration` in your `tsconfig.json` (as opposed to just in your `tsconfig.dts.json`, so that the editor can tell you about `--declaration` errors when they happen). I also had to turn `--allowJs` off since it's currently not a supported combo. Finally, I added a hack to get `--declaration` emit working with `noUnusuedLocals` (without needing a `// @ts-ignore`).
Lastly, I added …
=> Enable --declaration emit for TypeScript.

example/src/app/home.tsx, src/components/client.tsx, src/components/connect-hoc.tsx, src/components/connect.tsx, src/tests/components/client.test.tsx, src/tests/components/connect.test.tsx
Fixes #33 
By naming the render prop 'children', allows both prop style and functional child style
=> changing render to children

.prettierignore, package.json
**What**:
Ignore `package.json` when formatting with `prettier` to avoid conflicting with the `npm`/`yarn` format.
**Why**:
`npm` and `yarn` both format `package.json` in a common, opinionated way. Formatting JSON files with `prettier` yields a different result. `prettier` will currently reformat `package.json` and clutter up commits going back and forth between the two formats any time `npm` or `yarn` modifies `package.json`.
**How**:
* added `package.json` to `.prettierignore`
* reformatted `package.json` to prevent future diffs
**See also**:
[Stop re-formatting package.json with Prettier and VSCode once and for all](https://medium.com/@martin_hotell/stop-re-formatting-package-json-with-prettier-and-vscode-once-and-for-all-52d283067f9a) by Martin Hochel
=> Ignore package.json when formatting with prettier

.npmignore, package.json, tsconfig.dts.json, yarn.lock
In TypeScript 2.8 (and in TypeScript 2.7.2, but low-key) [we added the `emitDeclarationOnly` flag](https://github.com/Microsoft/TypeScript/pull/20735). This flag basically says "I only want to create `.d.ts` files", which is basically perfect for libraries that use Babel to emit JS.
C.C. @mhegazy (and thanks @nojvek!)
=> Only emit declaration files with TypeScript

src/components/client.tsx, src/tests/components/__snapshots__/connect-hoc.test.tsx.snap, src/tests/components/__snapshots__/connect.test.tsx.snap
This PR exposes the client to `Connect`'s child function in case child components want to manually fetch from the client.
=> Expose client in Connect child function

example/src/server/index.js
The spelling of the `context` key on the `graphqlHttp` options object in the example server appears to be off. The [`express-graphql` docs](http://graphql.org/graphql-js/express-graphql/) provide this structure for the options object:
```
graphqlHTTP({
schema: GraphQLSchema,
graphiql?: ?boolean,
rootValue?: ?any,
context?: ?any,
pretty?: ?boolean,
formatError?: ?Function,
validationRules?: ?Array<any>,
}): Middleware
```
=> Fix spelling of context key for graphqlHttp.

example/src/app/home.tsx, example/src/app/index.tsx, example/src/app/loading.tsx, example/src/app/todo-form.tsx, example/src/app/todo-list.tsx, src/components/client.tsx, src/components/connect.tsx, src/tests/components/connect.test.tsx
This PR does a few things:
- Introduces a new generic TS type `UrqlProps<Data, Mutations>` that works pretty much like Formik's `FormikProps<Values>` and React Router 4's `RouteComponentProps<Params>`, (i.e. you use it to properly type the children of the render prop function). 
- Fixes the example to use the new generic
- Adds detailed comments around the generic for improved editor integration for Urql x TS consumers.
What does it look like?
```tsx
// ...
export interface ITodoQuery {
todos: Array<{ id: string; text: string }>;
user: {
name: string;
};
}
export interface ITodoMutations {
addTodo: (input: { text: string }) => void;
removeTodo: (input: { id: string }) => void;
}
const Home: React.SFC<{}> = () => (
<Connect
query={query(TodoQuery)}
mutation={{
addTodo: mutation(AddTodo), …
```
=> Improve/Fix TS types

src/modules/hash.ts
Use the more concise https://github.com/garycourt/murmurhash-js
implementation. It's used in various other open source libraries
and more concise than the previous one.
It's functionally equivalent and I've made sure that the seed value
matches, which is also covered by some unit tests.
=> Swap out murmurhash v2 implementation

package.json, src/components/client.tsx, src/interfaces/client.ts, src/modules/client.ts, src/tests/modules/client.test.ts
I'm not sure why uuid was used to determine IDs for subscriptions on
the client. Instead we can use a create-broadcast like approach, where
we just count up the number of created (not active) subscriptions as
IDs.
Note: `uuid` is still necessary as a `devDependency` for the example as far as I can tell.
=> Swap out uuid for counter based subscriptions

package.json, src/components/client.tsx, src/interfaces/client.ts, src/interfaces/exchange.ts, src/interfaces/index.ts, src/interfaces/operation.ts, src/modules/client.ts, src/modules/dedup-exchange.ts, src/modules/http-exchange.ts, src/tests/components/client.test.tsx, src/tests/modules/dedup-exchange.test.ts, src/tests/setup.js, yarn.lock
This PR is an initial draft/proposal to introduce "exchanges". It's a structure that will enable us to implement more features in the future and to clean up the existing logic. It's flexible enough to allow us to implement batching and even subscriptions cleanly.
On the **TypeScript** side it introduces some new interfaces:
- `IOperation` — This is an instruction for an "Exchange" to go talk to the GraphQL API
- `IExchange` — This is an "Exchange". It's a function that accepts an `IOperation` and returns an Observable of a GraphQL `ExecutionResult`
Effectively with just two new type "primitives" we can separate the fetch logic from the Client and clean everything up. This means that the Client now calls the exchange to actually start a request.
To demonstrate what this means I've …
=> [Draft] Refactor fetch logic to be separated from Client

src/modules/cache-exchange.ts, src/tests/modules/cache-exchange.test.ts
Fix #58
Suppose a Client component fetches some data and is then unmounted, its
response will still remain cached. When a mutation is then performed
that invalidates its data, the component is not mounted to invalidate
this response itself. Instead it will render with the stale, cached
response.
To prevent this change introduces a secondary cache control. This
control keeps track of typenames as well in the cacheExchange. It maps
typenames to operation keys (which are also cache keys, woohoo!). When
a mutation then invalidates a couple of typenames in the cache, the
cacheExchange can go ahead and look up all cache keys that should be
invalidated, all while the Client component can stay unmounted.
=> Fix cache not invalidating when a Client component isn't listening

src/components/client.tsx, src/interfaces/client.ts, src/interfaces/events.ts, src/interfaces/index.ts, src/modules/client.ts, src/tests/components/client.test.tsx, src/tests/modules/client.test.ts
The observable "events" on the client are a little hard to follow since they're not self-descriptive. Instead we can make them into actual "actions"/"events", let them have a typed event, and make them more type-safe.
=> Refactor client to emit events on subscribers

src/components/client.tsx, src/components/connect.tsx, src/interfaces/client.ts, src/modules/client.ts, src/tests/components/__snapshots__/client.test.tsx.snap, src/tests/components/client.test.tsx, src/tests/components/connect-hoc.test.tsx
It should be possible to provide a `query` and a `subscription` and to describe how to update the query's result with a subscription's result. In this PR this new behaviour is introduced and the updates will be described using the `updateSubscription` function.
After an event from the subscription, the ClientWrapper will also invalidate the query's cache.
=> Improved query subscription updates

example/src/server/schema.js
Found a single `=` instead of `==` in the example todo resolver.
=> Fix server example 'todo' query

src/interfaces/error.ts, src/interfaces/index.ts, src/modules/error.ts, src/tests/modules/error.test.ts
Fix #88
This rehydrates additional fields onto the errors in `CombinedError#graphQLErrors` and types them correctly as instances of `Error`
=> Support additional IGraphQLError fields on rehydration

package.json, src/components/client.tsx, src/interfaces/client.ts, src/interfaces/exchange.ts, src/interfaces/index.ts, src/modules/client.ts, src/modules/typenames.ts, src/tests/modules/typenames.test.ts, tslint.json, yarn.lock
Updates the typenames utilities to use `graphql/language/visit` and `graphql-ast-types`
=> Append typenames via visitor and graphql-ast-types

README.md
The world's smolest diff! I just noticed this back while working on `reason-urql`'s support for custom caching. The README shows `urql`'s default cache using a `.map` to iterate over cache entries, but it actually (correctly) uses a `.forEach`: https://github.com/FormidableLabs/urql/blob/master/src/modules/client.ts#L45
=> Use forEach in README's cache update example to match urql's internal caching mechanism.

examples/1-getting-started/src/app/Home.tsx, src/client.ts, src/components/Query.tsx, src/components/__snapshots__/Query.test.tsx.snap, src/exchanges/__snapshots__/fetch.test.ts.snap, src/exchanges/__snapshots__/subscription.test.ts.snap, src/exchanges/cache.ts, src/hooks/useQuery.test.tsx, src/hooks/useQuery.ts, src/hooks/useSubscription.ts, src/test-utils/samples.ts, src/types.ts, src/utils/index.ts
This adds `requestPolicy` as a property on operation contexts. It has four modes, like in Apollo:
- `cache-first`: The default. It skips the network request (i.e. the other exchanges) when a result can be retrieved from the cache.
- `cache-only`: It returns an empty result when the data is not cached but also skips the network request. (With a normalised cache this would return a partial result if possible)
- `network-only`: This skips the cache entirely and forwards the request on to the other exchanges.
- `cache-and-network`: If data is cached it is first returned but another operation is then triggered using `network-only`, effectively using the cache and then updating it.
This can now be used as a prop on `useQuery`:
```js
const [res, executeQuery] = useQuery({ /* ... */ …
```
=> Add requestPolicy to manage cache strategy

docs/basics.md, docs/getting-started.md, examples/1-getting-started/src/app/Home.tsx, examples/2-using-subscriptions/src/app/Messages.tsx
Tidied up res language in docs for more consistency between examples.
* Changed query -> res in getting-started.md examples.
* Changed result -> res in basics.md example.
* Changed query -> res in Home.tsx of example project getting-started.
* Changed subscription -> res in Messages.tsx of example using-subscription (happy to let this go if people think it worsens comprehension.)
=> Proposal: Rename query in example docs and example projects from query to res.

src/utils/typenames.ts
I ran into a case where my `val` was `null`, and the stacktrace pointed me here. 
Apparently `typeof null === 'object'` 😄
=> handle val === null in getTypeNameFromField

docs/basics.md
First of all, Thank you for the amazing documentation. Much appreciated. 
Found some typos as I was reading the documentation.
=> Fix some typos in basics.md

docs/api.md
This PR adds a small fix to escape pipe characters in Markdown tables in `api.md`. While the pipes represent union types in the TS world, they also represent columns in Markdown land 😂. Previously, this meant that some types and descriptions of specific props were either cutoff or entirely missing.
By escaping the pipe characters, our types and descriptions rise like phoenixes from the ashes 🔥 🐦. 
Just noticed this while working on `reason-urql` and thought I'd fix it!
=> Escape pipe characters (|) in Markdown tables.

package.json, src/client.test.ts, src/client.ts, src/components/Mutation.test.tsx, src/components/Mutation.tsx, src/components/Query.test.tsx, src/components/Query.tsx, src/components/Subscription.tsx, src/exchanges/__snapshots__/fetch.test.ts.snap, src/exchanges/__snapshots__/subscription.test.ts.snap, src/global.d.ts, src/hooks/useMutation.test.tsx, src/hooks/useQuery.test.tsx, src/hooks/useSubscription.test.tsx, src/test-utils/samples.ts, src/types.ts, src/utils/__snapshots__/keyForQuery.test.ts.snap, src/utils/keyForQuery.test.ts, src/utils/keyForQuery.ts, src/utils/request.test.ts, src/utils/request.ts
We always parse the document now when we receive a string.
This ensures a consistent request data structure and makes
things easier, since there's not much else to expect.
Also addresses a bug where `parse` is undefined.
Fix #206
Fix #219 (Related)
=> Change GraphQLRequest to always contain a parsed document

src/exchanges/cache.ts
Fix #210 
The `operationCache` might already contain stale operation keys if particular queries are run while a mutation is looking to invalidate some results, hence the `resultCache` might not contain all operations anymore, if a result has already been invalidated.
=> fix: Guard resultCache access in cacheExchange

docs/api.md, src/components/Query.test.tsx, src/components/Query.tsx, src/hooks/useQuery.test.tsx, src/hooks/useQuery.ts
This PR picks up on the changes in #229 and would close issue #228. @kitten I read through your comments in #229 and attempted to address them in this PR. I also added a few tests to ensure things are behaving as expected, but definitely would appreciate both of your 👀 in verifying that this behaves as expected.
=> Add support for skip to Query and useQuery.

src/hooks/__snapshots__/useQuery.test.tsx.snap, src/hooks/useImmediateEffect.test.ts, src/hooks/useImmediateEffect.ts, src/hooks/useQuery.test.tsx, src/hooks/useQuery.ts, src/hooks/useRequest.test.ts, src/hooks/useRequest.ts, src/hooks/useSubscription.ts, src/utils/request.ts
Fix #245 
Initial stuff that will become necessary for #218
This implements two hooks:
- `useRequest` to simplify the creation of requests while keeping a stable reference, so we don't have to check for `request.key`
- `useImmediateEffect` to simplify running an effect immediately outside of `useEffect` for SSR/suspense, which then otherwise behaves like a normal `useEffect`.
=> Implement immediate effect and refactor

docs/basics.md, docs/getting-started.md
This adds tutorials on:
- setting up a client and provider
- adding the subscription exchange
- using `useSubscription`
This also adds a `pl` param to each lesson url so that the user clicking the link will see all the other urql lessons.
=> Add link to additional egghead screen casts

.eslintrc.json, src/hooks/useImmediateEffect.test.ts, src/hooks/useImmediateEffect.ts, src/hooks/useImmediateState.test.ts, src/hooks/useImmediateState.ts, src/hooks/useMutation.ts, src/hooks/useQuery.ts, src/hooks/useSubscription.ts
Fix #245
Fix #209 (See 17feeca)
It seems that in the current version React does
trigger *two* renders in our case.
We call executeQuery immediately which has a couple
of setStates. These are batched, it seems, but
do trigger a second update of the underlying
component, which is a shame.
Instead, we know that the initial executeQuery can
just safely merge its results into the initial
state, if it's during the initial mount.
This is why useImmediateState is added, which does
just that. Not the nicest way to solve this, but
the safest until React ships batched updates by
default.
This is basically a solution that will continue to
ensure that we won't have to add any state-related
stuff outside of `executeQuery`
=> Ensure that state changes are applied immediately on mount

package.json, src/__snapshots__/client.test.ts.snap, src/__snapshots__/context.test.ts.snap, src/client.ts, src/exchanges/cache.ts, src/exchanges/index.ts, src/exchanges/ssr.test.ts, src/exchanges/ssr.ts, src/test-utils/ssr.test.tsx, src/utils/index.ts, src/utils/toSuspenseSource.test.ts, src/utils/toSuspenseSource.ts, yarn.lock
Fix #218
Server-side rendering can now be achieved; an app using `urql` can do this with just minor modifications. Instead of using `getDataFromTree` like `react-apollo` does we're using our more generic [`react-ssr-prepass` library.](https://github.com/FormidableLabs/react-ssr-prepass)
This still needs to be documented but essentially on the server the client used like so:
```js
import ssrPrepass from 'react-ssr-prepass';
import {
createClient,
dedupExchange,
cacheExchange,
ssrExchange,
fetchExchange
} from 'urql';
// We create an ssrExchange, which is an additional cache for client-side rehydration
const ssr = ssrExchange();
// The client can also be shared, but `suspense` needs to be set to
// false on the client-side
const client = createClient({
url,
exchanges: [dedupExchange, …
```
=> Implement server-side rendering support

src/hooks/useImmediateEffect.ts, src/hooks/useQuery.ts
The proposed changes here are aimed to simplify the use-cases associated with the `pause` argument.
Rather than pause preventing requests outright - it will _pause_ the functionality of auto fetching  - whether that be on mount or when the query has changed.
The reasons for this are:
- It allows users to pause auto fetching while having the ability to manually fetch on demand (currently not an option - see [example problem here](https://www.reddit.com/r/reactjs/comments/bxu4hc/urql_v11_now_with_serverside_rendering_support/eqb3sj0?utm_source=share&utm_medium=web2x))
- It improves the seperation of concerns. Config options should influence how urql acts, manual operations can be prevented with a conditional inside component logic. 
There's also a small typing fix for _useImmediateEffect_. …
=> Modify use of pause

src/exchanges/dedup.test.ts, src/exchanges/dedup.ts
Fix #280 
When a query was torn down, the dedup exchange wasn't
removing its key from the inFlight keys.
This was causing us to ignore torn down queries forever.
=> Fix dedup ignoring torn down query operations

examples/3-ssr-with-nextjs/components/PostUpvoter.js
The upvote buttons in the Next example weren’t working, this fixes it.
=> Fix PostUpvoter variables

.sail.yml, package.json, rollup.config.js
- Declarations are now generated as part of the Rollup build
- The Rollup build overrides the tsconfig correctly now and no changes to the output were made
- The clean task now runs only before publishing as that's the only time we care about it
- Prune was removed; instead we just exclude test files inside Rollup
=> Move all build tasks to Rollup

package.json
In my PR the testing dep snuck into dependencies instead of devDependencies, apologies!
=> (chore) - move wrongly placed import

src/utils/typenames.test.ts, src/utils/typenames.ts
Fix #320 
**Note: ** The [check for a selections array](https://github.com/FormidableLabs/urql/compare/320-fix-typename-additions?expand=1#diff-f56409a2c09e8916f77be7385bb12343L39) inside of the selectionSet has been removed. According to _@types/graphql_ the [selections property is required](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/graphql/language/ast.d.ts#L226).
=> add typename existence check

src/exchanges/cache.test.ts, src/exchanges/cache.ts, src/hooks/useDevtoolsContext.ts, src/hooks/useMutation.test.tsx, src/hooks/useQuery.test.tsx, src/hooks/useSubscription.test.tsx, src/types.ts, src/utils/request.ts
When using the default cache exchange, responses will have an additional property `cacheHit` added to their context.
This property will not be added to the global context type definition as it is specific to this cache. Future cache implementations may use this `cacheHit` property in a different way (i.e. cache hits could be flagged as partial).
=> Flag responses with cache hit status

src/exchanges/__snapshots__/fetch.test.ts.snap, src/exchanges/fetch.test.ts, src/exchanges/fetch.ts
Adds a _latency_ property to a returning operation's context. This is the duration in milliseconds that the request took to complete.
=> Add latency info to context

docs/api.md, examples/2-using-subscriptions/README.md, examples/2-using-subscriptions/yarn.lock, src/hooks/useMutation.test.tsx, src/hooks/useQuery.test.tsx, src/hooks/useRequest.ts, src/hooks/useSubscription.test.tsx, src/hooks/useSubscription.ts
This PR would fix #319. As @mjadczak points out, the `void` type is a mistake there - `handler` is called in `useSubscription` with `(s.data, data)`, where `s.data` is set initially by `useImmediateState` to `undefined`: https://github.com/FormidableLabs/urql/blob/master/src/hooks/useSubscription.ts#L36. It also fixes the signature of the mutable ref inside of `useRequest`, which is initialized to `undefined` .
I'm also not sure if we were attempting to take advantage of `undefined` and `null` being sub-types of `void`, so feel free to push back on this change (but it seems to make sense to me).
=> Update type signature for SubscriptionHandler. Update associated docs.

src/utils/typenames.ts
`obj.hasOwnProperty` can sometimes be undefined even though `obj` is an actual object, see this conversation over in another repo for reference: https://github.com/domchristie/humps/issues/35
I am (somehow through a million hoops) running into this in my project, and their suggested fix of using `Object.prototype.hasOwnProperty.call(obj, key)` works beautifully and fixes my issue.
=> Fix error in collectTypes method

src/components/Mutation.ts, src/components/Query.ts, src/components/Subscription.ts
fixes: https://github.com/FormidableLabs/urql/issues/335
Normally one would use the exported type React.FC for these but since this isn't possible with generics I followed this line from the React types to come to this conclusion.
```
type SFC<P> = StatelessComponent<P>;
interface StatelessComponent<P> {
(props: P & { children?: ReactNode }, context?: any): ReactElement<any>;
}
```
=> (fix) - return value of functional components

examples/1-getting-started/src/app/Home.tsx, examples/1-getting-started/src/app/components/Error.tsx, examples/1-getting-started/src/app/components/Loading.tsx, examples/1-getting-started/src/app/components/Todo.tsx, examples/1-getting-started/src/app/index.tsx, examples/1-getting-started/yarn.lock, examples/2-using-subscriptions/src/app/Messages.tsx, examples/2-using-subscriptions/src/app/components/Error.tsx, examples/2-using-subscriptions/src/app/components/Message.tsx, examples/2-using-subscriptions/src/app/index.tsx, examples/2-using-subscriptions/yarn.lock, examples/3-ssr-with-nextjs/components/App.js, examples/3-ssr-with-nextjs/components/ErrorMessage.js, examples/3-ssr-with-nextjs/pages/index.js, src/hooks/useDevtoolsContext.ts
When exploring your devtools I noticed that there were a lot of places where the component would be labelled as `<Unknown>` in the React devtools. This fixes this issue for the examples.
It also cleans out some stale deps and subdeps from the `yarn.lock` files.
=> (fix) - make all components in examples have displayNames in devtools

src/client.ts, src/hooks/useDevtoolsContext.test.ts, src/hooks/useDevtoolsContext.ts, src/hooks/useMutation.ts, src/hooks/useQuery.ts, src/hooks/useSubscription.ts, src/types.ts
(I added some tests for `useDevtoolsContext` first, before I started, just to check that it's still doing the right thing)
This replaces the `Error` stack to determine the current component name with a React Fiber approach, by looking at `ReactCurrentOwner`. This is generally safe and the data structure hasn't changed much since `react-reconciler` was implemented. There's also some guards in the implementation though just in case. But this is just for development after all.
The motivation behind this was that the stack approach can lead to incorrect names at times depending on the browser, minification in the app bundle, testing approach, and other factors, where the stack is unreliable.
So this looks at `ReactCurrentOwner`, which is a ref, checks whether we have a fiber (which we should) …
=> Replace useDevtoolsContext Error.stack with Fiber approach

docs/api.md, docs/architecture.md, docs/basics.md, docs/getting-started.md, src/exchanges/__snapshots__/fetch.test.ts.snap, src/exchanges/__snapshots__/subscription.test.ts.snap, src/exchanges/cache.ts, src/exchanges/fetch.ts, src/exchanges/ssr.ts, src/exchanges/subscription.ts, src/hooks/__snapshots__/useMutation.test.tsx.snap, src/hooks/__snapshots__/useQuery.test.tsx.snap, src/hooks/__snapshots__/useSubscription.test.tsx.snap, src/hooks/useMutation.test.tsx, src/hooks/useMutation.ts, src/hooks/useQuery.test.tsx, src/hooks/useQuery.ts, src/hooks/useSubscription.ts, src/types.ts
=> (feat)  Add support for the top-level extensions key in the GraphQL specification

src/client.ts
Fix #345
We run the entire exchange pipeline synchronously,
since that's predictable, which is how Wonka's
sources work.
When an exchange dispatches an operation, for
instance with reexecuteOperation, this operation
is hence run immediately, which can be confusing
and lead to state that disagrees with itself,
since the operation is essentially then "nested".
Instead what we want is to queue operations up
if they're dispatched nestedly, so from inside
an exchange, and flush this queue after the
original dispatch has completed.
=> Fix operation dispatching allowing nested operations

src/hooks/useImmediateState.ts, src/utils/index.ts, src/utils/ssr.ts
The `ssr` check was failing on React Native since it was kind of aggressive. I don't really want to even have it or `useLayoutEffect` in place, but multiple React threads didn't really resolve concerns that have been raised with it. Even `react-redux` uses it in this way.
I tried to find an alternative solution, but it turns out that `useState(s => s)` which would be firing at a similar time still triggers an update.
I've left a link to react-redux's repo since they're likely also be looking out for a solution to this problem.
=> Fix useImmediateState for React Native

src/index.ts
When trying out the graphCache exchange I noticed we were missing the formatDocument helper that is used inside that package.
Relevant line: https://github.com/kitten/urql-exchange-graphcache/blob/master/src/exchange.ts#L3
=> (fix) - export `formatDocument`

docs/README.md, docs/api.md, docs/architecture.md, docs/basics.md, docs/extending-and-experimenting.md, docs/getting-started.md, docs/guides.md, src/exchanges/ssr.ts, src/utils/error.ts
These changes were already applied to `urql-docs`, but never backported
=> Fix some British spellings in docs

docs/api.md, docs/basics.md, src/exchanges/ssr.ts
Previously it was impossible to use the `ssrExchange` together with `suspense` mode on the client-side, since the `ssrExchange` assumes that it's on the server, when the `suspense` mode is turned on.
This PR adds a separate `isClient` option to `ssrExchange`, so it can be told whether it's running on the client-side manually.
=> Fix ssrExchange's client-mode defaulting based on suspense-mode

src/hooks/useImmediateEffect.ts
I forgot to PR this (shame) 😆 
We can do the same with constants, which compile away
thanks to Terser. This saves a lot and since we're
not exposing the enum, it's 100% fine.
urql.min.js: 4.62 kB -> 4.55 kB
=> Remove enum in useImmediateEffect

README.md
Right now it links to not existing page. As I think it's not supposed to be like this, and `./docs/guides` is a right way................
=> fix(README.md): bad route to guides

src/hooks/index.ts
- exports the useDevtoolsContext hook - resolves https://github.com/FormidableLabs/urql/issues/382
tested by importing into the example project and logging the returned object.
=> exports useDevtoolsContext

package.json, rollup.config.js, src/components/Query.ts, src/components/Subscription.ts, src/exchanges/cache.ts, src/exchanges/debug.ts, src/exchanges/fetch.ts, src/exchanges/subscription.ts, src/utils/error.ts, src/utils/index.ts, src/utils/result.ts, src/utils/typenames.ts, yarn.lock
This accomplishes a couple of things.
Firstly it sets up Rollup to compile `process.env.NODE_ENV` to be `"production"` for our minified bundles so those accurately reflect what `urql` would compile to in a production environment.
Then it adds some initial bundle size optimisations:
- Remove rest spread from Query/Subscription components as it's not needed
- Replace `debugExchange` with a noop in production
- Remove usage of `addMetadata` with latency times from `fetchExchange` in production
- Remove fallback and fetch error for unknown operations in production
- Extract response/error parsing from `fetchExchange` and `subscriptionExchange` into a common file
This appears to currently save us about `0.3kB (4.62 kB => 4.32kB) min+gzip`
=> Make further bundle size optimisations

docs/extending-and-experimenting.md, docs/urql-outside-react.md
This PR is currently WiP, but I figured I'd get feedback early from folks. The purpose of this PR is to create a guide for using `urql` outside of React. Specifically, I'm focusing on highlighting how to use `urql`'s `client` directly, since that's the easiest way for non-React consumers to get access to the core functionality.
Currently, I have two examples for using `urql` with NodeJS. I'd like to add a basic example with Vue as well before merging.
The biggest issue I see with using `urql` in non-React codebases is the peer dependency on React, and the way our internal references to `react` require it being installed even in a Node or Vue environment where it isn't used. I'd be curious to see if our tree-shaking works out in a Vue environment. Regardless, this makes me think of two …
=> Add guide on using urql outside of React.

docs/basics.md, docs/getting-started.md
I should also fix these in the PR to urql-docs, the others mentioned are already fixed in urql master but aren't reflected to the docs publish yet
Resolves: https://github.com/FormidableLabs/urql/issues/390
=> (docs) - fix typos and invalid syntax

package.json, src/client.ts, src/components/Subscription.ts, src/exchanges/subscription.test.ts, src/exchanges/subscription.ts, src/hooks/__snapshots__/useSubscription.test.tsx.snap, src/hooks/useQuery.test.tsx, src/hooks/useQuery.ts, src/hooks/useSubscription.test.tsx, src/hooks/useSubscription.ts, yarn.lock
Resolve #407 
I think the idea of adding "active teardowns" is pretty valuable. It may be required in the future for someone to actively cancel ongoing queries from exchanges. This is already necessary to correctly implement ending subscriptions.
This hence also adds missing features to the `useSubscription` hook, like `executeSubscription` and `args.pause`. It also ensures that the `handler` arg is a constant ref, since reexecuting subscriptions when it changes wouldn't make much sense.
Wonka had a slight bug in `onEnd`. The operator wasn't propagating `Close` signals correctly, so the use of `onEnd` would prevent unsubscriptions from propagating upwards.
=> Implement active teardowns and add useQuery features to useSubscription

CONTRIBUTING.md, src/hooks/useMutation.ts
And removed non-existing `build:types` entry from contributing doc
=> Fixed executeMutation type in useMutation hook result

src/client.ts, src/hooks/useRequest.test.ts
Subscriptions and Suspense don't work together at this point so we have to prevent from making our Subscriptions a suspended source.
=> (fix) - exclude subscription from becoming a suspenseSource

rollup.config.js, scripts/transform-pipe.js
If this works well I'll probably publish this separately, so we can reuse it. ~Right now it doesn't check whether the import actually matches up with the callee name `pipe` and whether it's present.~
=> Add babel transform to deconstruct Wonka's pipe

src/context.ts, src/hooks/useMutation.ts, src/hooks/useQuery.ts, src/hooks/useSubscription.ts
Fix #227 
This adds a new `useClient` hook for convenience and warns when the default client is used, informing the user why requests are made to `/graphql`.
In the future we may just remove the default, but that'd be a breaking change.
=> Add useClient and warning when default client is used

examples/1-getting-started/src/app/components/Todo.tsx
update todo example so toggling the todo does also work for graphcache. This because we were lacking the complete property. An empty response does not give context about the performed operation to graphcache.
=> (chore) - update example 1 to work with both caches

package.json, src/index.ts, src/utils/index.ts, src/utils/request.ts, src/utils/stringifyVariables.test.ts, src/utils/stringifyVariables.ts, yarn.lock
The problem with having `fast-json-stable-stringify` is that it's the only package that doesn't support ESM. This means that by using it we completely forgo the possibility of supporting ESM browser imports even for `urql/core` in the future.
This replaces the package with an embedded implementation that works the exact same. It's exported so that it can be reused in `@urql/exchange-graphcache`, however it works the same, so it's completely backwards compatible.
This also shaves off some bytes, since we're getting rid of some options and configuration in `fast-json-stable-stringify` that we don't need.
=> Replace fast-json-stable-stringify

src/exchanges/cache.ts
Fix issue where a null data response with an error will result in cached errors
=> Cache fix for null data

.github/workflows/ci.yml
Changed the trigger to pull_request this enables the CI for forks. push will only trigger for pushes/pull requests on the exact repository.
=> (chore) - make CI run for external pull requests

examples/3-ssr-with-nextjs/src/with-urql-client.js
While spinning up my first nextjs project (experienced with react/urql), I ran into a eslint error [where `ctx` was not defined for `getInitialProps`](https://github.com/FormidableLabs/urql/compare/master...kysley:fix/example-nextjs-ssr#diff-d531117c918a8b6531456cf0f269e13bL17). 
**The HOC works as expected without this change, but was confusing for somebody who is new to nextjs.** 
The other changes are prettier formatting.
=> (chore) - don't destructure getInitialProps

examples/3-ssr-with-nextjs/components/PostList.js, examples/3-ssr-with-nextjs/pages/index.js, examples/3-ssr-with-nextjs/src/with-urql-client.js, src/client.ts
This is mainly meant to be an entry point for discussion, this shows how we would fix the nextjs example. The issue is that an error gets thrown in the getInitialProps meaning that we can't prefetch data. Something we wanted to enable with the `query` method.
This isn't the ideal solution yet but as it stands i'm a bit at a loss, for example putting getInitialProps in PostsList will make it so that that getInitialProps is never reached.
This wasn't easy to debug so this could be detriment to another deeper issue.
I have tried doing the following with prepass aswell:
```
await ssrPrepass(
<AppTree
pageProps={{
...appProps,
urqlClient
}}
/>, e => {
if (e && e.type && typeof e.type.getInitialProps === 'function') {
return e.type.getInitialProps();
}
}
);
```
In my opinion it's just …
=> (fix) - resolve issues with next example

docs/guides.md
add missing "variables." prefix to path map entries
=> (docs) - fix file upload exchange example

src/exchanges/cache.test.ts, src/exchanges/cache.ts, src/hooks/__snapshots__/useMutation.test.tsx.snap, src/hooks/__snapshots__/useQuery.test.tsx.snap, src/hooks/__snapshots__/useSubscription.test.tsx.snap, src/hooks/useMutation.ts, src/hooks/useQuery.spec.ts, src/hooks/useQuery.ts, src/hooks/useSubscription.test.tsx, src/hooks/useSubscription.ts, src/types.ts
This adds a new `stale?: boolean` flag to `OperationResult` that exchanges can use to indicate whether they're still fetching more data in the background (like with `cache-and-network` or graphcache's partial results)
Hooks will normalise this flag to `stale: boolean` and pass it through to their results.
This supersedes: https://github.com/FormidableLabs/urql/pull/444
=> Allow stale to be returned by exchanges

package.json, rollup.config.js, yarn.lock
Fix #450 
See: https://github.com/kitten/react-wonka/pull/1
This upgrade `react-wonka` to fix an issue where updates weren't propagated to context providers. This seems to be closely related to some kind of React internals that cause these kinds of updates to be run twice (presumably in two separate Fiber phases) to update the context consumers.
This also now externalises `react-wonka`, in case we need to push out another patch.
=> Fix react-wonka update bug that occurs with Context Providers

src/client.ts
Doing this allows me to reuse the types generated by GraphQL Code Generator to have a better typed experience via the client instance APIs.
For e.g.
```typescript
import { createClient } from 'urql';
import { LoginMutation, LoginMutationVariables, LoginDocument } from '../graphql-code-generated';
const urql = createClient({ url: 'http://localhost:1234/graphql' });
urql
.mutation<LoginMutation, LoginMutationVariables>(
LoginDocument, 
{ email: 'foo@bar.com', password: 'baz' }
)
.toPromise()
.then(result => {
return result.data ? result.data.login.email : undefined;
});
```
=> Adds generic parameters to the query/mutations APIs of client

README.md
We don't allow for passing variables to `executeQuery` as far as I know, these are only made through the `useQuery` and `useRequest`
=> remove confusing example

src/utils/error.ts
So I think this is better than relying on the `Error` instance received from the backend having an `originalError` property this way we allow for our users to have enriched errors with for instance `code` or `key`.
In the docs they also state this to be an `Error` instance so I think this is perfectly valid https://graphql.org/graphql-js/error/#graphqlerror
Resolves: https://github.com/FormidableLabs/urql/issues/469
=> add originalError

docs/guides.md
These updates would have helped me when learning to write exchanges.  They add context for the noop exchange, comment the examples' anonymous ExchangeIO function, explain what happens with forwarded + returned streams, where operationResults get created, and how request/response relate to forward/return.
=> exchange authoring guide clarifications for Urql noobs

src/utils/stringifyVariables.test.ts, src/utils/stringifyVariables.ts
For some reason when I tried to include the library locally I got an error about Invalid hook calls:
`Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:`
So I was not able to test if it fixes those for sure
This possibly: 
fixes #479 and fixes #478
=> fix problem with stringifying date objects

package.json, src/client.test.ts, src/client.ts, yarn.lock
Fix #501 
Fix #502 ~(Needs to be verified)~
Edit: The fix was confirmed by testing against CodeSandboxes in both of the above issues :+1:
wonka@^4.0.0 has some improved behaviour that fixed
some edge cases and bugs. As it turned out urql was
relying on one of them.
The switchMap in the hooks would cancel the last
query and start the next. However, this cancellation
cascades not only up to executeQuery to end and
teardown the operation, it also flows up through the
exchange pipeline, ending the entire thing like an
electrical surge.
This can be prevented by publishing the results
chain and making sure it can never be interrupted.
=> Fix cascading cancellations from components

package.json, src/utils/toSuspenseSource.test.ts, src/utils/toSuspenseSource.ts, yarn.lock
This is a combined set of quirks that needed to be fixed. This PR also simplified the `toSuspenseSource` implementation as a shorter one is possible.
Essentially `wonka` had a problem with forwarding values in a `switchMap` operator, when the value was sent immediately on subscription before the operator had time to start.
The `react-wonka` implementation on the other hand would send a teardown even after the component suspended, which isn't necessary.
Lastly, all combined, a teardown operation would be sent at the wrong time and when React unsuspended the subtree it would create two new subscriptions which would cause the latest subscription to always miss the newest result.
See: https://github.com/kitten/react-wonka/pull/10
See: https://github.com/kitten/wonka/pull/69
=> Fix synchronous suspense cases on client-side

src/client.ts
This stems from a twitter conversation where the undefined url would lead to an error in a minimalistic fetch-shim.
=> warn when creating a client without url

src/exchanges/ssr.test.ts, src/exchanges/ssr.ts
Fix #508
In all error cases the ssrExchange would be generated
while assuming that networkError may never be undefined.
This could cause an edge case where networkError was
set to Error('undefined') on the client-side.
=> Fix error serializer/rehydrator in ssrExchange

src/hooks/useSource.ts
This stops us from creating temporary subscriptions when useSubscription
calls getCurrentValue in useEffect. This may happen because React first
checks whether it has missed any values.
Due to this change we may miss changed values, but this shouldn't be
an issue, because `subscribe` is pretty reliable in returning up-to-date
state.
=> Modify subscribe in useSource not to allow getCurrentValue in effects

package.json, scripts/rollup/config.js, scripts/rollup/plugins.js, yarn.lock
This will run `sucrase` instead of TypeScript in the Rollup build on CI. This means we won't get full `dist/types/` output on CI, but since we have a separate `tsc` step that should be safe, so we can prioritise better speeds on CI.
- Fix `extensions` on `resolve` plugin
- Add `sucrase` for `CI=true` builds
=> Add sucrase for typescript-stripping in CI

CONTRIBUTING.md, exchanges/graphcache/tsconfig.json, package.json, packages/core/tsconfig.json, packages/preact-urql/tsconfig.json, packages/react-urql/tsconfig.json, packages/svelte-urql/tsconfig.json, scripts/jest/preset.js, scripts/rollup/build.js, scripts/rollup/plugins.js, scripts/rollup/settings.js, tsconfig.json
This fixes the `tsconfig.json` setup in all packages and introduces a new package naming convention so the `tsconfig.json` files won't have to change or be maintained in the future.
- Update `compilerOptions.path` convention
- Add new `tsconfig.json` files to all packages
- Ensure that `dist/types` will be built correctly for all packages
- Fix Jest's `moduleNameMapper` option
=> Fix tsc and Jest setup for paths mapping

.changeset/famous-ducks-smash.md, exchanges/graphcache/src/store/store.ts
This should make life easier on people using custom updaters with mutations/subscriptions
Resolves: https://github.com/FormidableLabs/urql/issues/537
- Moves away from Data return value for the `updater` function for `updateQuery` and goes to `DataFields` this type doesn't need `__typename` to be present
- Adds a fallback for `__typename` in the updater function.
=> fix updateQuery updater function type

.changeset/tiny-goats-type.md, packages/core/src/exchanges/subscription.ts
This adds an option to the `subscriptionExchange` to let it handle `query` and `mutation` operations as well.
Resolve #543
=> Add option to let subscriptionExchange handle all operations

exchanges/graphcache/src/helpers/help.ts
Links to graphcache warnings are out of date. 
https://github.com/FormidableLabs/urql-exchange-graphcache/blob/master/docs/help.md# is a 404, updates the pattern to https://github.com/FormidableLabs/urql/blob/master/docs/graphcache/help.md#
=> Fixes graphcache warning & error links

packages/site/src/components/navigation.js, packages/site/src/components/sidebar.js, packages/site/src/html.js, packages/site/src/screens/docs/article.js, packages/site/src/screens/docs/header.js, packages/site/src/screens/docs/index.js, packages/site/src/styles/global.js, packages/site/src/styles/theme.js
Add new styling to improve the docs look and feel on mobile/tablet viewports.
- Legend is now hidden on below `lg` width
- On mobile width the `urql` icon is now hidden
- There is an open/close sidebar button top right on small widths
- On small widths the sidebar is now `100%` width
- Pull the open/close logic into the `Docs` component so that it was available to stop scrolling in `Article`
=> Update Docs View for Mobile/Tablet 

.changeset/fluffy-guests-begin.md, exchanges/graphcache/src/cacheExchange.ts, packages/core/src/client.test.ts, packages/core/src/exchanges/cache.test.ts, packages/core/src/exchanges/cache.ts
`cache-only` currently dispatches a network-call when the result isn't in cache.
- Add a `cache-only` filter so the operation does not get forwarded in doc-cache.
- Moves the `graphcache` operations outside of `forward` so we can add the same filter as introduced in doc-cache
Issue: https://github.com/FormidableLabs/next-urql/issues/39#issuecomment-588901815
=> Fix cache-only for the caches

.changeset/stupid-lizards-return.md, docs/graphcache/help.md, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/types.ts
For use cases described in [this issue](https://github.com/FormidableLabs/urql/issues/559) an `invalidate` method seemed very suitable. Now we can remove an entity (with its properties) from the cache.
This has an added benefit that it removes links, if the links has no more ties with other entities it will get garbage collected.
> Note that schema awareness can cause a `null` in your data if this is marked as optional (partial result)
- Adds `cache.invalidate`
=> (graphcache) - Invalidating entities

package.json
Windows doesn't recognise the `shebang`
=> make the build-command work on windows

exchanges/graphcache/src/types.ts
This fixes the `cache` typings to include the newly added `invalidate` function.
=> (graphcache) - fix cache type

packages/site/package.json, packages/site/plugins/preact/node.api.js, packages/site/static.config.js, yarn.lock
Static websites don't need much special things, let's use Preact to make it faster, smaller and Preact-y
- docs site uses Preact
=> Use preact for the docs-site to lower bundle size

.changeset/sharp-students-flash.md, packages/core/src/exchanges/subscription.ts
Fix #576
The `subscriptionExchange` now supports queries and mutations using the `enableAllOperations?: boolean` flag. However, it actively tears down, i.e. closes, active queries since for subscriptions the server may tell the client that subscriptions have ended.
For queries and mutations this doesn't apply though as we want to keep them active indefinitely.
=> Prevent active teardown for queries on subscriptionExchange

exchanges/graphcache/src/helpers/help.ts, exchanges/populate/src/helpers/help.ts
Shorten url's for the help files, this reduces bundle size
=> shorten help urls

.changeset/good-swans-cough.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/store/data.test.ts, exchanges/graphcache/src/store/data.ts
The commutative squashing would previously only start when
the lowest commutative layer (the first one) was written.
This ignored the case however of when this layer has already
been written. When this was the case the stopping condition
was unreachable and commutative layers were never squashed.
The change is to continuously squash the commutative layers
with the least priorities as they're written.
This change also gets rid of the temporary `squash` queue,
which ends up making it a rather nice implementation.
Resolve #574
=> Fix commutative squashing failing when lowest layer resolved earlier than others

.changeset/two-guests-hide.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/store/data.test.ts, exchanges/graphcache/src/store/data.ts, exchanges/graphcache/src/store/index.ts
Previously a commutative layer would be deleted when a `teardown` event came in, which wasn't respecting layers that may already have been written to. Instead the `teardown` now triggers an empty data change, which will only delete the layer if it exists and if it can be.
=> Fix teardown operation breaking commutative layers

.changeset/olive-donuts-talk.md, exchanges/graphcache/package.json
Externalise `@urql/exchange-populate` from `@urql/exchange-graphcache`'s build bundles.
=> Add @urql/exchange-populate as dependency to @urql/exchange-graphcache

exchanges/retry/src/retryExchange.test.ts, exchanges/retry/src/retryExchange.ts
In preparation for getting  `retryExchange` ready to publish:
- `retryExchange` now only returns an error if the max number of retries have been exceeded
- `retryCount` have been moved to operation context (removes unnecessary typings)
- Update tests to reflect that only 1 result should be returned per operation
=> Filter results that are being retried from retryExchange's output

.codesandbox/ci.json, exchanges/multipart-fetch/CHANGELOG.md, exchanges/multipart-fetch/README.md, exchanges/multipart-fetch/package.json, exchanges/multipart-fetch/src/__snapshots__/multipartFetchExchange.test.ts.snap, exchanges/multipart-fetch/src/index.ts, exchanges/multipart-fetch/src/multipartFetchExchange.test.ts, exchanges/multipart-fetch/src/multipartFetchExchange.ts, exchanges/multipart-fetch/src/test-utils.ts, exchanges/multipart-fetch/src/utils.ts, exchanges/multipart-fetch/tsconfig.json, yarn.lock
This adds a new exchange meant to extend the feature-set of our default `fetchExchange` to include file-uploads!
Working playground https://codesandbox.io/s/urql-upload-client-05pcn
Implements https://github.com/FormidableLabs/urql/issues/560
=> Add multipartFetchExchange package

.changeset/green-owls-pump.md, packages/core/src/exchanges/ssr.test.ts, packages/core/src/exchanges/ssr.ts, packages/core/src/utils/error.ts, packages/next-urql/src/types.ts
Resolves #562
This adds the missing serialization for `GraphQLError`s to the `ssrExchange` when the `GraphQLError` carries the `extensions` or `path` fields. These fields should be preserved even after server-side rendering so that it's possible to pass on metadata from the server-side to the client-side.
The `extensions` field is often used to carry error code or types.
- Add conditional `GraphQLError` serialization to `ssrExchange`
- Allow `Partial<GraphQLError>` as input for `CombinedError`
=> (core) - Fix ssrExchange not serializing extensions or path on GraphQLError

.changeset/funny-parents-beg.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/store/data.test.ts, exchanges/graphcache/src/store/data.ts, scripts/rollup/settings.js
This will now apply mutations (including optimistic updates for mutations) commutatively. Before the ordering was a little confusing in that overlapping queries and mutations would have data from the queries always take precedence, which isn't always expected.
- Remove direct `clearLayer` calls and instead have `initDataState` clean up optimistic updates.
- Let `commutativeKeys` in `data.ts` keep track of commutative query layers, while optimistic layers are only added to `optimisticOrder`
- Add consistent ordering of `optimisticOrder` instead of prioritising optimistic updates
- Prevent squashing layers when a layer has only optimistic results
=> (graphcache) - Apply commutativity to all operations

docs/advanced/README.md, docs/advanced/retry-operations.md, docs/advanced/testing.md, docs/api/README.md, docs/api/core.md, docs/api/retry-exchange.md, docs/api/retryExchange.md, docs/concepts/exchanges.md, exchanges/retry/README.md
This made me realise that we maybe need a way to react to for instance `rate limiting`, example: `waitFor(err) => number` and maybe something to react to `unauthorized` so the user can refetch a token. What do you think?
We'll also need a page to put the exchanges that don't need a lot of words:
- devtools (can become a dedicated page if we move the readme in the docs but is a sep repo)
- multipart-fetch
=> (docs) - Add docs for the retryExchange

.changeset/dirty-tips-sin.md, packages/next-urql/src/with-urql-client.tsx
Passes down `urqlClient` in `withUrqlClient.getInitialProps`, this prevents the HOC from having to call `initUrqlClient` again.
If anyone has suggestions for a test feel free to throw them out there since `typeof window === undefined` in tests
Implements https://github.com/FormidableLabs/urql/issues/582
Passes down `urqlClient` in `withUrqlClient.getInitialProps`
=> (next-urql) - call init once browser side

.changeset/metal-otters-mate.md, exchanges/graphcache/src/operations/write.ts
This is potentially a missing piece to use Graphcache to fully simulate a schema.
When simulating queries, they can be written using `write` and queried using `query`.
To simulate mutations we currently only have `writeOptimistic` + `opts.optimistic` + `opts.updates` to generate a mutation result from scratch. To get around this one would need the `writeOptimistic` result.
This can then be enriched, e.g.:
```js
import { createRequest } from '@urql/core';
import { writeOptimistic, query, write } from '@urql/exchange-graphcache';
const store = new Store(/* ... */);
/** This would fully simulate a mutation using optimistic updates, queries so that resolvers can update the data, then writes it back permanently, assuming that the resolvers return serialisable data. */
const mutation = (query, …
```
=> (graphcache) - Expose data on write and writeOptimistic results

.changeset/red-candles-decide.md, packages/core/src/utils/maskTypename.ts
Fixes https://github.com/FormidableLabs/urql/issues/620
`typeof null === 'object'` so we need to check if we have a truthy value before going into this branch.
- add check for `maskTypenames` to see if we are dealing with a truthy value before checking the object properties.
=> (core) - fix maskTypenames clauses

.changeset/fresh-cars-sip.md, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/extras/relayPagination.test.ts, exchanges/graphcache/src/extras/simplePagination.test.ts, exchanges/graphcache/src/operations/invalidate.test.ts, exchanges/graphcache/src/operations/query.test.ts, exchanges/graphcache/src/operations/write.test.ts, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/test-utils/examples-1.test.ts, exchanges/graphcache/src/test-utils/examples-2.test.ts
This changes `cacheExchange` to just pass on its options and `Store` to accept an options object as well to make it easier to use directly.
```js
// before:
new Store(
undefined, // schema
{ /* resolvers */ },
{ /* updates */ },
{ /* optimistic */ },
{ /* keys */ },
);
// after:
new Store({
schema: undefined,
resolvers: {},
updates: {},
optimistic: {},
keys: {},
});
```
`storage` is exempted since the rehydration logic is coupled to the `cacheExchange` (for now). Bundle size remains unchanged.
=> (graphcache) - Change Store constructor to accept options object

.changeset/dull-zebras-burn.md, exchanges/graphcache/src/store/data.test.ts, exchanges/graphcache/src/store/data.ts
Resolve #625 
For any uninitialized layers, commutative or otherwise, `cache.inspectFields` would lead to an "of undefined" exception.
- Fix undefined exception in `data.ts`
- Prevent regression with additional test
=> (graphcache) - Fix inspectFields for uninitialized layers

.changeset/khaki-jeans-report.md, docs/api/graphcache.md, exchanges/graphcache/src/operations/invalidate.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/types.ts
If a user wanted to quickly get rid of a list or another complex part of an entity, invalidating the entire entity may be overkill or impossible, especially if they're seeking to invalidate `Query.list` for instance.
This addition does not impact or increase the bundlesize as far as I can tell.
- Move `invalidateEntity` to `operations/invalidate`
- Add support for invalidating a single field
=> (graphcache) - Add support for field-level invalidation to cache.invalidate

.changeset/lucky-hotels-scream.md, exchanges/graphcache/src/ast/index.ts, exchanges/graphcache/src/ast/variables.test.ts, exchanges/graphcache/src/ast/variables.ts, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/store/store.test.ts
Resolve #559 
Resolve https://github.com/FormidableLabs/urql-exchange-graphcache/issues/146
This allows untyped variables to be used inside operations and therefore inside updaters, which may be necessary to pass additional data to some updaters.
The filtering is preserved, it's moved to before the forwarding in `cacheExchange` however.
- Refactor `cacheExchange` logic
- Add `filterVariables` and fix `normalizeVariables`
- Use `formatDocument` and `filterVariables` only when operation is forwarded
=> (graphcache) - Fix variables being filtered in operations

.changeset/rude-toes-chew.md, packages/react-urql/package.json, packages/react-urql/src/hooks/useSource.ts, yarn.lock
Resolve #600 
This prevents us from triggering updates across components in render by preventing `getCurrentValue` from being able to trigger updates in other subscriptions with a simple global flag.
- Add global flag to `useSource`'s `getCurrentValue`
- Replace `use-subscription` with custom code
=> (react-urql) - Fix React warning on cross-component updates

.changeset/thin-wombats-bake.md, exchanges/graphcache/package.json, exchanges/multipart-fetch/package.json, exchanges/populate/package.json, exchanges/retry/package.json, exchanges/suspense/package.json, packages/core/package.json, packages/next-urql/examples/3-with-custom-exchange/package.json, packages/next-urql/package.json, packages/preact-urql/package.json, packages/react-urql/package.json, packages/svelte-urql/package.json, scripts/prepare/index.js, scripts/rollup/config.js, yarn.lock
Fixes: https://github.com/FormidableLabs/urql/issues/636
~Depends on: https://github.com/kitten/wonka/pull/80~ Published
Import maps in `Node 13` apparently need the full-path, to fully fix this we'll need to upgrade Wonka as well.
=> Fix the Node.js ESM import support for all packages

.changeset/stale-plants-bow.md, exchanges/graphcache/src/ast/variables.ts, exchanges/multipart-fetch/src/multipartFetchExchange.ts
The `extract-files` dependency has an explicit check for [an object](https://github.com/jaydenseric/extract-files/blob/master/src/extractFiles.mjs#L91) this makes our dictionary object not viable as a variables when combined with the multipart-fetch-exchange.
Fixes: https://github.com/FormidableLabs/urql/issues/635
- Use a normal object instead of our dictionary
=> (graphcache) - fix multipart/graphcache combination

.changeset/happy-keys-type.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/store/data.test.ts, exchanges/graphcache/src/store/data.ts
Resolve #633 
Previously the `cacheExchange` code had trouble with results coming in "spontaneously". It also erroneously created optimistic layers for queries and mutations at the wrong time. `createLayer` exacerbated the issue by not being idempotent.
On a side note, sorry for commutativity causing issues for some of you! But we believe that it'll eventually strengthen our caching guarantees and make all caching operations more predictable in the face of timing changes. So we hope that after ironing out its flaws and adding more tests that it'll be a great addition!
- Move `optimisticUpdate` logic into the later `prepareForwardedOperation` to avoid further mistakes
- Fix `noopDataState(store.data, operation.key, true /* meaning optimistic */);` from being called for all queries and …
=> (graphcache) - Fix edge cases in operation ordering

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/config.yml
GitHub doesn't seem to support a root `ISSUE_TEMPLATE` and a set of them in a folder so I followed [this](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) and made a community health file instead.
At this moment making an issue is bugged, it won't get to the bug/question part.
=> (GH) - update issue template

.changeset/rich-camels-hunt.md, exchanges/graphcache/package.json, exchanges/multipart-fetch/package.json, exchanges/populate/package.json, exchanges/retry/package.json, exchanges/suspense/package.json, packages/core/package.json, packages/next-urql/package.json, packages/preact-urql/package.json, packages/react-urql/package.json, packages/svelte-urql/package.json, scripts/prepare/index.js, scripts/rollup/config.js, yarn.lock
Resolve #644 
Resolve #640 
This fixes a quirk in webpack when entering a module it would transition to using the `pkg.json[main]` for the rest of the resolution path.
=> Fix node-resolution for Webpack

packages/site/src/components/scroll-to-top.js
I was solving a similar problem in the formidable.com rewrite, taking inspiration from this slick implementation and noticed that the value returned from `match` was not being treated as an array here.
- add `parsePathname` function and handle returned value like an array
=> fix match usage

.changeset/tough-bats-sniff.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/operations/write.ts
Their was a scenario where a mutation without selectionset would cause a call to its respective updater function.
```gql
mutation {
someUpdate
}
```
As you can see the above has no selectionset, this would cause the `writeSelectionSet` not to check if there was an actual optimistic-entry for the current rootField
Fixes: https://github.com/FormidableLabs/urql/issues/653
- fix no selectionset mutation updates in optimistic phase
=> (graphcache) - fix no selectionset mutation updates in optimistic phase

.changeset/twelve-trainers-sing.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/operations/write.ts
This PR adds support for  adding optimistic values when there's no selectionSet for your mutation.
- Add optimistic support for mutations without selectionset
=> (graphcache) - optimistic support for mutations without selection

.changeset/wicked-cows-heal.md, packages/core/src/utils/stringifyVariables.test.ts, packages/core/src/utils/stringifyVariables.ts
Resolve #649
When two operations with a `File` in the variables are sent the operation key would likely be the same since we never take any `File` attributes into account.
We'd hence like to have special handling for objects without any enumerable keys that also aren't plain objects.
- Add random (but stable) keying for objects without enumerable keys that aren't plain objects
=> (core) - Fix stringifyVariables (and thus operation keys) for Files

.changeset/cold-socks-juggle.md, exchanges/graphcache/src/ast/variables.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/write.ts
As discussed, this may cause more confusion than what it's worth.
=> (graphcache) - Remove dictionary data from results

packages/core/src/client.ts, packages/core/src/exchanges/dedup.ts, packages/core/src/exchanges/fallback.test.ts, packages/core/src/exchanges/fallback.ts, packages/core/src/exchanges/fetch.test.ts, packages/core/src/exchanges/fetch.ts, packages/core/src/exchanges/index.ts, packages/core/src/types.ts
Add debug dispatches for key events in fetch and fallback exchanges
=> Add debug dispatches for fetch + fallback exchanges

exchanges/graphcache/src/cacheExchange.ts, exchanges/retry/src/retryExchange.ts, packages/core/src/exchanges/cache.ts, packages/core/src/types.ts
- As above
- Change the `retryCount` increment logic
--- 
Do you think it would be useful to log any other graphcache events that I've missed?
=> Add debugEvent dispatches for retryExchange and graphcacheExchange

packages/site/package.json, packages/site/src/components/sidebar.js, packages/site/src/screens/docs/index.js, yarn.lock
- Bump react-static-plugin-md-pages
- Remove useMarkdownPage dependency from sidebar
- Loading sidebar now shows routes
=> Docs: Persist sidebar routes while loading

.changeset/curly-moons-kick.md, packages/core/src/__snapshots__/client.test.ts.snap, packages/core/src/client.test.ts, packages/core/src/client.ts, packages/next-urql/src/__tests__/with-urql-client.spec.tsx
Fix #668 
This fixes an edge case that was missed in #662.
The queue wasn't marked as being started by the first `client.dispatchOperation`, which means that the queue is then emptied by the first `client.rexecuteOperation` call instead. This doesn't cause any issues usually, but with the `dedupExchange` we'll accidentally deduplicate reissued operations, which are usually used to implement fetching for `stale` results or `cache-and-network` operations.
- Fix queuing behavior in `client.dispatchOperation`
- Add test for operation & result ordering
- Remove `client.exchange` (private variable)
=> Fix cache-and-network/stale on client.reexecuteOperation queue

.changeset/sweet-ghosts-share.md, exchanges/graphcache/benchmark/suite.js, exchanges/graphcache/src/operations/invalidate.test.ts, exchanges/graphcache/src/operations/invalidate.ts, exchanges/graphcache/src/store/__snapshots__/store.test.ts.snap, exchanges/graphcache/src/store/data.test.ts, exchanges/graphcache/src/store/data.ts, exchanges/graphcache/src/store/defer.ts, exchanges/graphcache/src/store/keys.ts, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/types.ts
This contains a stable implementation of persistence that combines its run with the garbage collection run and takes commutativity into account using a new approach that squashes layers on-the-fly.
=> Implement new persistence logic compatible with commutativity

.changeset/rotten-jobs-count.md, exchanges/multipart-fetch/src/multipartFetchExchange.test.ts, exchanges/multipart-fetch/src/multipartFetchExchange.ts, packages/core/src/exchanges/fetch.test.ts, packages/core/src/exchanges/fetch.ts
This always parses JSON data in all fetch exchanges and falls back to generating errors when it's safe to do so, i.e. when the data isn't GraphQL data. When we can't parse the response we also fall back to our previous error logic, but we also account for `new Error('No Content')` in case of success scenarios.
`4.43 kB -> 4.46kB`
- Update `executeFetch` in `fetchExchange`
- Update `executeFetch` in `multipartFetchExchange`
=> Fix non-2xx GraphQL responses on fetch exchanges

.changeset/modern-weeks-retire.md, exchanges/graphcache/package.json, packages/preact-urql/package.json, packages/react-urql/package.json, packages/svelte-urql/package.json
Forcefully bump @urql/core package in all bindings and in @urql/exchange-graphcache.
We're aware that in some cases users may not have upgraded to @urql/core, even though that's within
the typical patch range. Since the latest @urql/core version contains a patch that is required for
`cache-and-network` to work, we're pushing another patch that now forcefully bumps everyone to the
new version that includes this fix.
=> Bump @urql/core in urql, @urql/preact, @urql/svelte, Graphcache

docs/concepts/core-package.md, docs/concepts/philosophy.md, docs/concepts/stream-patterns.md
Typo fix in docs
```
- toopls
+ tools
- framewrk
+ framework
- [We've previously seen
+ We've previously seen
```
=> Fix typos in docs/concepts

.changeset/eighty-plants-pump.md, package.json, scripts/rollup/plugins.js, yarn.lock
Adds [`babel-plugin-modular-graphql`](https://github.com/kitten/babel-plugin-modular-graphql) to rewrite `graphql` imports to their modular variants.
=> Add babel-plugin-modular-graphql to rewrite graphql imports

packages/react-urql/examples/1-getting-started/src/graphql/index.ts
Minor to fix parsing of inline arguments in mutations. Previously, the below would fail (tested in devtools)
```gql
mutation AddTodo {
addTodo(text: "Install devtools") {
id
}
}
```
=> Fix resolver on React example (inline arguments)

.changeset/young-eyes-call.md, packages/svelte-urql/src/operations/mutate.ts
Resolve #703 
Change `@urql/svelte`'s `mutate(query, variables, context)` signature to: `mutate({ query, variables, context })`.
=> Svelte: Update mutate to have an options argument for consistency

.changeset/few-trees-taste.md, package.json, yarn.lock
Fix #708 
Looks like we didn't sufficiently test #700 with `@urql/exchange-populate`, since it breaks in `graphql@<15`. This will be less risky in the future anyway, when populate is broken out of `@urql/exchange-graphcache` in the next major.
=> Fix @urql/exchange-populate visitWithTypeInfo import

.changeset/honest-mangos-rule.md, exchanges/graphcache/examples/persisted-store/src/app/index.tsx, exchanges/graphcache/src/store/__snapshots__/store.test.ts.snap, exchanges/graphcache/src/store/data.ts, exchanges/graphcache/src/store/keys.ts, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/types.ts
- ~Avoid illegal character \t which seems to be sometimes stripped in IDB~ (This turned out to be untrue and our example was simply broken. That being said, I think this is still a safer alternative)
- Move deserialization to keys.ts
- Add string sanitization
=> (fix) - Remove special character from persistence keys and sanitize

.changeset/eighty-turkeys-jam.md, packages/core/src/utils/stringifyVariables.ts, packages/next-urql/src/__tests__/with-urql-client.spec.tsx, packages/next-urql/src/with-urql-client.tsx
Resolves #707. 
In #707, @nickrttn pointed out that `ctx` wasn't available during all stages of SSR with `next-urql`. After some investigation with `console.trace`, it was clear that `ctx` _was_ available during execution of `withUrql`'s `getInitialProps` function, but _not_ during the `useMemo` that gets executed as part of the server side render.
The steps to fix this are twofold:
1. Move the call to create the `clientOptions` _after_ the check for an existing `urqlClient`. If we receive `urqlClient` from `getInitialProps`, we return early from the `useMemo`. This saves us from having to call `initUrqlClient` twice on the server side (the first call being in `getInitialProps`, the second call being inside `useMemo`, where `ctx` is `undefined`).
2. The above requires that we return …
=> next-urql: Ensure ctx in clientOptions is available during all stages of SSR

.changeset/loud-doors-think.md, exchanges/graphcache/extras/package.json, packages/core/internal/package.json
Make the extension unknown so it can decide for itself what it likes the most, this is similar to https://github.com/FormidableLabs/urql/blob/master/packages/core/package.json#L21
Fixes: https://github.com/FormidableLabs/urql/issues/732
=> (fix) - Fix internal and graphcache/extras main path

.changeset/strong-radios-judge.md, packages/core/package.json, packages/core/scripts/remove-empty-imports.js
Removes empty imports from both `@urql/core` and `@urql/core/internal`
=> add script to remove empty imports/requires

.changeset/afraid-flies-matter.md, scripts/rollup/plugins.js
Fix #736 
Work around a quirk in Metro Bundler which leads to incorrect minification due to a missing hoisted variable when a `process.env.NODE_ENV` if-clause is removed.
This happens due to variable re-use, and Metro isn't equipped to hoist variables itself.
=> Add workaround for minification quirk in Metro Bundler

docs/advanced/subscriptions.md
This PR fixes a small typo found on [this documentation page](https://formidable.com/open-source/urql/docs/advanced/subscriptions/#react--preact).
```diff
- what you would pass to `Array.prootype.reduce`.
+ what you would pass to `Array.prototype.reduce`.
```
=> Fix a typo in docs

.changeset/long-rocks-give.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/store/data.test.ts, exchanges/graphcache/src/store/data.ts
This makes a slight adjustment to the data layer reservation.
Optimistic Mutation layers are now not only cleared but will be
shifted to the front of the optimistic order queue when they're
written with a concrete result (non optimistic result).
The optimistic mutation layer is therefore still discarded but
the layer itself is reused, which allows for slight adjustments
in how layers are handled when they transition from being
optimistic to non-optimistic.
This also makes an adjustment that allows layers to transition
from being non-optimistic to optimistic. This shouldn't happen
in practice, but protects us from race-conditions.
=> (graphcache) - Shift mutation results to top layer

.changeset/little-chicken-ring.md, .changeset/seven-onions-check.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/helpers/dict.ts, exchanges/graphcache/src/operations/invalidate.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/store/data.test.ts, exchanges/graphcache/src/store/data.ts, exchanges/graphcache/src/store/index.ts, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/test-utils/examples-1.test.ts, exchanges/graphcache/src/test-utils/examples-2.test.ts, exchanges/graphcache/src/types.ts, package.json, yarn.lock
This PR implements both recommendations from RFC #747.
These changes have been validated and tested so far against @frederikhors' unexpected behaviour reproductions in CodeSandboxes:
- https://codesandbox.io/s/urql-svelte-cacheinvalidate-many-items-j89ru
- https://codesandbox.io/s/urql-svelte-add-mutation-back-to-list-t98y7
- Convert dependencies data structure from `Set<string>` to `type Dependencies = Record<string, true>`
- Keep track of optimistically updated dependencies (of type `Dependencies`)
- Block refetching of operations that have active optimistic updates and keep track of them (see above)
- Allow `executePendingOperations` to trigger refetch for previously blocked `cache-and-network` operations
- Keep track of optimistic mutation that are pending at the same time, and flush …
=> (graphcache) - Implement RFC for optimistic behavior enhancements

.changeset/smart-adults-suffer.md, packages/svelte-urql/src/operations/mutate.ts
Moves to a normal promise instead of the promise-like object. We'll probably have to look into a test-suite for this content before we go stable (and we're sure about the API)
=> (svelte) - Promise mutation result

.changeset/little-years-cough.md, exchanges/persisted-fetch/src/__snapshots__/persistedFetchExchange.test.ts.snap, exchanges/persisted-fetch/src/persistedFetchExchange.ts
Resolve #764
Previously the `persistedFetchExchange` wasn't correctly sending the SHA256 when a cache miss occurred.
=> (persisted-fetch) - Fix hash not being sent after Not Found error

.changeset/flat-buses-develop.md, .changeset/red-mails-mix.md, exchanges/graphcache/package.json, exchanges/multipart-fetch/package.json, exchanges/persisted-fetch/package.json, exchanges/populate/package.json, exchanges/retry/package.json, packages/core/package.json, packages/preact-urql/package.json, packages/svelte-urql/package.json, scripts/prepare/index.js, scripts/rollup/config.js, scripts/rollup/settings.js
Fix #770 
Fix #708
Adds the `./package.json` exports entry for Node 14.
- add `./package.json` to exports
=> Fix missing package.json entry in exports field

.changeset/slimy-chairs-sniff.md, exchanges/graphcache/src/operations/query.test.ts, exchanges/graphcache/src/operations/query.ts
Fix #768
This issue occurs when a previous selection determined a field to be `null`. A future selection that doesn't result in `null` is then forced to retrieved `prevData`, but isn't covering the `null` case.
This can happen with split selections on a single entity, e.g.
```
query Item {
...NullItem
...ValidItem
}
fragment NullItem {
item {
id
invalid # Suppose this causes the item to become null, due to an invalid field
}
}
fragment ValidItem {
item {
id
}
}
```
- On the first traversal, the `NullItem` fragment hits `invalid` which causes `Query.item` to become `null`
- On the second traversal, the `Validitem` fragment hits `id` and tries to write it, but `Query.item` is already `null`
This can only happen with schema awareness most of the time.
- Handle `prevData === null` by …
=> (graphache) - Fix query traversal for previous null fields

README.md, docs/advanced/debugging.md
- Put the "Browser Devtools" first, i.e. front and centre.
Most people are likely to access the page to debug and not to create
exchanges with debugging information, hence the Devtools should be
at the top with immediately actionable installation instructions.
- The intro for devtools was split up into too many headings.
Showing headings from `h1 > h2 > h3` in quick succession with only one
paragraph each is hard to read, so they're now using more full sentences
and bullet point lists instead.
- Devtools was nested in "consuming events". IMHO Consuming programmatically
compared to the Browser Devtools is very different for our users. Either
someone is reading this to *debug* or to *create a debugger* but never
really for both at a time.
- Remove `h4`. We don't use them;
- Shorten tips and …
=> (docs) - Restructure Debugging document

.changeset/weak-clocks-yawn.md, exchanges/graphcache/src/operations/write.ts
This fixes the typical Graphcache warnings for unkeyable entities to be muted for internal types, like `__Type`, which by convention start with double-underscores and are only used for any kind of introspection query.
- Replace "Invalid key" warning check with regex pattern
- Update regex pattern to include `^__`
=> (graphcache) - Fix unkeyable warnings for introspection results

.github/ISSUE_TEMPLATE/RFC.md
Following from our other RFCs, this PR adds a template for RFCs based on:
- https://github.com/FormidableLabs/urql/issues/683
- https://github.com/FormidableLabs/urql/issues/747
And with instructions in comments of the template that also match:
- https://github.com/FormidableLabs/urql/issues/423
- https://github.com/FormidableLabs/urql/issues/472
- https://github.com/FormidableLabs/urql/issues/360
This will allow outside collaborators to also propose wide-ranging changes (be it breaking changes or vast enhancements / features that lead to dramatic `@urql/core` changes)
Putting RFCs and proposals out in the open will hopefully encourage more people to weigh in with arguments for/against proposals, to note on caveats early on, or to collaborate on opinions on and suggestions for an …
=> (chore) - Add issue template for RFCs

.changeset/red-brooms-drive.md, .changeset/tiny-ducks-teach.md, exchanges/suspense/README.md, exchanges/suspense/src/suspenseExchange.ts
**NOTE: This doesn't affect server-side / SSR support! It's only for the `suspenseExchange` of the `@urql/exchange-suspense` package**
This adds a fix that would affect `subscription` operations, although they remain untouched by suspense-mode.
It also adds a deprecation note, since client-side suspense in `urql` isn't as stable as it should be and overall not very useful.
This PR will remain opened for discussion briefly, if anyone has good arguments as to why this package _shouldn't_ be deprecated.
=> (suspense) - Fix suspenseExchange affecting subscriptions and add deprecation note

.changeset/weak-rats-perform.md, packages/core/src/internal/fetchOptions.ts
When GET queries are used, and especially with persisted queries it is hard to debug them as only hash is displayed in network debugger. Urql already sends operationName when POST is used and this only adds the same value to url when GET is used.
- add operationName to GET queries query
=> Add operationName to GET queries

.changeset/big-worms-punch.md, exchanges/persisted-fetch/src/persistedFetchExchange.test.ts, exchanges/persisted-fetch/src/persistedFetchExchange.ts
Implements #799 
- Makes the `persistedFetchExchange` accept options
=> (persisted-fetch) - support persisted get

.changeset/light-birds-kneel.md, packages/next-urql/package.json, yarn.lock
Bump `react-ssr-prepass` to 1.2.1, this will allow terser to safely remove this import due to `sideEffects: false` being added.
Relates to: #801 
- Bump `react-ssr-prepass` to 1.2.1
=> (next-urql) - bump react-ssr-prepass

docs/graphcache/errors.md, exchanges/graphcache/src/ast/schemaPredicates.test.ts, exchanges/graphcache/src/ast/schemaPredicates.ts, exchanges/graphcache/src/helpers/help.ts, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/store/store.ts, scripts/jest/setup.js
As described in #810, when a schema is known, we want to validate `opts.keys`, `opts.updates`, `opts.resolvers`, and `opts.optimistic`.
When any of the validation fails, we want to warn the user (either via console or throwing an error).
*This PR only deals with `opts.keys`*, not the others (updates/resolvers/optimistic), to get feedback.
The issue I'd like feedback on is: If the new validation calls `console.warn`, we preserve backwards compatibility because no error is thrown that would change the real functionality. If the new validation throws an error, that is backwards incompatible and we would need to do a major version bump.
IMO, throwing an error is probably better, but until we are ready to do a major version bump, I think we should use `console.warn`.
Thoughts?
I will finish …
=> 810: Graphcache warnings for `opts.keys`

docs/graphcache/errors.md
This fixes the docs, there is an issue where an error thrown by `react-static` won't surface through the CI/CD and will just deploy the partially built site. https://circleci.com/gh/FormidableLabs/urql/5942?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
[The generated links](https://github.com/FormidableLabs/urql/blob/master/exchanges/graphcache/src/helpers/help.ts#L68) are broken atm, what would be the best way to go about this? We can't just start including the titles. Do we need to special case this in react-static?
Anchor transformed from to: #1 --> #1-invalid-graphql-document
Fixes: https://github.com/FormidableLabs/urql/issues/821
=> (docs) - Fix errors page links

.changeset/weak-pants-lick.md, docs/advanced/server-side-rendering.md, packages/next-urql/README.md, packages/next-urql/examples/1-with-urql-client/pages/index.tsx, packages/next-urql/examples/2-with-_app.js/pages/_app.tsx, packages/next-urql/examples/3-with-custom-exchange/pages/index.tsx, packages/next-urql/examples/4-with-navigation/pages/[pokemon].tsx, packages/next-urql/examples/4-with-navigation/pages/index.tsx, packages/next-urql/examples/5-with-suspense-exchange/pages/index.tsx, packages/next-urql/src/__tests__/init-urql-client.spec.ts, packages/next-urql/src/__tests__/with-urql-client.spec.tsx, packages/next-urql/src/init-urql-client.ts, packages/next-urql/src/types.ts, packages/next-urql/src/with-urql-client.tsx
This is a breaking change for `next-urql`, we were seeing a lot of confusion because of the `mergeExchanges` argument. This proposal streamlines it to the normal client.
However this does impose us to always specify a function for the creation of a client
Implements https://github.com/FormidableLabs/urql/issues/813
Still have to rewrite a lot of the testing.
TODO:
=> (next-urql) - streamline client creation

docs/graphcache/computed-queries.md, exchanges/graphcache/examples/persisted-store/README.md, exchanges/graphcache/examples/persisted-store/package.json, exchanges/graphcache/examples/persisted-store/public/index.html, exchanges/graphcache/examples/persisted-store/src/app/Messages.tsx, exchanges/graphcache/examples/persisted-store/src/app/index.tsx, exchanges/graphcache/examples/persisted-store/src/server/index.js, exchanges/graphcache/examples/persisted-store/src/server/schema.js, exchanges/graphcache/examples/persisted-store/webpack.config.js, exchanges/graphcache/examples/persisted-store/yarn.lock
While learning about Graphcache, I loaded this example in my browser: `exchanges/graphcache/examples/persisted-store`
Initially, I didn't understand how the different request policies interacted with a populated v.s. empty cache. @JoviDeCroock paired with me and explained it to me -- thank you Jovi!
The goal of this PR is to make it easier for URQL newcomers to play with different options.
* added some buttons to the example page to allow the user to easily configure the request policy, clear Graphcache's cache, and re-execute queries.
* made the message JSON pretty-print.
* added a `Message.message` resolver which upper-cases the property.
* this PR only changes the example and documentation. No implementation files are changed.
This screenshot shows the original page on the left, and …
=> Graphcache example: allow user to change Graphcache options via buttons on the page.

.changeset/hot-dryers-drive.md, docs/advanced/subscriptions.md, docs/api/core.md, packages/core/src/client.ts
Resolves #837 
Expose `client.subscription` to be correctly recognized by the exchange.
An only small addition to `@urql/core` API.
=> (core) - Expose client.subscription shortcut method

.changeset/thick-avocados-enjoy.md, docs/graphcache/errors.md, exchanges/graphcache/src/ast/schemaPredicates.ts, exchanges/graphcache/src/helpers/help.ts, exchanges/graphcache/src/operations/query.test.ts, exchanges/graphcache/src/operations/write.test.ts, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/test-utils/simple_schema.json, exchanges/graphcache/src/test-utils/utils.ts, scripts/jest/preset.js, scripts/jest/setup.js
As described in #810, when a schema is known, we want to validate `opts.keys`, `opts.updates`, `opts.resolvers`, and `opts.optimistic`.
When any of the validation fails, we want to warn the user via `console.warn`.
Validation for `opts.keys` has already been added in PR https://github.com/FormidableLabs/urql/pull/820
* `opts.updates.Mutation` and `opts.updates.Subscription` are now validated against the schema.
* `opts.resolvers` is now validated against the schema.
* `opts.optimistic` is now validated against the schema.
Resolves #810.
=> (graphcache) Validation for Graphcache's opts.updates, opts.resolvers, opts.optimistic

exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/shared.ts, exchanges/graphcache/src/operations/write.ts, scripts/babel/transform-invariant-warning.js
This should likely be batched with #840 (and #793)
It reduces the bundlesize of Graphcache using two small changes:
- Replace `SelectionIterator` with a `makeSelectionIterator` function. Curiously this doesn't reduce performance, so is 100% safe. This gets rid of a lot of unique variable names (due to instance properties) that aren't used anywhere else.
- Add some hoist-logic to the `transform-invariant-warning` Babel transform. I discovered that some statements were still sticking around, since we add the production-check below some if-statements for `warn` calls. Instead the plugin will now check whether one or more parents of the `warn()` call are if-statements only containing this call, and appropriately hoist the wrapped production check.
Bundlesize went from `6.3kB` to `6.17kB` …
=> (graphcache) - Implement opportunities to reduce bundlesize on Graphcache

.changeset/real-falcons-clap.md, exchanges/execute/package.json, exchanges/graphcache/package.json, exchanges/multipart-fetch/package.json, exchanges/persisted-fetch/package.json, exchanges/populate/package.json, exchanges/retry/package.json, exchanges/suspense/package.json, packages/core/package.json, packages/preact-urql/package.json, packages/react-urql/package.json, packages/svelte-urql/package.json, yarn.lock
Resolve #831 
This works around a bundling issue in React Native, which uses `uglify-es`, a deprecated minifier/uglifier. This caused invalid JS output, which would lead to errors.
This PR is set to bump all packages by a patch release to forcefully get users to use the new version, since it also saves on size and improves performance. Theoretically, this will prompt bundlers to upgrade `wonka` and deduplicate it either way, even if only one of these patches is installed.
=> (chore) - Upgrade to wonka@^4.0.14

.changeset/two-crews-share.md, docs/advanced/server-side-rendering.md, packages/next-urql/README.md, packages/next-urql/src/__tests__/with-urql-client.spec.tsx, packages/next-urql/src/types.ts, packages/next-urql/src/with-urql-client.tsx
Relates to: https://github.com/FormidableLabs/urql/issues/754
We need to implement a switch between `getInitialProps`, `getStaticProps` and `getServerProps` I've been browsing some examples but have not yet succeeded in finding a reasonable approach. This is a first step towards some common guidelines.
- Optionally bind `getInitialProps` to `withUrql`
=> (next-urql) - getStaticProps & getServerProps

.changeset/curly-bags-tap.md, packages/next-urql/src/init-urql-client.ts, packages/next-urql/src/with-urql-client.tsx
We shouldn't serialize the urql-client down to the client, we used to rely on this happening within `getInitialProps`, now that this isn't always present it'd be better to rely on `initUrqlClient` to handle this for us.
- add `client.toJSON = () => null` to `initUrqlClient` to prevent serialization between server and client.
=> (next) - prevent client-serialization even without getInitialProps

.changeset/rich-eels-shop.md, docs/graphcache/errors.md, exchanges/graphcache/src/helpers/help.ts, exchanges/graphcache/src/operations/query.ts
Resolve #858
Add warning for queries that traverse an Operation Root Type (Mutation / Subscription types occuring in a query result)
It's possible for someone to _explicitly_ use `Mutation` or `Subscription` inside `Query`, which by convention is discouraged and shouldn't be done. The worst that we do in such a case is now issue a warning, but I believe it's more important to prevent this mistake than to ignore it silentily, especially since it's extremely uncommon.
- Add check to `readSelection` for non-Query root types and issue warning
- Add explanation of the warning to `errors.md`
- Ensure that the warning logs out the relevant typenames
=> (graphcache) - Add root operation type traversal warning

.changeset/strong-games-scream.md, packages/core/src/client.ts, packages/core/src/utils/defer.ts, packages/core/src/utils/index.ts
Resolve #721
When an operation becomes asynchronous, by matter of an exchange
delaying it, while it also calls client.reexecuteOpoeration, we
were calling client.reexecuteOperation out-of-band, which causes
the reexecuted operation to be dispatched immediately.
We can't detect the intent of the exchange, and don't know that it
may afterwards immediately send a result synchronously after the delay,
but we do know that once an operation becomes asynchronous, the timing
of client.reexecuteOperation is not sensitive anymore. So instead we
now choose to defer it by a tick.
- Add a `defer` to `@urql/core`
- Defer flushing the queue actively in `reexecuteOperation` when no other operation is in-band and actively being worked on
=> (fix) - Fix timing for out-of-band client.reexecuteOperation calls

.changeset/tiny-tomatoes-bow.md, exchanges/graphcache/src/offlineExchange.test.ts, exchanges/graphcache/src/store/data.ts, exchanges/graphcache/src/store/defer.ts, packages/core/src/client.ts, packages/core/src/utils/defer.ts, packages/core/src/utils/index.ts
Removes the `scheduleTask` ponyfill helpers in favour of inline `Promise.resolve().then(fn)` calls.
The scheduleTask helper was useful because globally we can't
tell whether `Promise` has been polyfilled for IE11 yet.
However, where this is called we _can_ already be sure of
it being polyfilled, which we do assume in other places
of the codebase.
Therefore it's safe to replace the `scheduleTask` polyfill
with a simple inline `Promise.resolve().then(fn)` call, which
is also more obvious.
=> (chore) - Remove scheduleTask helpers

.changeset/thick-bees-decide.md, exchanges/graphcache/src/default-storage/index.ts, exchanges/graphcache/src/store/data.ts
Resolve #864 
This fixes an issue where deleted values wouldn't be persisted correctly, since the `default-storage` serializer coerced both `null` and `undefined` to `"null"` JSON values. The `@urql/exchange/default-storage` implementation now comes with a new serializer which is incompatible with the old one but should be faster and more correct. It's incompatible with the old one, so the default `idbName` has been bumped to `graphcache-v4`.
- Prevent optimistic layers from queueing up unnecessary keys onto the `data.persist` set
- Implement a new serializer and deserializer on `default-storage`
=> (graphcache) - Reimplement default-storage serializer/deserializer

.changeset/strange-donuts-listen.md, packages/svelte-urql/example/src/App.svelte, packages/svelte-urql/src/operations/mutate.ts, packages/svelte-urql/src/operations/query.ts, packages/svelte-urql/src/operations/subscription.ts
Resolve #706 
Resolve #854
Resolve #806
Resolve #795
The previous store implementations for `query`, `mutate`, and `subscription` were not as capable as we'd hoped. Two problems surfaced mainly:
- The state of `query` and `subscription` could not be preserved. Passing new arguments meant that the old state was lost
- The APIs were confusing. Svelte has many different ways to consume data and we only provided one that worked and was limited
To solve this there are now several more ways of using these bindings. To start with a simple one `mutate` now returns a `MutationStore`, which can be subscribed to, can be called itself to start a mutation, and can be used as a `PromiseLike`
```js
// Standard Usage:
mutate({ query, variables })()
// Subscribable Usage:
$: result = mutate({ query, …
```
=> (svelte) - Expand Readables with factory and PromiseLike methods

.changeset/green-lies-help.md, exchanges/persisted-fetch/README.md, exchanges/persisted-fetch/src/persistedFetchExchange.test.ts, exchanges/persisted-fetch/src/persistedFetchExchange.ts
This PR adds support for a custom hash function in the persisted query exchange. This is useful for non-browser environments like react-native, where you might want to use a different crypto API ([like Expo's](https://docs.expo.io/versions/v37.0.0/sdk/crypto/), for instance).
Usage:
```ts
import sha256 from "my-library";
const client = createClient({
url: 'http://localhost:1234/graphql',
exchanges: [
dedupExchange,
cacheExchange,
persistedFetchExchange({ generateHash: sha256 }),
fetchExchange
],
});
```
Adds an argument to the `persistedFetchExchange` factory. No breaking changes.
=> (persisted) - Add generateHash option to the persistedFetchExchange

.changeset/six-hornets-smile.md, exchanges/graphcache/src/offlineExchange.test.ts, packages/core/src/utils/request.ts, packages/core/src/utils/typenames.test.ts, packages/core/src/utils/typenames.ts
Resolve #879 
- Fix the formatDocument mutating parts of the original document
- Fix a formatted document from creating a different hash in createRequest
The latter works because `formatDocument` can be assumed to be called
by caches, like the cacheExchange, so they shouldn't ever alter the
resulting hash.
This does affect the minzipped size: `3.44kB => 3.46kB`
=> (core) - Fix formatDocument mutating original document

.changeset/kind-goats-carry.md, .codesandbox/ci.json, packages/next-urql/src/__tests__/init-urql-client.spec.ts, packages/next-urql/src/__tests__/with-urql-client.spec.tsx, packages/next-urql/src/init-urql-client.ts, packages/next-urql/src/with-urql-client.tsx
Fixes: https://github.com/FormidableLabs/urql/issues/883
[New sandbox](https://codesandbox.io/s/next-urql-pokedex-ko54t)
[Generated bundle](https://pkg.csb.dev/FormidableLabs/urql/commit/52ae6e87/next-urql)
disable suspense when we aren't binding getInitialProps, enabling thi…s without getInitialProps means we aren't using prepass which results in react-dom/server throwing an error about suspense not being supported server-side
- disable suspense when we aren't binding getInitialProps
=> (next-urql) - disable suspense when we aren't binding getInitialProps

.changeset/cuddly-ligers-design.md, exchanges/persisted-fetch/README.md, exchanges/persisted-fetch/src/persistedFetchExchange.test.ts, exchanges/persisted-fetch/src/persistedFetchExchange.ts, packages/core/src/utils/typenames.test.ts
This passes the parsed GQL document as a second parameter so it can be used to get an already calculated hash.
Resolves https://github.com/FormidableLabs/urql/issues/886
- add Second document parameter to `generateHash`
=> (persisted-fetch) - pass document as a second argument to the generateHash option

docs/advanced/auto-populate-mutations.md
The import line for populate should point to `@urql/exchange-populate`, not `@urql/exchange-graphcache`
One line documentation fix
=> Docfix: import populate from correct library.

docs/advanced/auto-populate-mutations.md
Removes duplicate (and also non existent) import of `populateExchange` from `@urql/core`
Changed file  `docs/advanced/auto-populate-mutations.md`
=> Remove duplicate of populateExchange import

.changeset/afraid-dragons-train.md, exchanges/graphcache/src/ast/schemaPredicates.ts, exchanges/graphcache/src/store/store.test.ts
Fixes: https://github.com/FormidableLabs/urql/issues/889
This adds a special case to our schemaPredicates to ignore the `__schema` field
- ads a special case to our schemaPredicates to ignore the `__schema` field
=> (graphcache) - add special case for fetching an introspection result in graphcache

docs/concepts/exchanges.md, exchanges/request-policy/CHANGELOG.md, exchanges/request-policy/README.md, exchanges/request-policy/package.json, exchanges/request-policy/src/index.ts, exchanges/request-policy/src/requestPolicyExchange.test.ts, exchanges/request-policy/src/requestPolicyExchange.ts, exchanges/request-policy/src/retryExchange.test.ts, exchanges/request-policy/tsconfig.json
Implements an exchange that monitors all incoming operations and checks them vs an internal map, if this operation is `cache-first` or `cache-only` and has exceeded the TTL it will upgrade this operation to a `cache-and-network` policy. This helps us refresh stale data.
The user can specify a custom TTL in ms
- add new exchange
=> (exchanges) - implement requestPolicyExchange

.changeset/six-shoes-kneel.md, packages/react-urql/src/hooks/useMutation.ts, packages/react-urql/src/hooks/useQuery.ts, packages/react-urql/src/hooks/useRequest.ts, packages/react-urql/src/hooks/useSource.ts, packages/react-urql/src/hooks/useSubscription.ts
This PR changes the definition of React Hooks to use `export function` instead of `export const`. It's a simple change that allow developers later to interact better with the signature of the hooks.
In TS, these `const` are defined as block-scoped variables, and cannot be overwritten/redefined/overloaded by external TS libraries or consumers. 
You can see a [real-time example for that here](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=12&pc=2#code/CYUwxgNghgTiAEBbA9sArhBByALiAzjlvAN4CwAUPNfAPS3wgAeADsjDvAGZoB2YOAJbJe8AO7sA1vko1Grdpx78hIpAE8AYnzAAKFrCiIAXPEIxBvAOYBKU+ctWA3JVk168th3hgRheMDIBLy44lJu1MxenL68-ojqAGqwpvqGJmY4FtY28AC8AHyZ2c6UAL6uFKCQsAgo6JjwuAREpBGeitw6qqIJ2vxpMEamvGiIAEYgMHbwoxNTLlQ0UZ2x8Ukp8IPDs2OT0-lFc-uLZUA)  , and it's [also reported as …
=> (react-hooks) prefer exported function instead of block-scoped variable

.changeset/chatty-poems-rescue.md, exchanges/graphcache/src/ast/schemaPredicates.ts
See: https://spectrum.chat/urql/help/is-there-a-way-to-access-cache-directly~40669292-345e-4c02-b5ca-64c95f776762?m=MTU5NTIzMDA5MDQ0Ng==
=> (graphcache) - Mute warnings when using built-in fields

.changeset/hip-adults-look.md, packages/core/src/utils/request.test.ts, packages/core/src/utils/request.ts
This shortens the querystring by removing whitespaces and comments when a request is created with an unparsed query.
=> (core) - Shorten queries for hashing

.changeset/pretty-squids-learn.md, packages/core/src/internal/fetchOptions.ts
Strips redundant whitespaces when using `GET`
This solves the case where the user provides their own queries, ....
Fixes: https://github.com/FormidableLabs/urql/issues/907
- Strips redundant whitespaces when using `GET`
=> (core) - Strip whitespace from query for GET requests

.changeset/hot-turkeys-deliver.md, exchanges/graphcache/default-storage/package.json, packages/preact-urql/src/hooks/useMutation.ts, packages/preact-urql/src/hooks/useQuery.ts, packages/preact-urql/src/hooks/useSubscription.ts, packages/react-urql/src/hooks/__snapshots__/useMutation.test.tsx.snap, packages/react-urql/src/hooks/__snapshots__/useQuery.test.tsx.snap, packages/react-urql/src/hooks/__snapshots__/useSubscription.test.tsx.snap, packages/react-urql/src/hooks/constants.ts, packages/react-urql/src/hooks/useMutation.ts, packages/react-urql/src/hooks/useQuery.ts, packages/react-urql/src/hooks/useSubscription.ts, packages/svelte-urql/src/operations/constants.ts, packages/svelte-urql/src/operations/query.ts, packages/svelte-urql/src/operations/subscription.ts
closes: https://github.com/FormidableLabs/urql/pull/918
closes: https://github.com/FormidableLabs/urql/issues/917
- Adds `operation` to the result of a query/mutation/subscription
=> (react/preact/svelte) - add operation to the result

.changeset/rotten-pandas-obey.md, docs/advanced/server-side-rendering.md, packages/next-urql/README.md, packages/next-urql/src/init-urql-client.ts, packages/next-urql/src/with-urql-client.tsx
Resolves: https://github.com/FormidableLabs/urql/issues/832
We can rename this to `_dangerous_reset_store` since this resets all the exchange states, ....
- Add function to invalidate current client instance
=> (next-urql) - Pass resetUrqlClient method to App/Page

.changeset/wet-cows-melt.md, exchanges/persisted-fetch/src/persistedFetchExchange.test.ts, exchanges/persisted-fetch/src/persistedFetchExchange.ts
In insecure browser environments, the `window.crypto.subtle` api isn't available. The default hashing function in the persisted query exchange will resolve an empty string in this case, and send that empty string as the persisted query, which leads to a `PersistedQueryNotFound` exception. This is fine, because the exchange will follow up with non-persisted query, but we can improve the default behavior by not sending a persisted query at all if the hash fails.
Updates the persisted query exchange to only send a persisted query if there's a non-falsey hash value. Let me know if there's a better way of implementing this with Wonka!
=> (persisted-fetch) - Don't send persisted queries if the hash operation fails

docs/graphcache/custom-updates.md
Adds an example of inspecting a non-rootfield
=> (docs) - add example of sub-field inspection

.changeset/clean-spiders-complain.md, packages/preact-urql/src/hooks/useRequest.ts
after upgrading to `@urql/preact@1.2.0`, I started getting an error where `prev.current` is sometimes `null`, which throws `TypeError: Cannot read property 'key' of null`
I wasn't able to test this bix with your build step, but it should transpile properly
we could probably drop the `prev.current !== undefined` with this fix, but I didn't want to change more than I had to because I don't have a ton of context on this project
=> fix(preact): handle case where `prev.current` is null

docs/graphcache/computed-queries.md, exchanges/graphcache/src/extras/relayPagination.test.ts, exchanges/graphcache/src/extras/relayPagination.ts
Some APIs allow you to requests pages of nodes, rather than individually-cursored items -- here is a good [writeup of why to do this](https://medium.com/javascript-in-plain-english/graphql-pagination-using-edges-vs-nodes-in-connections-f2ddb8edffa0). This patch handles pagination for either style of response. 
See example app and server at
* https://codesandbox.io/s/urql-relay-pagination-server-cuuc2?file=/example.graphql (server) and 
* https://codesandbox.io/s/urql-demo-client-t0d8o (app)
Added a helper just like relayPagination, but which iterated over a field called nodes, a direct list element of the page. It's appreciably simpler, as is node-style pagination.
This is not a breaking change.
=> (graphcache) - Add nodes support to relayPagination helper

.changeset/many-comics-grin.md, docs/api/core.md, packages/core/src/exchanges/error.test.ts, packages/core/src/exchanges/error.ts, packages/core/src/exchanges/index.ts
An exchange that allows inspecting all errors within the urql client.
```js
import { errorExchange, dedupExchange, fetchExchange } from 'urql';
const client = new Client({
exchanges: [
dedupExchange,
errorExchange({
onError: (error: CombinedError, operation: Operation) => {
console.log("An error!", error);
}
}),
fetchExchange
],
});
```
- adding an error exchange to urql core
- adding a note about the error exchange in the documentation site
- tests! 👏
=> (exchanges) implement error exchange

.changeset/pink-crabs-clean.md, packages/core/src/exchanges/ssr.test.ts, packages/core/src/exchanges/ssr.ts, packages/react-urql/src/test-utils/ssr.test.tsx
Resolves #961
This changes the `ssrExchange` to serialize its `OperationResult` data early into JSON so that mutations to it don't get picked up. Such mutations are made by Graphcache for instance, which is a feature to make past data match resolvers and other conditions. Here however, we care about the earliest version of the data from the `fetchExchange`.
Test with Reproduction: https://codesandbox.io/s/distracted-wozniak-tlfvf?file=/pages/index.js
- Update `SerializedResult[key: number]` to be of type `string | undefined`, i.e. JSON data
- Update tests and add new test to verify behavior
=> (core) - Fix mutable data for SSR exchange

.changeset/pretty-pillows-serve.md, packages/core/src/internal/fetchOptions.ts
Fixes: https://github.com/FormidableLabs/urql/issues/956
Remove the `content-type` from the headers when using GET.
- Remove the `content-type` from the headers when using GET.
=> (core) - Omit Content-Type header when using GET

exchanges/auth/CHANGELOG.md, exchanges/auth/README.md, exchanges/auth/package.json, exchanges/auth/src/authExchange.test.ts, exchanges/auth/src/authExchange.ts, exchanges/auth/src/index.ts, exchanges/auth/tsconfig.json
Currently, every user will have to build their own auth exchange for authentication, and token refresh. The motivation for this exchange is to provide a general api that enables auth and token refresh for both React and React Native.
The exchange will allow flexibility in:
- being used in React (web) or React Native (primarily the implication is that, the initial auth state can be fetched asynchronously or synchronously)
- what constitutes an auth error (e.g. a 401 or a specific error code)
- how to add auth to a request (format of the header(s))
- what auth state looks like (you can also store and use refresh token, token expiry or anything else)
- how to refresh token (using a REST or graphQL endpoint)
- how to react to errors (when to log the user out)
Once the exchange is created, we …
=> (exchanges) implement auth exchange

.changeset/old-pets-watch.md, packages/react-urql/src/hooks/useSource.ts
Fixes https://github.com/FormidableLabs/urql/issues/955
During fast-refresh effect cleanup is called simulating an unmount, we're removing the isMounted flag to prevent this. Essentially we could also duplicate this flag to the body of the atm removed `useEffect` however I haven't been encountering issues with rogue streams in my tests so it should be safe to remove.
- Remove ref tracking the mounted-state of the hook
=> (react) - Support fast-refresh

exchanges/auth/README.md
Just fixing some typos.
As for `errorExchange` change, typescript throws type error, so I presume that it should be changed too:
=> Fix some typos in auth exchange readme

docs/graphcache/custom-updates.md, docs/graphcache/normalized-caching.md
Resolves: https://github.com/FormidableLabs/urql/issues/938
It clarifies some frequent misunderstandings within the graphCache documentation.
=> (docs) - elaborate on graphcache documentation

docs/graphcache/schema-awareness.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/operations/query.test.ts, exchanges/graphcache/src/operations/write.test.ts, exchanges/graphcache/src/store/store.test.ts, packages/introspection/CHANGELOG.md, packages/introspection/README.md, packages/introspection/package.json, packages/introspection/src/getIntrospectedSchema.ts, packages/introspection/src/index.ts, packages/introspection/src/minifyIntrospectionQuery.ts, packages/introspection/tsconfig.json
Related #974
The new `@urql/introspection` utilities aim to contain all kinds of functions that may be used to treat client-side GraphQL schemas, currently: to minify them. This may be used to minify an `IntrospectionQuery` to get it down to a minimum possible size.
This has been tested against the GitHub GraphQL API schema and it brings it down from `49.4kB` minzipped to `29.6kB` minzipped. The uncompressed sizes are `1.1MB` and `551KB`.
We've determined that it's _not_ effective to translate the GraphQL Introspection Query to a schema string and turning that back to a `GraphQLSchema`. The reduction is about a third of size, but this does pull in about 15-20KB more from `graphql`. Since we're dealing with a worst-case scenario sized schema here, this doesn't seem worth it, since that …
=> (introspection) - Implement initial @urql/introspection package

README.md
Just noticed the CircleCI badge wasn't showing up, because it was still pointing to the `master` branch, which we no longer have.
=> (chore) - fix circleci badge

.circleci/config.yml
Skips the install step if a cache for the current lockfile exists
[First run](https://app.circleci.com/pipelines/github/FormidableLabs/urql/1972/workflows/5c23d493-bc3a-4981-b76b-96ca01d2a7e1/jobs/7443)
[Cache hit](https://app.circleci.com/pipelines/github/FormidableLabs/urql/1972/workflows/f37c0819-38ac-45d1-809b-61867bdc2799/jobs/7447)
---
Heads up - I haven't looked too deeply into how this affects imports with yarn workspaces. Might need some tweaks
=> Update CircleCI to skip install on cache hit

.changeset/pretty-pans-doubt.md, docs/graphcache/offline.md, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/helpers/operation.ts, exchanges/graphcache/src/offlineExchange.test.ts, exchanges/graphcache/src/offlineExchange.ts
Previously when the user was offline and the cache would fail with a complete cache miss for offline queries then no result would be delivered to the client and instead would fetch infinitely. Instead the `offlineExchange` now retries with `cac he-only`.
=> (graphcache) - Fix offline queries not delivering any results on cache-miss and offline

.changeset/fuzzy-peas-shop.md, exchanges/graphcache/src/ast/schemaPredicates.ts, exchanges/graphcache/src/ast/traversal.ts, package.json, packages/next-urql/src/with-urql-client.tsx, packages/preact-urql/src/hooks/useMutation.ts, packages/react-urql/src/hooks/useMutation.ts, scripts/eslint/common.js, scripts/eslint/js-preset.js, scripts/eslint/preset.js, yarn.lock
This adds some ESLint refactors and the `eslint-plugin-es5` rules to ensure that we continue to support polyfill-less ES5 support. The exception here are of course `Map`, `Set`, `WeakSet`, and `WeakMap` which React also requires to be polyfilled but overall these are very non-intrusive polyfills.
There were some cases where we used some stuff that we probably shouldn't have used but I did fix them up. Overall it seems like we kept our self-imposed rule in check quite well and there were only two files where we slipped up.
Just as a clarification. We've always aimed to not include any polyfills for static methods or methods that were added in ES6+, which also keeps our bundle size low. We've seen this as a minor overhead to our work and it doesn't have a huge impact on how we write our …
=> (chore) - Add ES5 linting and ensure polyfill-less ES5 support

.changeset/great-dragons-study.md, packages/next-urql/README.md, packages/next-urql/src/index.ts
Expose `initUrqlClient` function in order to allow fetching data in SSR mode. Without it data can be fetched only in client-side rendered apps and in static pages.
__Notes:__ The GraphQL server doesn't work, I had to use different ones in order to test the functionality. I kept the old Pokemon endpoints for consistency.
=> (next-urql) Expose initUrqlClient function for manual usage in Next’s getServerSideProps methods

CONTRIBUTING.md
- whilst submitting my first PR (# 999), i noticed that the CONTRIBUTING doc referenced `master`, but it seems that `main` is the primary branch now.
- :memo: changes `master` to `main` in the CONTRIBUTING doc
- :x: not a breaking change
=> change branch reference to 'main'

docs/graphcache/normalized-caching.md
- :bug: There was a typo (missing word) in the "normalized caching" docs
- :memo: Add aforementioned missing word
- :heavy_check_mark: Not a breaking change (just docs)
=> Fix typo in normalized caching docs

exchanges/populate/src/helpers/node.ts, exchanges/populate/src/helpers/traverse.ts, exchanges/populate/src/populateExchange.ts
Removes the need for `graphql Typeinfo` & `visitWithTypeInfo` in the populate exchange
=> (populate) - refactor and remove the need for visit & typeinfo

.changeset/thin-cows-hug.md, exchanges/populate/src/helpers/help.ts, exchanges/populate/src/helpers/node.ts, exchanges/populate/src/helpers/traverse.ts, exchanges/populate/src/populateExchange.test.ts, exchanges/populate/src/populateExchange.ts
Fixes https://github.com/FormidableLabs/urql/issues/909
Adds support for nested complex types
=> (populate) - support (nested) interfaces & unions in the return type

exchanges/request-policy/package.json, exchanges/retry/package.json, packages/storybook-addon/tsconfig.json
This previously made CodeSandbox builds fail, I suspect.
Quick sanity check shows that `yarn tsc` (in package and in repo root) and `yarn build` still succeed locally.
=> (chore) - Update tsconfig.json in storybook-addon to match others

.changeset/strange-waves-confess.md, .changeset/tidy-bobcats-sniff.md, exchanges/graphcache/src/offlineExchange.test.ts, exchanges/graphcache/src/offlineExchange.ts, packages/core/src/client.ts
Test against: https://codesandbox.io/s/urql-crud-router-doesnt-update-forked-3nf19
This change updates when queries that have received an offline / network error are dispatched as `cache-only` operations again, and adds support for them being retried automatically (in case they're still active) when the client comes back online.
A small change has also been made to `@urql/core` to allow `client.reexecuteOperation` to be called with mutations.
=> (graphcache) - Fix offline queries not flowing through the entire cacheExchange

docs/api/README.md, docs/api/refocus-exchange.md, docs/concepts/exchanges.md, exchanges/refocus/CHANGELOG.md, exchanges/refocus/README.md, exchanges/refocus/package.json, exchanges/refocus/src/index.ts, exchanges/refocus/src/refocusExchange.test.ts, exchanges/refocus/src/refocusExchange.ts, exchanges/refocus/tsconfig.json
This exchange is meant to avoid stale queries, everytime the window reenters focus the currently active queries will be refetched with a `cache-and-network` policy.
TODO:
- tests
- docs
=> (exchanges) - implement the focusExchange

docs/concepts/exchanges.md
Simple fix for a typo on the docs.
Changed "occursz" to "occurs".
Not a breaking change at all.
=> Fix docs typo

.changeset/shy-lemons-hug.md, .changeset/weak-seas-reflect.md, docs/advanced/server-side-rendering.md, packages/next-urql/README.md, packages/next-urql/package.json, packages/next-urql/src/init-urql-client.ts, yarn.lock
Having `urql` as a dependency seemed to confuse some package managers about what version of `@urql/core` to take and would often result in duplicates.
Removes the `fetch` polyfill since Next handles this [as of 9.4](https://nextjs.org/blog/next-9-4#improved-built-in-fetch-support)
- Move `urql` to the peerDependencies (breaking)
- Remove `fetch` polyfill (breaking pre Next 9.4)
=> (next) - Move urql to peerDependencies and remove fetch polyfill

packages/site/src/components/mdx.js
On Windows I can see this:
I think it is better to use `auto`, see:
=> Fix Windows overflow-x style

.changeset/honest-turkeys-begin.md, packages/svelte-urql/src/operationStore.test.ts, packages/svelte-urql/src/operationStore.ts, packages/svelte-urql/src/operations.ts
Fix for `stale` remaining `true`, with a `cache-and-network` query.
Fixes: https://github.com/FormidableLabs/urql/issues/1031
- Adds `stale` Boolean cast to the query result since `stale` isn't  always present on the `OperationResult`, this indicates a false value.
=> (svelte) - cache & network query should reset stale to false

.changeset/small-worms-bake.md, exchanges/graphcache/src/ast/node.ts, exchanges/graphcache/src/ast/schemaPredicates.test.ts, exchanges/graphcache/src/ast/schemaPredicates.ts, exchanges/graphcache/src/operations/shared.ts, exchanges/graphcache/src/test-utils/suite.test.ts
Fix #1039
- Add test suite case for conditionless inline fragment
- Fix `isFragmentHeuristicallyMatching`
- Fix `isInterfaceOfType`
- Use `node` in `isInterfaceOfType` for consistency
- Update tests in `schemaPredicates.test.ts`
- Add test suite case for directives (while I'm at it)
=> (graphcache) - Fix handling of conditionless inline fragment

docs/advanced/debugging.md, docs/api/README.md, docs/api/core.md, docs/api/graphcache.md, docs/api/svelte.md, docs/api/urql.md, docs/comparison.md, packages/site/src/components/mdx.js, packages/site/src/styles/theme.js
This aims to add an unbiased and comprehensive comparison page that can be expanded in the future as we see fit. I'm trying to keep it accurate but I expect that it'll change as more questions arise or other libraries change. For now we only compare `urql` with Apollo and Relay and not other libraries like React Query or SWR as we only want to have direct comparisons with GraphQL clients... well, for just GraphQL. Otherwise the feature sets wouldn't make much sense.
=> (docs) - Add Comparison page

.changeset/lovely-gorillas-change.md, .changeset/yellow-toes-decide.md, docs/basics/queries.md, packages/svelte-urql/example/src/App.svelte, packages/svelte-urql/src/operationStore.test.ts, packages/svelte-urql/src/operationStore.ts, packages/svelte-urql/src/operations.test.ts, packages/svelte-urql/src/operations.ts
- Add support for `context.pause` to restore functionality like other bindings' to pause executing
- Fix an edge case where Svelte wouldn't correctly update the store, which lead to a faulty error (Fix #1036)
- Update `context` comparison code to deeply compare context changes (because Svelte lacks primitives for easy memoisation)
=> (svelte) - Add pause support and fix update edge case

docs/comparison.md
In this PR I have added some of the libraries that I have implemented and currently supported:
* [relay-hooks](https://github.com/relay-tools/relay-hooks): hooks for Relay for both concurrent and legacy modes
* [react-relay-offline](https://github.com/morrys/react-relay-offline): it's a Relay extension for offline capabilities
* [relay-angular](https://github.com/morrys/react-relay-offline): Angular Bindings including offline capabilities
* [wora/apollo-offline](https://morrys.github.io/wora/docs/apollo-offline) is an Apollo extension for offline functionality
=> (docs) - Update Comparison page with relay-tools related projects

.changeset/fuzzy-flowers-accept.md, packages/svelte-urql/src/operationStore.ts
=> (svelte) - Remove use of void type unions which prevent optional chaining

.changeset/kind-radios-clean.md, exchanges/graphcache/src/ast/traversal.ts, exchanges/graphcache/src/index.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/shared.ts, exchanges/graphcache/src/operations/write.ts
These changes were initially started to remove obsolete exports from Graphcache. Previously we would expose some `data.ts` internals so they could be used externally, but since we forgot to expose `initDataState` those exports wouldn't be of much use anyway. So instead we can reduce our exports to a minimum just to satisfy our `benchmark`'s needs.
Also this made me search for some more bundlesize opportunities, and I found that a small `traversal` helper could be rewritten and the shared `SelectionIterator` could be optimised a little. This also gave us a small micro-benchmark performance bump, since it's a hotpath.
- Remove `noopDataState`, `writeOptimistic`, and `reserveLayer` from exports
- Rewrite `getFragments` utility in `ast/traversal.ts`
- Rewrite `makeSelectionIterator` to become …
=> (graphcache) - Refactor SelectionIterator and clean up exports

.changeset/ten-turkeys-appear.md, exchanges/graphcache/src/store/data.ts, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/test-utils/examples-1.test.ts
This was discovered in this Discussions thread: https://github.com/FormidableLabs/urql/discussions/1073
In #866 we previously disallowed optimistic updates to read other optimistically written data, which meant to prevent conflicts between these data layers that will later trickle down into permanent layers. This isn't a concern anymore because optimistic layers will never contribute to concrete, non-optimistic data and are thrown away, if they're for optimistic mutations.
The edge case we aimed to prevent is also not possible anymore because we now never apply concrete updates on top of optimistic ones since #750, namely:
> - Block refetching of operations that have active optimistic updates and keep track of them (see above)
> - Keep track of optimistic mutation that are pending at the …
=> (graphcache) - Reenable cumulative optimistic updates

.changeset/heavy-peaches-brush.md, .codesandbox/ci.json, exchanges/auth/src/authExchange.ts
See: https://github.com/FormidableLabs/urql/discussions/1070
Previously the `willAuthError` method would trigger the operation that triggered it twice. First for the active operation `mergeMap` function, and second for the `retryQueue` which is caused by `refreshAuth(operation)`.
=> (auth) - Fix duplicate operation on willAuthError

.changeset/gorgeous-queens-fetch.md, exchanges/graphcache/src/offlineExchange.ts, exchanges/graphcache/src/store/data.ts, exchanges/graphcache/src/test-utils/examples-1.test.ts
Fix #1079
> ~**NOTE:** This changes an earlier (but rare) case's behaviour!~
> ~We expect that this changes how a "toggling mutation" may look in the UI. Specifically it will never be able now to actually toggle if we trigger it repeatedly in optimistic updates. That's probably a good thing however as between a bad network connection and going offline/online we can't tell whether all toggling mutations will be delivered and applied in-order and atomically. So it's invalid to prioritise this case over the following fix.~
This fix clears all optimistic updates as a single batch by sending `'teardown'` operations in the `offlineExchange` when the mutations are ready to be retried. This uses the existing functionality that clears layers using `noopDataState` when a `teardown` operation comes …
=> (graphcache) - Clear optimistic updates before retrying in offlineExchange

.changeset/dirty-dragons-try.md, exchanges/refocus/src/refocusExchange.test.ts, exchanges/refocus/src/refocusExchange.ts
Resolves #1063 
Use the `visibilitychange` api.
* Switch from `focus` to `visibilitychange` api
I looked at [SWR](https://github.com/vercel/swr/blob/4d6be3df441f925d235a4b26914efcc85ae335a3/src/use-swr.ts#L61) and [react-query](https://github.com/tannerlinsley/react-query/blob/master/src/core/setFocusHandler.ts#L14) code and noticed that they refetch on both `focus` and `visibilitychange` events. As you can see in the video below, `visibilitychange` does not fire when we switch from one window to another (while `focus` does). It actually makes sense since the visibility of the document does not change. According to #1063, `focus` has some issues so I guess it's fine to only refetch on `visibilitychange`?
=> (refocus) - Switch to visibilitychange api

.changeset/thin-rings-tell.md, package.json, packages/preact-urql/src/hooks/index.ts, scripts/rollup/cleanup-plugin.js, scripts/rollup/config.js, scripts/rollup/plugins.js, yarn.lock
Resolve #1086 
Another week another small ESM issue in Webpack 5. In the upgrade Webpack now supports `package.json:exports` maps. However, a small problem with this support is how it handles sub-packages without a `package.json:exports`. There's a small quirk in Webpack that will require all import paths to be exact (including extensions) even when the sub-package doesn't have a `package.json:exports` map.
We're affected by this because we use our `babel-plugin-modular-graphql` plugin to convert some `graphql` imports into more specific ones. But instead of specifying files like `graphql/language/visitor` we need to add the full path like `graphql/language/visitor.mjs`. While I'm not convinced that this is the correct behaviour, it's an easy fix.
- Upgrade to …
=> (build) - Fix graphql imports for Webpack 5

.changeset/tough-dryers-perform.md, packages/next-urql/package.json, packages/next-urql/src/types.ts, packages/next-urql/src/with-urql-client.tsx, yarn.lock
This removes the dev-dependency on `next` from `next-urql` by providing vague types around what the `NextContext` and component types look like. It's provided so that the enhancer function still assumes and infers the correct type if possible.
This is to reduce the dependencies in our monorepo and it's been tested against the first example in the `next-urql` folder, which passes a `tsc` run successfully even with the new package.
=> (next) - Remove explicit dependency on next for next-urql's types

.changeset/wet-onions-burn.md, exchanges/graphcache/default-storage/package.json, scripts/rollup/config.js
Fix the production build overwriting the development build. Specifically in the previous release we mistakenly replaced all development bundles with production bundles. This doesn't have any direct influence on how these packages work, but prevented development warnings from being logged or full errors from being thrown.
=> (chore) - Fix development build being overwritten by production build

.changeset/gorgeous-radios-dream.md, packages/core/src/client.ts, packages/preact-urql/src/hooks/useQuery.ts, packages/preact-urql/src/hooks/useSource.ts, packages/preact-urql/src/hooks/useSubscription.ts, packages/react-urql/src/hooks/useQuery.ts, packages/react-urql/src/hooks/useSource.ts, packages/react-urql/src/hooks/useSubscription.ts
The motivation of this change is to simplify the `useSource` and `useBehaviourSubject` implementations and to remove various additional edge cases from the implementation, like shallow equal updates. In theory it'd be best to also figure out a way to carry over the subscription from the mount phase to the effect phase, which we attempted before but which very deliberately is impossible in React.
This will not change the behaviour of these hooks dramatically but avoid unnecessary state updates when any updates are obviously equivalent and the hook will furthermore improve continuation from mount to effects, which will fix cases where the state between the mounting and effect phase may slightly change.
- Combine `useSource` and `useBehaviourSubject` into just `useSource`
- Prevent …
=> (core) - Refactor useSource and improve hooks edge case behaviour

.changeset/fifty-fans-dream.md, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/types.ts, packages/core/package.json, packages/core/src/client.ts, packages/core/src/index.ts, packages/core/src/types.ts, packages/core/src/utils/operation.ts, packages/core/src/utils/request.ts, packages/core/src/utils/typenames.ts, packages/preact-urql/src/components/Mutation.ts, packages/preact-urql/src/components/Query.ts, packages/preact-urql/src/components/Subscription.ts, packages/preact-urql/src/hooks/useMutation.ts, packages/preact-urql/src/hooks/useQuery.ts, packages/preact-urql/src/hooks/useRequest.ts, packages/preact-urql/src/hooks/useSubscription.ts, packages/react-urql/src/components/Mutation.ts, packages/react-urql/src/components/Query.ts, packages/react-urql/src/components/Subscription.ts, packages/react-urql/src/hooks/useMutation.ts, packages/react-urql/src/hooks/useQuery.ts, packages/react-urql/src/hooks/useRequest.ts, packages/react-urql/src/hooks/useSubscription.ts, packages/svelte-urql/src/operationStore.ts, packages/svelte-urql/src/operations.ts, yarn.lock
Resolve https://github.com/dotansimha/graphql-typed-document-node/issues/36
This comprehensively adds `Data` and `Variables` generics with untyped fallbacks to all of our results and operations, containing either `DocumentNode` or variables.
It uses the `TypedDocumentNode` type from `@graphql-typed-document-node/core` which is just a stand-in for generated types for a given GraphQL document. So other tooling can step in and fill this out. The advantage of using it throughout is that all of our APIs will be able to accept a `TypedDocumentNode` which then subsequently makes their results typed as well, similar to `graphql_ppx` and `reason-urql`.
- Reexport `TypedDocumentNode` from `@urql/core` (It's technically a core type and that limits where the dependency is installed)
- Add …
=> (core) - Add support for TypedDocumentNode

.changeset/gentle-grapes-love.md, exchanges/retry/src/retryExchange.test.ts, exchanges/retry/src/retryExchange.ts
Resolve #1116 
Suppose there's a `error.graphqlErrors` error and that triggers a retry. This type of error won't have broken the operation pipe for subscriptions, so retrying will start an identical operation in that case for subscriptions, depending on the transport protocol and method that's used.
We could also consider adding a small dedup predicate to `subscriptionExchange` but for now we should allow the `retryExchange` to be configured to ignore certain cases per operation kind.
- Add `operation: Operation` argument to `retryIf` predicate
=> (retry) - Add operation argument to retryIf predicate

docs/advanced/subscriptions.md
👋, I'd like to introduce a subscriptions transport alternative [`graphql-ws`](https://github.com/enisdenjo/graphql-ws).
=> (docs) - add `graphql-ws` as a subscriptions client

.changeset/breezy-ghosts-sin.md, packages/core/src/exchanges/subscription.ts
As suggested by TS and recommended ESLint rules - don't use `object` as a type. The `object` type is currently hard to use ([see this issue](https://github.com/microsoft/TypeScript/issues/21732)).
This also solves the type compatibility for `graphql-ws` where you can use the lib in TS as you would in plain ol' JS like in #1118.
Previously, because of this `object` type, you have to do this:
```ts
...
subscriptionExchange({
forwardSubscription({ query, variables }) {
return {
subscribe: (sink) => {
const dispose = wsClient.subscribe(
{
query,
variables: variables as Record<string, unknown>, // 😞
},
sink,
);
return {
unsubscribe: dispose,
};
},
};
},
}),
...
```
=> (fix) - use Record over object type for subscription operation variables

.github/CODEOWNERS, .github/workflows/release.yml
This automates our release process, we're already using changesets but what changed?
- Every merged PR will make a PR from changesets that increments all versions (`yarn changeset version`) and updates changelogs
- When we merge it it will release all the packages to the NPM-registry
TODO: add npm-token to this repo's secrets
=> (chore) - Create GH Action for automated releases

docs/api/core.md
This PR just fixes a few incorrect types in the docs and explicitly documents the `Client.readQuery` method. I noticed these were off when working on revised `reason-urql` docs and figured I'd contribute the fix in while I was at it!
- Fix types on `additionalTypenames` and `preferGetMethod`.
- Document `Client.readQuery` method.
=> (docs) - Fix types on Client  properties and document Client.readQuery.

CONTRIBUTING.md
This basically adds:
- How our issues work, especially regarding the RFC process
- How PRs are written with respect to changesets and titles
- How the automated releases work
It also removes some duplicate sections and revises some other things I've found
=> (docs) - Update CONTRIBUTING guide with new information

.changeset/popular-bananas-camp.md, exchanges/execute/src/execute.test.ts, exchanges/execute/src/execute.ts, packages/core/src/index.ts
Fixes: https://github.com/FormidableLabs/urql/issues/1134
- Add getOperationName export to core
- Import getOperationName from core in the execute-exchange
=> (execute) - Fix imports and reuse getOperationName from core

.changeset/cool-news-buy.md, packages/preact-urql/src/hooks/useQuery.ts, packages/react-urql/src/hooks/useQuery.ts
When using `Suspense` on ssr-runs/interrupted runs effects won't be run, also when subsequent prepasses happen we can't be caching
Fixes https://github.com/FormidableLabs/urql/discussions/1136
- Don't cache suspenseful operations during ssr on Preact and React
=> (react/preact) - Fix suspense-ssr runs

.changeset/thin-years-scream.md, packages/storybook-addon/package.json
Given the choice to statically import devtools, we need to ensure it exists.
=> (storybook) - Add missing dependency on @urql/devtools

.changeset/eighty-rivers-sniff.md, packages/preact-urql/src/hooks/useQuery.ts, packages/react-urql/src/hooks/useQuery.ts
This regressed in the last patch, the version before that explicitly fixing it. This patch was aimed at server-side rendering but cleared the local suspense cache too early.
- Ensure that caching is still disabled on the server-side
- Clear suspense cache in effect rather than render loop
=> (react/preact) - Fix client-side Suspense loop regression

.changeset/odd-starfishes-punch.md, packages/vue-urql/src/index.ts, packages/vue-urql/src/useClient.ts
In the Vue ecosystem, library bindings like this one commonly provide an install function to add global configuration -  such as providing the client - through the global `app.use()`plugin API. This install function is usually the default export of the package.
This PR adds such an install function
- Adds an `install` function which allows the user to install and urql client as a plugin.
- exports this function as the default export.
This should be a minor change and doesn't break existing behavior or APIs, so a matching changeset is included.
=> (vue-urql) - Add plugin install function

.changeset/flat-rats-fetch.md, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts
Fixes a bug introduced in #1151, which broke `pause()`/resume()` functionality of `useQuery()`
I'm sorry about this - in #1151 I turned `isPaused` into a computed ref, which makes it read-only as it's a derived value.
This PR turns it into a writeable `ref()` again.
It doesn't contain any breaking changes, just a fix for a patch release.
=> (vue-urql) - Fix pausing behavior

packages/vue-urql/src/useMutation.test.ts, packages/vue-urql/src/useQuery.test.ts, packages/vue-urql/src/useSubscription.test.ts, packages/vue-urql/tsconfig.json
This PR adds tests for:
- `useMutation`
- `useQuery`
- `useSubscription`
- The added tests cover the same cases as the svelte implementation.
- I had to add `jest` to the package's tsconfig type option in order to stop TS from complaining, this should not have any impact outside of the vue-urql package.
- This is a draft PR for now as I came across some problems to test `useQuery().then()` behavior, and I'm not certain what the desired behavior here should be. Please see the code comments 
This only adds tests, so I didn't create a changeset. I can provide one if that's still required for this kind of PR.
=> (vue-urql) - Add Tests

.changeset/nasty-kids-bake.md, packages/react-urql/src/hooks/useSource.ts
Fix #1150 
We encountered another edge-case in client-side React Suspense, which is caused by React handling suspense-on-updates differently than suspense-on-mount. We basically have to be more sensible with state on suspense-on-update because React doesn't clear any state when we suspend during an update.
This can be tested against this reproduction sandbox: https://codesandbox.io/s/ecstatic-ritchie-lzxvl (See CodeSandbox CI output)
- Use the latest known `input` in `useSource` when subscribing
=> (react) - Fix client-side Suspense update edge-case

.changeset/tasty-ravens-hide.md, packages/vue-urql/src/useQuery.test.ts, packages/vue-urql/src/useQuery.ts
This should fix the thenable in `useQuery`'s Vue Suspense implementation by making it more reactive.
cc @LinusBorg
=> (vue) - Fix Vue Suspense by making thenable reactive

.changeset/six-wolves-eat.md, packages/vue-urql/src/useQuery.test.ts, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts
This refactors `useQuery` to use `watchEffect` again (see earlier commits). It then goes further to ensure that the lazy promise will always look at the latest query that has been issued. It also ensures that this latest query is shared if it's ongoing and not if it's completed. A paused query will always immediately resolve the latest result.
This implementation is made a lot easier by the fact that we're resolving to the same `state` object every time. Since there's only one truth for the state, we don't need to ensure that the streams are transformed to usable `scan` state like in `react-urql`.
- Use a continuous subject to track the latest query stream
- Make all ref updates side-effects of these query streams as they're issued
- Write a `replayOne` operator to wrap the subject stream …
=> (vue) - Refactor lazy promise and watch effects

.changeset/curvy-terms-dress.md, docs/advanced/server-side-rendering.md, packages/core/src/exchanges/ssr.ts
This adds an example to our docs of using `getStaticProps`.
=> (next-urql) - add example of using the built-in data-fetching functions

.changeset/little-crabs-sell.md, docs/api/graphcache.md, docs/graphcache/computed-queries.md, exchanges/graphcache/src/extras/simplePagination.test.ts, exchanges/graphcache/src/extras/simplePagination.ts
Resolves #1173 
Adds `mergeMode` to `simplePagination` similar to that of `relayPagination`. Default to `inwards`, so it will not be a breaking change.
=> (graphcache) - Add mergeMode to simplePagination helper

.changeset/hungry-penguins-teach.md, packages/preact-urql/src/hooks/useQuery.ts, packages/react-urql/src/hooks/useQuery.ts
=> (react/preact) - Force suspense to be disabled for executeQuery calls

.changeset/smart-lizards-crash.md, docs/graphcache/errors.md, exchanges/graphcache/default-storage/package.json, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/extras/relayPagination.test.ts, exchanges/graphcache/src/extras/simplePagination.test.ts, exchanges/graphcache/src/helpers/help.ts, exchanges/graphcache/src/offlineExchange.test.ts, exchanges/graphcache/src/operations/query.test.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/shared.ts, exchanges/graphcache/src/operations/write.test.ts, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/store/__snapshots__/store.test.ts.snap, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/test-utils/examples-1.test.ts, exchanges/graphcache/src/test-utils/examples-2.test.ts, exchanges/graphcache/src/test-utils/examples-3.test.ts, exchanges/graphcache/src/test-utils/suite.test.ts
See #1184 
**Note:** More testing is needed before we can safely ship this.
Increase the consistency of when and how the `__typename` field is added to results. Instead of adding it by default and automatically first, the `__typename` field will now be added along with the usual selection set. The `write` operation will issue a warning if it's in the selection but missing in the result, as it should, and the `query` operation will add it as it did before but at the correct position of the result, assuming that it's in all selection sets. The slight change here is that it now won't be added to root results by default and only if it's being queried explicitly.
- Allow `makeSelectionIterator` to iterate `__typename` field
- Remove `data.__typename` assignment in `readSelection` and add …
=> (graphcache) - Increase consistency of __typename in cached results

.changeset/nice-rivers-run.md, .changeset/serious-gorillas-develop.md, packages/core/src/utils/request.ts, packages/core/src/utils/typenames.test.ts, packages/core/src/utils/typenames.ts
Fix an edge case in `formatDocument` for aliased fields and add in-memory caching to it via the document key.
- Add `keyDocument` for `formatDocument` to cache its result
- Add `alias` check to `formatDocument`'s visit function
- Code golf `collectTypesFromResponse` a little
=> (core) - Fix formatDocument edge case and add caching

.changeset/nervous-beds-battle.md, exchanges/graphcache/src/ast/buildClientSchema.ts, exchanges/graphcache/src/ast/index.ts, exchanges/graphcache/src/ast/schema.ts, exchanges/graphcache/src/ast/schemaPredicates.test.ts, exchanges/graphcache/src/ast/schemaPredicates.ts, exchanges/graphcache/src/store/store.ts, yarn.lock
Our largest impact on `@urql/exchange-graphcache` is our usage of `graphql/utilities/buildClientSchema` which uses `GraphQLSchema` and other heavy implementations, which are basically server-side implementations with a lot of invariants. Given that we know that with `@urql/introspection` and other introspection methods the result can be trusted we don't even need any of the strict validation of `buildClientSchema` and what it pulls in.
Furthmore, we don't need any of the `graphql/type/definition` types, e.g. `GraphQLObjectType` and helpers like `isObjectType` if we transform the client schema to a format that is just good enough for our purposes.
This change increases `@urql/exchange-graphcache`'s size slightly from `6.74kB gzip` to `6.93kB gzip`. However, the impact on what's pulled in …
=> (graphcache) - Replace buildClientSchema with lean implementation

.changeset/wise-rats-whisper.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/offlineExchange.test.ts, exchanges/graphcache/src/operations/query.test.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/write.ts
This was originally reported by @sarmeyer.
Tracking down what the root culprit and intended fix is was difficult since the effects of this bug were subtle, the cause was hard to find, and this can poorly by fixed by several small issues. Ultimately, tl;dr, the bug can be seen here: https://github.com/FormidableLabs/urql/blob/eee828914fb6083b2aaa3203484ed6b36b7beff5/exchanges/graphcache/src/operations/query.ts#L93-L97
Fix reusing original query data from APIs accidentally, which can lead to subtle mismatches in results when the API's incoming `query` results are being updated by the `cacheExchange`, to apply resolvers. Specifically this may lead to relations from being set back to `null` when the resolver returns a different list of links than the result, since some `null` relations may …
=> (graphcache) - Fix API results from being reused incorrectly for queries 

.changeset/ten-kangaroos-march.md, docs/api/graphcache.md, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/shared.ts, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/types.ts
Resolves #1207
This updates the shared context object to be provided on a global ref, which is then used in various cache methods, via `cache.keyOfEntity`, to alias the `parent` argument, which can be found on resolvers and updaters, to `info.parentKey`. This is done by adding (publicly) `info.parent`, which is the current parent's data as it is. (This avoids us having to share it on a separate object)
This further refactors `store.keyOfEntity` to take care of all key normalisation that has been done repeatedly in separate methods before, which further ensures that `cache[method](parent)` is going to work consistently as expected.
The reasoning here is that writing resolvers with `parent` as the first argument to further cache methods is so intuitive that we even did it ourselves in the …
=> (graphcache) - Alias resolvers/updates parent to its parentKey in cache methods

packages/next-urql/README.md
Fixes a mistake in the `next-urql` docs.
`NextUrqlClientConfig` now uses `PartialNextContext` instead of `NextPageContext`.
https://github.com/FormidableLabs/urql/blob/e723365575203ff242bc9867f6e43fb43fb2e51e/packages/next-urql/src/types.ts#L21-L23
=> (docs) - Fix outdated type in next-urql section

docs/graphcache/custom-updates.md
Contrary to a few lines up, in this closure `x` is already destructured
which means `arguments` exists, but `x.arguments` does not.
A small change makes sure the code works when copy pasted :)
=> (docs) - Fix error in cache.inspectFields code sample

.changeset/gentle-wasps-play.md, exchanges/execute/src/execute.test.ts, exchanges/multipart-fetch/src/__snapshots__/multipartFetchExchange.test.ts.snap, packages/core/src/exchanges/__snapshots__/fetch.test.ts.snap, packages/core/src/exchanges/__snapshots__/subscription.test.ts.snap, packages/core/src/gql.test.ts, packages/core/src/gql.ts, packages/core/src/internal/__snapshots__/fetchSource.test.ts.snap, packages/core/src/utils/request.ts
This change implements a missing feature of the `gql` tag. While it previously warned about fragments with duplicate names, it didn't check whether these fragments were identical and deduplicated them. This change implements fragment deduplication and solidifies some of our `DocumentNode#__key` and `ASTNode#loc` additions.
- Incrementally add an operation's definitions to a new `gql` document
- Add `ASTNode.loc` in `stringifyDocument`
- Switch `gql` to apply this behaviour to raw `DocumentNode` inputs only
=>  (core) - Add fragment deduping to gql tag 

docs/graphcache/schema-awareness.md
This changes the wording of `schema-awareness.md` to reflect what `minifyIntrospectionQuery` can take as an argument and that it's not a requirement to make schema-awarenss work, it is an optimization step.
Closes https://github.com/FormidableLabs/urql/issues/1228
=> (docs) - Change wording in schema-awareness to reflect intent of minify

exchanges/graphcache/src/ast/schemaPredicates.test.ts
Noticed we weren't testing against a minified schema in the `schemaPredicates` which seems like our biggest use case 😅
=> (graphcache) - minify the schema in the schema-predicates tests

.changeset/tiny-badgers-pretend.md, exchanges/graphcache/src/operations/invalidate.ts, exchanges/graphcache/src/store/store.ts
Fixes: https://github.com/FormidableLabs/urql/issues/1262
This PR adds `null`  as a possible type for the variables argument in `invalidate` and `keyOfField`.
- Add `null` as a type for `cache.invalidate` variables
=> (graphcache) - add null as a possible type for args in invalidate

.changeset/little-mice-shave.md, packages/preact-urql/src/hooks/useSource.ts, packages/react-urql/src/hooks/useSource.ts
Fix Suspense when results share data, this would return partial results for graphCache and not update to the eventual data
Fixes: https://github.com/FormidableLabs/urql/issues/1249 https://codesandbox.io/s/modest-chatterjee-s6c2g
- Always reset the `currentInit` for state initialization
=> (react/preact) - Suspense with child queries sharing data

packages/site/package.json, packages/site/src/components/navigation.js, packages/site/src/components/sidebar-search-input.js, packages/site/src/components/sidebar.js, packages/site/src/styles/theme.js, yarn.lock
Resolves #1064 
The reasoning behind this change is mostly explained in the above issue. 
We want to add the capability to search the docs for relevant content based on the page title or subheading(s).
- add `< SidebarSearchInput />`
- filter sidebar headings and subheadings based on input 
- while searching, include matching H3 headers in the sidebar
- highlight matching substrings by wrapping them in `<strong>`
- add `fuse.js` fuzzy-search dep
- increase the sidebar width
- Depending on how we like the current design we may want to relocate the search bar to the header, showing relevant matches in a dropdown as opposed to the sidebar
=> (docs) add a search input to the sidebar

.changeset/fast-fireants-drum.md, packages/next-urql/examples/1-with-urql-client/package.json, packages/next-urql/examples/1-with-urql-client/pages/index.tsx, packages/next-urql/examples/1-with-urql-client/tsconfig.json, packages/next-urql/examples/1-with-urql-client/yarn.lock, packages/next-urql/examples/2-with-_app.js/pages/_app.tsx, packages/next-urql/src/__tests__/with-urql-client.spec.ts, packages/next-urql/src/types.ts, packages/next-urql/src/with-urql-client.ts
Fixes: #1213
Integrate with the page/context types used when typing a page via `NextPage`. 
* set example 1 tsconfig to strict
* support `NextPage` and related `AppContext` types
* update example 1 to use `NextPage` type
* remove `// @ts-ignore` from example 2
=> (next-urql) integrate with Next page/content types

.changeset/silly-peaches-compete.md, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/store/data.ts
Resolve #1253 
In Graphcache, results from the API update the cache and are then re-queried to execute resolvers and apply optimistic updates. The latter is unlikely to take effect, since optimistic updates block queries. However the former is pretty important for consistency.
A race condition could be triggered by invalidating data or rewriting it in a mutation. A subsequent query result (where the query was triggered before the mutation result) would then read the new/rewritten data instead of its own as it just wrote it. Instead we'll want this re-queried data to always prioritise reading its own data over the mutation data, but still prioritise optimistic layers over its own.
This change adds an exception for re-queried API data to prioritise its own layer and read from it first, …
=> (graphcache) - Prefer updated layer in re-query

.changeset/large-ladybugs-burn.md, packages/next-urql/src/with-urql-client.ts
Fixes: https://github.com/FormidableLabs/urql/issues/1301
React-refresh babel requires components to start with an upper case letter to be incorporated in the signing flow.
- `withUrql` renamed to `WithUrql`
=> (next-urql) - Use uppercase for React components

.changeset/late-gifts-worry.md, docs/graphcache/errors.md, exchanges/graphcache/src/ast/schemaPredicates.ts, exchanges/graphcache/src/helpers/help.ts, exchanges/graphcache/src/store/store.test.ts
Resolves: https://github.com/FormidableLabs/urql/issues/1293
Warn the user when using an abstract type in the resolvers config.
- add dev-check to schema-predicates
- add documentation for said error
=> (graphCache) - warn when using an interface or union type in the resolvers

.changeset/strange-scissors-swim.md, exchanges/graphcache/src/extras/relayPagination.test.ts, exchanges/graphcache/src/extras/relayPagination.ts
Resolves https://github.com/FormidableLabs/urql/issues/1297
When we'd have two backwards overlapping pages the results would start mixing up.
- Reverse the backwards pagination node - edge concatenation
=> (graphcache) - Relay backwards pagination

.changeset/many-rats-buy.md, packages/react-urql/src/hooks/useQuery.ts, packages/react-urql/src/hooks/useSource.ts
Resolve #1303
Fix edge cases related to Suspense triggering on an update in Concurrent Mode. Previously it was possible for stale state to be preserved across the Suspense update instead of the new state showing up. This has been fixed by preventing the suspending query source from closing prematurely.
See CodeSandbox for reproduction / fix in action: https://codesandbox.io/s/optimistic-andras-f2j1q?file=/src/useQuery.ts
For some next steps it'd be interesting to explore ways to remove the `toSuspenseSource` cache in `useQuery` for another solution that's more in-line with per-client shortterm caches, e.g. https://github.com/FormidableLabs/urql/tree/refactor/shared-sources
- Don't close `toSuspenseSource` sources prematurely when throwing suspense promise
- Fix cached values in …
=> (react) - Fix Suspense-on-update giving stale results in Concurrent Mode

.changeset/clever-islands-do.md, packages/core/src/utils/request.ts
Resolve #1298 
For output from graphql-tag/loader we need to add a workaround
to request.ts which adds the operation name to the document's
string since `document.loc.source` isn't reliable and potentially
points to the original query document which may contain all
operations rather than just one.
- Add `getOperationName` to document strings in `request.ts` which are eventually used as hashes
=>  (core) - Fix graphql-tag/loader document.loc.source usage 

docs/advanced/subscriptions.md
Just tried using GraphQL Subscriptions with `subscriptions-transport-ws`. I can only get it to work when using `ws://`. No response whatsoever when using the `wss://` prefix. Not sure what is causing this because they should specify the same protocol, but I guess it would be a good change either way for consistency with other resources like the Apollo Docs.
Changed `wss://` to `ws://`
=> docs(subscriptions): change websocket protocol prefix

.changeset/orange-maps-raise.md, packages/introspection/src/minifyIntrospectionQuery.ts
This removes more superfluous information from the minified schema introspection JSON data that `minifyIntrospectionQuery` generates. This has been checked to still be correctly parsed by `buildClientSchema`.
- Remove metatypes from schema (See https://github.com/FormidableLabs/urql/commit/eb7abebe6ecb6ca9c907bfb475f8918cb2e94669)
- Remove additional JSON fields from arguments
=> (introspection) - Improve schema minification by removing meta types

.changeset/smart-emus-jam.md, docs/api/graphcache.md, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/shared.ts, exchanges/graphcache/src/operations/write.test.ts, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/types.ts
Resolve #1344
This change attempts to improve Graphcache's error handling and error awareness. Instead of ignoring the added information that `GraphQLError#path` may provide for individual null'ed out fields, Graphcache now processes these errors and dynamically replaces `null` values (links and records) as it writes them with `undefined` — i.e. uncached / cache misses — when an associated `GraphQLError` has been received for a given field.
- Add `Context.__internal.path` tracking the current data path via aliases and indices
- Add `Context.__internal.errorMap` tracking the current `CombinedError`'s `GraphQLError`s by their paths
- Add `Context.error` which shows an updater its current field's error if any exists
- Replace `fieldValue` in `write` with `undefined` rather than `null` if the …
=> (graphcache) - Handle fields with associated GraphQLError as cache misses and provide errors to updaters

exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/operations/query.ts
This is a follow-up for #1356
The #1356 change introduced behaviour that prevents `null` values from fields that have errored and are associated with `GraphQLError` from being cached. This caused a regression where when we "read-back" results from the cache that have just arrived from the API these fields would cause a cache miss:
https://github.com/FormidableLabs/urql/blob/6a687091b67dc3d0ee78353ca79b0aa401ba983c/exchanges/graphcache/src/cacheExchange.ts#L237-L243
We can prevent this by also tracking errored fields in the `query` and ignoring these uncached fields there too by replacing them with `null` while we still have access to the `GraphQLError`s.
This is preferable to other solutions as we've gotten rid of comparing the cached result to the API result in #1196 as we had trouble …
=> (graphcache) - Fix uncached GraphQLError fields making it impossible to get first API result

.changeset/gorgeous-squids-exercise.md, .changeset/great-rice-lick.md, .changeset/twelve-camels-sit.md, docs/api/core.md, docs/api/urql.md, docs/api/vue.md, packages/core/src/client.test.ts, packages/core/src/client.ts, packages/core/src/types.ts, packages/preact-urql/src/hooks/useQuery.ts, packages/react-urql/src/hooks/useQuery.ts, packages/vue-urql/src/useQuery.test.ts, packages/vue-urql/src/useQuery.ts
Resolves #531
This PR removes the `pollInterval` option from `@urql/core` and all bindings. Generally it isn't hard to replace `pollInterval` in user-land with even more correct behaviour, as it can ultimately read the results of the bindings and react to those accordingly.
This just demonstrates that it's rather simple to replace the implementation in React-land.
```js
const [result, executeQuery] = useQuery(...);
useEffect(() => {
if (!result.fetching) {
const id = setTimeout(() => executeQuery({ requestPolicy: 'network-only' }), 5000);
return () => clearTimeout(id);
}
}, [result.fetching, executeQuery]);
```
**NOTE re #531**: It's worth noting that this PR doesn't resolve the issue explicitly, however we see it as much easier to implement effects in user-land that call `executeQuery` …
=> (breaking) - Remove pollInterval option from urql

.changeset/strong-emus-confess.md, packages/core/src/client.test.ts, packages/core/src/client.ts
Resolve #1372 
Usually we have a couple of refetches that are emitted as `cache-and-network`. In these cases the cache exchanges (default or Graphcache) take care of emitting a first result with the `stale` flag set. In other cases we may have a subsequent `network-only` reexecution which happens in the background. In these cases no part of the exchange pipeline or the `Client` took responsibility of emitting a `stale` result.
This PR changes this behaviour to allows the `Client`'s `executeRequestOperation` stream to add-on a single `stale` result onto a prior result if it detects a `network-only` operation.
- Has been tested in `threed-web` against Graphcache's `cache.invalidate` which triggers a `network-only` refetch.
- This has also been fixed in 5c1b1fd to be applied to all …
=> (core) - Reemit results as stale if they're refetched in the background

.changeset/small-apricots-exercise.md, exchanges/request-policy/src/requestPolicyExchange.ts
Fix #1334
Fix the exchange upgrading non-query operations and setting a last-occurence time by operations rather than results.
=> (request-policy) - Fix conditions and time of upgrading operations

.changeset/blue-bees-join.md, exchanges/graphcache/src/ast/schema.ts, exchanges/graphcache/src/ast/schemaPredicates.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/offlineExchange.ts, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/store/store.ts
Resolve #1378
I had some of these changes done in a forgotten branch but never proposed / opened this since we didn't have a corresponding RFC just yet, and I didn't have time to write it up.
Basically, we should allow the root names to be altered without enabling full schema awareness for exceptional cases where schema awareness is explicitly not wanted. This is rather rare with the advent of GraphQL Code Generator's built-in plugin to resolve this at build time / deploy time but it may be helpful still.
It's now possible to pass only the root names like so:
```js
const introspection = {
__schema: {
queryType: {
name: 'query_root',
},
mutationType: {
name: 'mutation_root',
},
subscriptionType: {
name: 'subscription_root',
},
},
};
cacheExchange({ schema: introspection });
```
- Make …
=> (graphcache) - Allow partial schema to be passed for altered root names

docs/graphcache/cache-updates.md, packages/site/static.config.js
As it was discussed here https://github.com/FormidableLabs/urql/pull/1283
=> docs: renamed 'custom updates' to 'cache updates'

.changeset/silly-walls-cover.md, packages/react-urql/src/hooks/useQuery.ts
Fixes https://github.com/FormidableLabs/urql/issues/1382
- Shields for `useQuery` updating during the update of another component.
=> (react) - shield for cross-component updates

.changeset/eleven-poems-juggle.md, packages/react-urql/src/hooks/useSubscription.ts
We have an issue when the handler is an inline function, this will result in an endless loop due to the callbacks never being equal.
- Removes endless loop for `useSubscription`
=> (react) - move subscription handler to a ref to avoid infinite loops

docs/api/graphcache.md, docs/graphcache/README.md, docs/graphcache/cache-updates.md, docs/graphcache/local-resolvers.md, docs/graphcache/normalized-caching.md, packages/site/static.config.js
Resolve #1362
This is a compelte overhaul and basically a rewrite of the "Local Resolvers" (prev. known as "Computed Queries") and "Cache Updates" pages. The goal is to categorise all APIs and supported use-cases by actual examples rather than by API surfaces, since the latter is covered by the API docs.
**Preview Link:** https://formidable-com-urql-staging-1412.surge.sh
=> (docs) - Overhaul "Local Resolvers" & "Cache Updates" Graphcache docs pages

docs/architecture.md, packages/site/package.json, packages/site/plugins/preact/node.api.js, packages/site/plugins/react-router/browser.api.js, packages/site/src/components/mdx.js, packages/site/src/components/sidebar.js, packages/site/src/google-analytics.js, packages/site/src/screens/docs/article.js, packages/site/static.config.js, yarn.lock
- Fix react-router plugin not outputting correct base path for static export
- Replace relative routes with absolute ones for MDX output (md-plugin@0.3.0)
- Replace sidebar links with absolute ones
- Fix basepath for Google Analytics component as per Victory docs
- Fix basepath across site
- Downgrade react-static to fix static export (otherwise HTML output is empty)
This took a while to figure out as the behaviour and exports is just very
messed up. The downgrade is needed, otherwise no static HTML will be exported.
=> (chore) - Fix react-static docs pages build

.changeset/afraid-lamps-provide.md, exchanges/refocus/src/refocusExchange.ts
Fixes: https://github.com/FormidableLabs/urql/issues/1416
In a node environment do nothing in the refocus-exchange.
- In a node environment do nothing in the refocus-exchange.
=> (refocus) - only use the refocus-exchange in a browser env

.changeset/kind-cooks-invite.md, packages/preact-urql/src/context.ts, packages/react-urql/src/context.ts
Resolves https://github.com/FormidableLabs/urql/issues/1398
Adds a displayName for the DevTools
- add displayName property
=> (react/preact) - add displayName to the context provider

.changeset/fast-glasses-grin.md, packages/svelte-urql/src/operations.ts
resolves #1472 
Allow for making requests without `variables` and a `string` query argument. This is already allowed in our `operationStore` typings https://github.com/FormidableLabs/urql/blob/main/packages/svelte-urql/src/operationStore.ts#L34
- Allow for making requests without `variables` and a `string` query argument.
=> (svelte) - make the mutation request argument less strict

README.md
Getting a 404 on that link and this looks like a good alternative. 
I am just exploring the project for the first time and am guessing that the getting started guide used to be one link and is now divided by framework. It might make sense to change 'contains' or other copy around this, too.
=> Update README.md to fix Getting Started link

.changeset/large-parents-talk.md, packages/next-urql/src/with-urql-client.ts
Resolves https://github.com/FormidableLabs/urql/issues/1481
When we're not using `getInitialProps`, the one from `withUrqlClient` and opt to use static-prerendering we still have to hydrate the cache.
Examples: 
- [getStaticProps](https://codesandbox.io/s/urql-get-static-props-dmjch?file=/pages/index.js)
- [getServerSideProps](https://codesandbox.io/s/urql-get-static-props-forked-xfbrs?file=/pages/index.js)
- [getInitialProps](https://codesandbox.io/s/urql-get-static-props-forked-y1cv7?file=/package.json)
Might need to start the [GraphQL endpoint](https://codesandbox.io/s/urql-issue-template-server-0ufyz?file=/index.js) to try them
- use `pageProps` to hydrate the cache when possible
=> (next) - hydrate cache correctly when using getStaticProps

.changeset/fair-beds-happen.md, exchanges/multipart-fetch/src/__snapshots__/multipartFetchExchange.test.ts.snap, packages/core/src/exchanges/__snapshots__/fetch.test.ts.snap, packages/core/src/exchanges/__snapshots__/subscription.test.ts.snap, packages/core/src/internal/__snapshots__/fetchSource.test.ts.snap, packages/core/src/utils/request.ts
Fixes #1508
This makes DocumentNode serialization idempotent.
In other words, this makes it so we get the same serial representation (and therefore hash key) for a DocumentNode each time it is computed.
=> (core) - Make DocumentNode serialization idempotent

docs/graphcache/cache-updates.md
A possibly accidental bullet point in the docs seem to affect the readability.
It's a pretty minor inconvenience but I decided to make a PR anyways :) 
Remove the bullet point.
=> (docs) - Remove accidental bullet point

docs/graphcache/cache-updates.md
Read Query link in the docs has an incomplete markdown syntax.
=> (docs) - Fix broken link

.changeset/slow-doors-sparkle.md, exchanges/graphcache/src/ast/schema.ts
Resolves https://github.com/FormidableLabs/urql/issues/1506
- allow null for subscription- & mutationType in the introspectionSchema
=> (graphcache) - allow null for subscription- & mutationType

docs/basics/README.md
the core package link file name is `core.md`, not `core-package.md`.
Update the broken link
=> Update core package link

docs/advanced/server-side-rendering.md
Adds in a missing import and dependency to Next.js examples, improving the 'get started' experience
- Adds `graphql` to dependency list for Next.js (app errors without this)
- Adds `useQuery` import from `urql` to Next.js example
=> (docs) - missing import/dependency in Next.js example

.changeset/great-scissors-boil.md, exchanges/graphcache/src/operations/query.ts
list-items are never nullable when we aren't using schema-awareness, this would otherwise lead to scenario's where we don't refetch partial results
Fixes: https://github.com/FormidableLabs/urql/issues/1546
Formerly we made the assumption that a list-item was nullable when we weren't provided with a schema, this meant that if we'd provide `[undefined, 'entity:x']` from a resolver we wouldn't fetch the result but we'd return it.
- Lists are non-nullable without schema-awareness
=> (graphcache) - make list items non-nullable without schema-awareness

docs/basics/svelte.md
When using either this or other GraphQL clients together with Vite it's common to encounter this error:
```
Uncaught Error: Function called outside component initialization
at get_current_component (index.mjs:649)
at setContext (index.mjs:679)
at setClient (context.ts:11)
```
The fix is simple, as seen in the changes, but in spite of that there exist very few resources that provide a concrete solution to it. Many threads are open on both StackOverflow and Github on this issue, so I believe specifying the solution in the docs will help a lot of developers in the long run.
=> (docs) Add Vite-specific installation instructions

docs/advanced/retry-operations.md
In the docs, the existing retryIf condition could fail if error is not defined. That's why I wanted to check error is defined before checking for graphQLErrors or networkError
=> (docs) Improve retryIf function in example

.changeset/lovely-hounds-tap.md, packages/introspection/src/minifyIntrospectionQuery.ts
Resolve: #1577
Some other tools may want to use the schema for other purposes, which has the prerequisite of more information having to be included in the schema; namely, the `customScalarsExchange` (a third-party one) requires scalar information to map any kind of scalar values in a result.
It's also imagineable that other information is needed so this PR adds options to now allow the inclusion of all schema information separately, which is still excluded by default.
=> (introspection) - Add options to include more schema info to minifyIntrospectionQuery

.changeset/curvy-bobcats-fry.md, exchanges/graphcache/default-storage/package.json, package.json, scripts/babel/transform-function-expressions.js, scripts/rollup/config.js, scripts/rollup/plugins.js, yarn.lock
Fixes: https://github.com/FormidableLabs/urql/issues/1552
The current rollup plugin isn't really maintained and we were seeing frequent issues with metro and bundles compiled by closure
- remove `rollup-plugin-closure-compiler`
=> (chore) - remove closure-compiler

packages/core/src/__snapshots__/client.test.ts.snap, packages/core/src/client.test.ts, packages/core/src/client.ts, packages/core/src/utils/index.ts, packages/core/src/utils/streamUtils.ts, packages/core/src/utils/withPromise.ts
At the risk of being called edgy, this proposed change layers a third cache on top of the `Client`. Apart from the usual exchange cache (default `cacheExchange` or Graphcache) and the React bindings' suspense/concurrent cache, this third cache is just a minor one to share results across all sources.
This change replaces the `Client`'s semaphore with a shared binary semaphore that only stores the result source for a given operation. Hence, an active operation now has a single source that it uses for all subscribers. Apart from the shared source on each subscription it will still emit a new operation. However, all sources for a single subscription now share an underlying source. This source ensures that all operations see the exact same result (which was only implicitly guaranteed before) …
=> (core) - Make Client more forgiving by sharing result sources that emit cached results

.changeset/bright-tools-taste.md, exchanges/graphcache/src/extras/relayPagination.ts, exchanges/graphcache/src/operations/invalidate.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/store/data.ts, exchanges/graphcache/src/store/keys.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/types.ts
This is a supporting PR for #1551 and #901 and some commits were lifted from other branches into this new PR.
Some types in Graphcache weren't accurate enough, especially when using them as extensions for generated types, for conveying the intent of some methods on `Store` / `Cache`, and lastly when typing some scalar and link fields.
Mainly interesting is that `FieldArgs` is a new type that was generalisable, because it was used in this form quite frequently. It's simply `undefined | null | Variables`, a common input for a field's arguments.
The other adjustment that's notable is that `NullArray` can now be nested in on itself, because lists in GraphQL can be nested arbitrarily often. (There was actually one case where Graphcache wasn't handling this well in reference counting)
And …
=> (graphcache) - Improve internal typings for lists, scalars, and overall cleanliness

.changeset/moody-mice-arrive.md, docs/api/graphcache.md, docs/graphcache/cache-updates.md, docs/graphcache/errors.md, exchanges/graphcache/src/operations/shared.ts, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/types.ts
This allows the user to pass in a rootKey or entity from which we'll derive the rootKey for instance Query or { __typename:'Todo', id: 1 }, secondly we accept a field, this can be for instance author which will be applied to the rootKey. As a thirth argument we accept the entity or entities to be written as keys to the rootKey.field, for example { __typename: 'Author', id: 1 } and as a last argument we accept fieldArguments, these will be applied to the fieldKey and will help with fields that have their own arguments for instance: Todo:1.authors({ first: 10 }).
Resolves: #1485
- Adds `cache.link` to graphCache to be used in updaters
=> (graphcache) - Add cache.link method for writing links

.changeset/beige-candles-kneel.md, .changeset/fluffy-ligers-draw.md, docs/api/vue.md, docs/basics/vue.md, packages/vue-urql/example/package.json, packages/vue-urql/example/src/App.vue, packages/vue-urql/example/src/components/HelloWorld.vue, packages/vue-urql/example/yarn.lock, packages/vue-urql/package.json, packages/vue-urql/src/index.ts, packages/vue-urql/src/useClient.ts, packages/vue-urql/src/useClientHandle.ts, packages/vue-urql/src/useMutation.test.ts, packages/vue-urql/src/useMutation.ts, packages/vue-urql/src/useQuery.test.ts, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.test.ts, packages/vue-urql/src/useSubscription.ts, yarn.lock
Resolve #1596
This adds a `useClientHandle()` function as per the #1596 RFC. The function creates a `handle` instance on which all `use*` hooks can be called as methods. This allows `handle.useMutation` to be called at any time and `handle.useQuery` and `handle.useSubscription` to be chained for more elaborate setups, e.g. for passing an ID from a `await handle.useQuery(...)` call into a `await handle.useSubscription(...)` call.
The general usage may look something like this (this is obviously pseudo code and chaining should be avoided when possible to avoid query waterfalls):
```js
import { ref, computed } from 'vue';
import { gql, useClientHandle } from '@urql/vue';
export default {
async setup() {
const handle = useClientHandle();
const pokemons = await handle.useQuery({
query: gql`
{ …
```
=> (vue) - Implement client handles with methods to call hooks

.changeset/large-frogs-tease.md, packages/core/src/client.test.ts, packages/core/src/client.ts, packages/core/src/utils/streamUtils.ts
Previously, in #1515 we merged the groundwork for making identical operations that are run concurrently more intuitive. Namely, when an active source is active multiple times then the sources that newly become active will have the last known result replayed. (There was one bug in there that's fixed in here; See "Set of changes")
We can use the same principle to make concurrent operations in general more intuitive. While it'd seem to make sense to create some kind of "result cache" that prevents unnecessary work, we now have the foundation that we need to make this intuitive and seamless, on top of existing logic.
With these changes applied we will now _not_ dispatch a new operation on the `Client` and instead use the replayed result when the request policy _isn't_ `network-only` or …
=> (core) - Avoid dispatching an operation for already active cache-first/only operations

.changeset/new-dingos-clean.md, packages/core/src/client.test.ts, packages/core/src/client.ts, packages/core/src/utils/streamUtils.ts
Resolves #1621
We discovered a slight regression in `@urql/core@2.1.0` that caused reexecuting an operation to not be possible under the usual circumstances anymore. The reason for this was that the `replayOnStart` utility was effective but we'd share the entire source too eagerly. Since this source was shared, no new operation would be created for future concurrent runs which makes changing the `requestPolicy` of an operation, e.g. for the `executeQuery` function in bindings, impossible.
Instead, I've now moved the implementation back to `Client` and cleaned it up a little, which should make it easier for us to predict how it'll behave. Sources aren't completely shared anymore and instead (which was the same in a prior implementation) we only share the result source and store that …
=> (core) - Fix concurrent operations not respecting request policies

.changeset/ten-pets-remain.md, exchanges/graphcache/src/ast/schemaPredicates.ts, exchanges/graphcache/src/store/store.test.ts
Resolve https://github.com/dotansimha/graphql-code-generator/issues/5981
- Add missing test for formatted introspection query on introspected schema-aware store
- Add cases for built-in typenames to `ast/schemaPredicates`
=> (graphcache) - Fix edge-case of erroring introspection on schema-awareness

.changeset/empty-zoos-compete.md, packages/core/src/client.test.ts, packages/core/src/client.ts
Resolves #1633
This will need further investigation and I'd like to find a nicer implementation for this behaviour (our test suite should guide us there).
The short story here is that it seems that the `toPromise` implementation in Wonka is a little flawed and doesn't quite operate correctly. In fact, it doesn't seem to work correctly as soon as a subject is added to the direct descendants of the source.
- Replace subject in `client.executeRequestOperation` with `make` i.e. anonymous source
=> (core) - Fix Client hang on promisified sources

.changeset/plenty-frogs-remember.md, packages/core/src/__snapshots__/client.test.ts.snap, packages/core/src/client.test.ts, packages/core/src/client.ts, packages/next-urql/src/__tests__/with-urql-client.spec.ts, scripts/eslint/preset.js
- Create an `interface Client` type with all internals hidden
- Convert `Client` to an ES5 factory/constructor pattern
- Ensure that `Client` can both be called with or without `new` (types remain the same)
- Hide internals in factory function using scoped closure variables as needed
`3.68kB minzipped` to `3.59kB minzipped`
=> (core) - Refactor Client to hide some impl details and reduce size

.changeset/swift-pumas-tie.md, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/offlineExchange.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/types.ts
When using the types like https://github.com/FormidableLabs/urql/discussions/1654 we run into an issue with the typings of our current `updateResolver`, this because `[key: string]` is seen and TS expects `__typename`. A similar fix has been put into place for the `resolversconfig`
[Playground](https://www.typescriptlang.org/play?#code/PTAEAkFMBsAdIE6gC4E94GcBQkAesB7BZFdSUAOQFdpoBBBBAQ1QB4AVAPlAF5QHmbAHY1ooAD6h2EyqIEsOnTgG4sOfERIBLIckQAzJgGNyAMWYBzALaRdGUAG8soUAG19lm7opMbALlAMZAQdCwBdAIA3Ai0AE1UAXzUQUABlIyZoJiQ0TFBs8iECEltkLTLIeyZ7WGySAn1QBErCIQxyWKZkJnVCYlJ4UAAFEKtyrUjyPhFaGRErACNEGQWCAmhIJiEZIJChC1VezVAdPQRDEzSMrIQAeQWAK0gjEicXIwI24KoXogB+AKmKhCF5aT6qFyuADWkFQAV2oQi+SEqESajwfRIuXI6Uy2V4w1G40mMlxN3uTxehwxx1OBmMONQQUgVlMWhgsXsb1AAH0edihL5IPDgqEIby4gDAqL9nMqItlpIZtBxSdYlKEbKlfKlkhtbQ0Ud+tjQ …
=> (graphcache) - loosen type constraint on the graphCache generic

.changeset/strange-elephants-add.md, exchanges/graphcache/src/default-storage/index.ts
We were clearing on `ENTRIES_STORE_NAME` without an active transaction. Fixes #1684 
- add `ENTRIES_STORE_NAME` to `storage.clear()` transaction
=> (graphcache) - add the ENTRIES_STORE_NAME to the clear transaction

.changeset/smooth-hounds-battle.md, packages/core/src/utils/streamUtils.ts
Prevent stale results from being emitted by promisified query sources, e.g. `client.query(...).toPromise()` yielding a partial result with `stale: true` set. Instead, `.toPromise()` will now filter out stale results.
- Add `OperationResult` limitation and `filter` operator to `withPromise`
=> (core) - Prevent stale results from promisified sources

.changeset/grumpy-dogs-allow.md, packages/react-urql/src/hooks/useQuery.ts
Fix #1698
Fix issue with `useQuery`'s `executeQuery` state updates, where some calls wouldn't trigger a source change and start a request when the hook was paused.
=> (react) - Fix pause + executeQuery issue in useQuery

.changeset/loud-ghosts-sparkle.md, packages/svelte-urql/src/operationStore.ts, packages/svelte-urql/src/operations.ts
Resolves #1716
Improve `OperationStore` and `subscription` types to allow for result types of `data` that differ from the original `Data` type, which may be picked up from `TypedDocumentNode`.
- Add a `Result = Data` generic to `OperationStore`
- Fix generic usage on `subscription` to assign new `Result` type to store
=> (svelte) - Fix typings for subscription's differing results

.changeset/khaki-guests-hope.md, packages/vue-urql/src/useMutation.test.ts, packages/vue-urql/src/useMutation.ts
Fixes https://github.com/FormidableLabs/urql/issues/1658
- use `executeMutation` over `mutation`
=> (vue) - use executeMutation in useMutation

docs/basics/core.md
I noticed that a lot of folks are having trouble finding "Node.js" as a keyword in the menu or via the search, so I think we should rename the "Core" page to account for that.
=> (core) - Rename "Basics" > "Core" page for discoverability

.changeset/fresh-moose-exist.md, packages/core/src/client.test.ts, packages/core/src/client.ts
Resolve #1754
This fixes an accidental change from `v2.1.0` onwards that prevented `stale: true` from being added onto reexecuting operations when those were using `cache-first`. We reverted this to instead always update the `stale` flag except for `cache-only` as it was before.
=> (core) - Fix stale on reexecute being skipped for cache-first

.changeset/sweet-beers-brush.md, .gitignore, exchanges/request-policy/src/requestPolicyExchange.ts
Resolves https://github.com/FormidableLabs/urql/issues/1644
Do not set the TTL unless cache outcome is "miss". If the first result to come through the requestPolicyExchange was a cache-hit then the ttl was set initially based on this cache hit and no network request was made. This happens when using
persisted caching with the graphcache exchange since the very first result could be a cache hit.
=> (request-policy) - Fix requestPolicyExchange usage with persisted caching

.changeset/silent-carpets-judge.md, exchanges/persisted-fetch/src/sha256.ts
The `@urql/exchange-persisted-fetch` package is not currently being minified to the fullest extent and even throws warnings in some minifiers/bundlers, such as esbuild, because it contains a direct call to `eval()`.
Every minifier (including terser, which is being used to generate minified bundles of urql libraries) avoids mangling names when there is a direct `eval` call in scope. Because a direct call to eval gives the code being evaluated access to the scope from which it was called, there's no way for the minifier to know what side-effects that evaluted code has, so it avoids making optimizations.
By changing it to an indirect eval, we get smaller outputs, even though more boilerplate was added to the code:
* `urql-exchange-persisted-fetch.min.js` shrinks from `3299b` to …
=> (exchange-persisted-fetch) - Make indirect eval call to optimize for minifiers

.changeset/quiet-pants-refuse.md, exchanges/graphcache/src/types.ts
This PR fixes type mismatch which happens when pass generated GraphCacheConfig to CacheExchange and you have mutations that returns scalar type.
fixes #1766 
* fixed type definition of OptimisticMutationResolver
=> Fixed: Type mismatch between GraphCacheConfig and CacheExchange

.changeset/strange-windows-repair.md, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts
Resolve #1429 
Refactor `useQuery` implementation to utilise the single-source implementation of `@urql/core@2.1.0`. This should improve the stability of promisified `useQuery()` calls and prevent operations from not being issued in some edge cases.
=> (vue) - Simplify useQuery implementation

.changeset/cuddly-readers-walk.md, packages/core/src/exchanges/ssr.test.ts, packages/core/src/exchanges/ssr.ts
Related #1775 
Resolve #1771
Prevent `ssrExchange().restoreData()` from adding results to the exchange that have already been invalidated. This may happen when `restoreData()` is called repeatedly, e.g. per page. When a prior run has already invalidated an SSR result then the result is 'migrated' to the user's `cacheExchange`, which means that `restoreData()` should never attempt to re-add it again.
- Invalidate results in `ssrExchange` with `null` rather than `delete`
- Use `null` entries to prevent overwriting invalidated results
=> (core) - Fix ssrExchange.restoreData adding invalidated results

.changeset/spicy-impalas-repair.md, packages/next-urql/package.json, packages/next-urql/src/with-urql-client.ts
Resolves #1714 
This aims to fix two things
1. When we first visit a page and later do `resetUrqlClient`. We do end up using a new client because `urqlClient` prop was set to null. But due to `ssr.restoreData(urqlServerState)` Results are fetched from old ssr cache and network isn't called.
2. When we navigate to a new page (client side rendered) `urqlClient` prop is not null and that is the client we use. Now if you call `resetUrqlClient`, we don't get a `new client` because of existing `urqlClient` prop value. `if (urqlClient) return  urqlClient`
=> (next) - Prevent restoring SSR data when client has been reset

.changeset/quick-shrimps-fetch.md, packages/svelte-urql/src/operations.ts
Resolve #1716
Resolve #1750
There isn't a much cleaner way of inferring this. Either `operationStore` _needs_ to be explicitly typed with a `Result` generic, or the `subscription(...)` type needs to be looser and assign a more specific type to its return value. There isn't really an in-between solution.
As this is confusing to many, I'm thinking of just loosening the type.
=> (svelte) - Loosen subscription type further

.changeset/chilly-laws-trade.md, docs/api/svelte.md, docs/basics/svelte.md, examples/with-svelte/package.json, examples/with-svelte/vite.config.js, packages/svelte-urql/src/internal.ts, packages/svelte-urql/src/operationStore.test.ts, packages/svelte-urql/src/operationStore.ts, packages/svelte-urql/src/operations.ts
Resolve #1678
This changes the internal logic of `operationStore` to make updates more granular, which prevents accidental updates when nothing has actually changed. It also updates the `operations`' sources to check the identity of `context` instead of doing a deep comparison. These changes together will allow for more granular updates of the operations.
Additionally, this PR also adds a `reexecute` method to the stores, which allows the context value to be force-changed.
=> (svelte) - Refactor OperationStore update logic to be more granular

.changeset/happy-radios-wonder.md, exchanges/graphcache/src/cacheExchange.ts
Fix hydration running into issues when there are operations added synchronously after the readData promise resolves
- Convert cache rehydration to buffer implementation
=> (graphcache) - hydration issue in storage restoration

.changeset/grumpy-tomatoes-cheat.md, exchanges/multipart-fetch/package.json, yarn.lock
Resolve #1791
The multipart fetch exchange no longer works correctly with ReactNative. This is due to the `extract-files` package being somewhat out of date.
When performing a file upload the files list is not correctly extracted from the operation variables, this results in the operation being sent to the server as a normal fetch request with `application/json` as the content type.
The server doesn't recognise the upload with `[CombinedError: [GraphQL] map[string]interface {} is not an Upload]`.
A simple version bump of this package fixes uploads.
* Upgrade `extract-files` to the latest release 11.0.0
=> (multipart-fetch) - Upgrade extract-files

.changeset/weak-boxes-speak.md, exchanges/auth/src/authExchange.ts
First of all thanks a lot for this awesome GraphQL client 
`useMutation` gives up the posiblity to infer Data/Variables if we pass a typed-document as you can see here [useMutation.ts#L35](https://github.com/FormidableLabs/urql/blob/main/packages/react-urql/src/hooks/useMutation.ts#L35), unlike mutate from auth-exchange which only accepts `DocumentNode` and not `TypedDocumentNode`
- allow `mutate` exposed by the `getAuth` to accept `TypedDocumentNode` to make type inference possible
=> (auth) - Allow mutate from the getAuth to accept a TypedDocumentNode

docs/api/svelte.md, docs/basics/svelte.md
Resolves https://github.com/FormidableLabs/urql/issues/1805
Reflect the need for immutable variables changes or an explicit `reexecute` call.
=> (docs) - update svelte for the reexecute change of 1.3.0

.changeset/dull-crabs-sit.md, packages/vue-urql/src/useMutation.ts, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts, packages/vue-urql/src/utils.ts
Relates to https://github.com/FormidableLabs/urql/discussions/1809
When we use `variables` in vue we'll pass it in as a `ref` which in `vue` is a proxy or proxy-like object, this means if we don't unwrap it we'll send this through the exchanges-chain which in this case caused issues in IndexedDB.
I'm wondering if there's more places where we could mutate/.... a variable that goes into the exchange-pipeline.
- unwrap `variables` proxy-ref before sending it through to the client
=> (vue) - unwrap the proxy variables before we send it to the urql-client

docs/advanced/testing.md
related #868 
In the docs, testing mutation example instructs `expect(mockClient.executeMutation).toBeCalledWith(expect.objectContaining({ variables }))`
but it won't pass the test because the second argument of executeMutation is missing.
This PR adds the second argument to the example in order to avoid confusion.
=> docs: fixed mutation test example which doesn't pass the test

.changeset/weak-doors-cheer.md, packages/core/src/client.test.ts, packages/core/src/client.ts, packages/core/src/utils/request.ts
Fixes https://github.com/FormidableLabs/urql/issues/1827
Errors out when an invalid operation-node is passed into our client-methods
- throw an error when passing in the wrong operation-type to the urql-client
=> (core) - error for invalid operation passed to query/mutation/subscription

.changeset/spicy-suits-tease.md, exchanges/auth/src/index.ts
Exposes the `AuthConfig<T>` type in the auth exchange package. This would be useful for doing something like:
```ts
const baseAuthConfig: AuthConfig<MyAuthContext> = { ... }
```
Currently `AuthConfig` cannot properly be derived at all because it is generic.
```ts
type AuthConfig = Parameters<typeof authExchange>[0] // => AuthConfig<unknown>
```
- re-export `AuthConfig<T>` from `authExchange.ts`
=> (auth) - expose AuthConfig type

.changeset/sour-goats-agree.md, exchanges/execute/src/execute.ts, exchanges/execute/src/index.ts
This PR exposes ExecuteExchangeArgs from execute-exchange which would be useful when you wrap executeExchange in your function and pass the configuration args accordingly (e.g. testing).
* export ExecuteExchangeArgs
=> expose ExecuteExchangeArgs

docs/common-questions.md
The current example perfectly suits some use-cases but can't be used "as is". If you copy it into TS project, you'll see a few errors. Fixing these errors requires some understanding of exchange internals and wonka API.  
I see two possibilities how to make it easier to get started with the `urql` here:
1) Make it able to copy and paste the code example
2) Add `fetchOptionsExhange` to the core (as @RodolfoSilva originally suggested [here](https://github.com/FormidableLabs/urql/issues/234#issuecomment-602305153))
I implemented first as a simple solution, but maybe second would be even a better option?
Changed the current example a bit by adding the missing imports and types.
=> Make "async fetchOptionsExchange" example copy-able

.changeset/rich-tigers-brush.md, packages/next-urql/package.json, packages/next-urql/src/__tests__/with-urql-client.spec.ts, packages/next-urql/src/types.ts, packages/next-urql/src/with-urql-client.ts, yarn.lock
Fixes #1794
This leverages the built-in types of `Next` to type our `withUrqlClient`.
An example `_app` typed:
<details>
<summary>Example of  an `_app`</summary>
```tsx
import type {AppProps} from 'next/app'
import {withUrqlClient,NextUrqlAppContext} from "next-urql";
import {cacheExchange, dedupExchange, fetchExchange, ssrExchange} from "urql";
import React from "react";
import App from "next/app";
function MyApp({ Component, pageProps }: AppProps) {
return <Component {...pageProps} />
}
const isServerSide = typeof window === "undefined";
const ssr = ssrExchange({
isClient: !isServerSide,
initialState: !isServerSide ? window.__URQL_DATA__ : undefined,
});
const UrqlWrappedApp = withUrqlClient(() => ({
exchanges: [
dedupExchange,
cacheExchange,
ssr,
fetchExchange,
],
url: …
```
=> (next) - leverage the next package to provide the types for our withUrqlClient

.changeset/giant-jobs-cross.md, packages/core/src/internal/fetchOptions.ts
Fix prevent mangling embedded strings in queries sent using the `GET` method.
- Alter the regex so it only removes comments
=> (core) - prevent mangling embedded strings in queries

.changeset/popular-mirrors-lick.md, packages/core/src/client.ts
The [single-source behavior previously](https://github.com/FormidableLabs/urql/pull/1515) wasn't effective for implementations like React, where the issue presents itself when the state of an operation is first polled. This led to the operation being torn down erroneously.
Fix #1841
- We now ensure that operations started at the same time still use a shared single-source.
=> (core) - fix single-source behavior in integrations

.changeset/new-horses-bow.md, .changeset/spicy-poems-rule.md, docs/advanced/server-side-rendering.md, docs/api/core.md, packages/core/src/exchanges/cache.ts, packages/core/src/exchanges/ssr.ts, packages/next-urql/src/types.ts, packages/next-urql/src/with-urql-client.ts
Resolve #1846
This adds a `staleWhileRevalidate` option to both the `ssrExchange` and `next-urql`'s `withUrqlClient`, which allows the `ssrExchange` to mark a result as stale while it forcefully refetches a new server result. This is similar but different to `cache-and-network` as we wouldn't recommend changing the request policy on every operation by default, which would also be ineffective as the `ssrExchange` "imitates" full network results.
- Add `staleWhileRevalidate` to `ssrExchange` in `@urql/core`
- Add `staleWhileRevalidate` to `withUrqlClient` in `next-urql`
=> (core) - Add staleWhileRevalidate option to ssrExchange

.changeset/chilled-pears-eat.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/operations/query.ts
Resolve #1867
When a given field cascades as `undefined` into a list and the schema shows this list as nullable, then the query wouldn't be marked as partial and subsequently the list would contain `null` without the query being refetched.
- Add missing `ctx.partial` mark to `resolveLink`
- Add missing `ctx.partial` mark to `resolveResolverResult`
=> (graphcache) - Add missing partial mark to null cascading into list

.changeset/rude-pumpkins-yawn.md, packages/core/src/utils/typenames.test.ts, packages/core/src/utils/typenames.ts
When a plugin manipulates `operation.query` with for instance removing a directive, changing the selectionSet, ... we would restore the original query with subsequent invocations of `formatDocument`. By marking `query.__key` as non-enumerable we prevent this, this does assume that the consuming exchange uses `visit` or any other cloning traversal mechanism to manipulate the query.
- mark `query.__key` as non-enumerable
=> (core) - mark query.__key as non-enumerable

.changeset/mean-pugs-laugh.md, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/store/data.ts
Fix #1878
Fix previous results' `null` values spilling into the next result that Graphcache issues, which may prevent updates from being issued until the query is reexecuted. This was affecting any `null` links on data, and any queries that were issued before non-optimistic mutations.
- Separate input from output data in `operations/query.ts`
- Fix typo in owned-data check for `resolveLink`
- Fix skipped layers being disregarded if last result was falsy
=> (graphcache) - Fix previous result's null values spilling into next result

.changeset/thick-seals-wait.md, packages/core/src/utils/streamUtils.ts
This change ensures that when we call `toPromise()` on a query we wont serve an incomplete result, the user will expect to receive a non-stale full-result when using `toPromise()`
- Account for `hasNext` in `toPromise`
=> (core) - update toPromise to exclude `hasNext` results

.changeset/swift-apples-flash.md, exchanges/graphcache/src/cacheExchange.ts
Resolves #1904
We've forgotten to remove `hasNext: true` from debugging in Graphcache's `cacheExchange`, which causes each stale result to be marked with `hasNext: true`. This erroneously causes the `dedupExchange` to prevent further operations, although this wasn't intended.
- Remove `result.hasNext = true` from `cacheExchange` generated stale results
=> (graphcache) - Remove hasNext from stale results

.changeset/cool-zoos-whisper.md, packages/svelte-urql/src/operationStore.ts
Fixes #1924 
- add missing property on operationStore return type
=> (svelte) - add missing `pause` on the `operationStore`

.changeset/flat-queens-refuse.md, packages/core/src/exchanges/ssr.ts
Resolves https://github.com/FormidableLabs/urql/issues/1888
When an operation would get reexecuted due to `staleWhileRevalidate: true` it would keep on hitting this branch as we don't filter out `network-only` results from the `ssrCache` response
- Guard against infinite loops within the `ssrExchange`
=> (core) - fix issue with ssr-exchange looping for reexecuted ops

.changeset/tasty-dragons-check.md, packages/vue-urql/src/useClient.ts
Relates to https://github.com/FormidableLabs/urql/discussions/1961
- Allow for passing in `Ref<Client>` to `provideClient` and `install`
=> (vue) - allow for passing in the client as a ref

.changeset/afraid-kiwis-end.md, exchanges/graphcache/src/ast/schemaPredicates.ts
[benchmark](https://perf.link/#eyJpZCI6InNlZjQ2MWM3NDFrIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGRhdGEgPSAnX190eXBlbmFtZSc7XG5jb25zdCBCVUlMVElOX05BTUVfUkUgPSAvXl9fLztcbmNvbnN0IEJVSUxUSU5fTkFNRSA9ICdfXyc7IiwidGVzdHMiOlt7Im5hbWUiOiJpbmRleE9mIiwiY29kZSI6ImRhdGEuaW5kZXhPZihCVUlMVElOX05BTUUpID09PSAwOyIsInJ1bnMiOlszOTUwMDAwLDQwMDIwMDAsMjY0MDAwMCwzNDk3MDAwLDE4ODEwMDAsMTI1OTAwMCw0MTQ5MDAwLDM1MjIwMDAsMTg5MjAwMCwyMzc0MDAwLDMwNDgwMDAsMTI4ODAwMCwxODEwMDAsODMwMDAwLDExNDAwMDAsMTk0NzAwMCwyNTU3MDAwLDM3MDAwMDAsNDA2OTAwMCwxNzk4MDAwLDEzNTAwMCwzMTgwMDAsMjI4NjAwMCwxODc2MDAwLDE4MzkwMDAsMzA0OTAwMCwxNjM1MDAwLDE4MTEwMDAsMzYyODAwMCwzMzYyMDAwLDE0ODEwMDAsMTk0MzAwMCwxNzg3MDAwLDIyNTIwMDAsMzM3NjAwMCwxOTM4MDAwLDI0MTAwMDAsMjUwODAwMCwzMDY4MDAwLDg4NjAwMCwxMTAwMDAwLDMxNDkwMDAsMTQyO …
=> (graphcache) - improve perf by using String.indexOf in getField

README.md
Resolves https://github.com/FormidableLabs/urql/issues/1959
- consolidate concepts link to only include architecture
=> (chore) - fix broken link to architecture page

.changeset/polite-jobs-call.md, exchanges/graphcache/src/operations/query.ts
Resolve #1969
#1869 introduced a regression for nullable lists when schema awareness is used. The intended behaviour is that any `undefined` value in a list (due to a cache miss) causes the list to also become undefined immediately, or to default to a `null` value when it's nullable. Unfortunately, when the list is marked as nullable (as derived by a passed schema with schema awareness) it'd now always be marked as "partial".
=> (graphcache) - Fix nullable lists with schema awareness

.changeset/tidy-tables-promise.md, exchanges/graphcache/default-storage/package.json, packages/core/src/exchanges/ssr.test.ts, packages/core/src/exchanges/ssr.ts
I opened a discussion about this some months ago [here](https://github.com/FormidableLabs/urql/discussions/1764), but it did not get much attention so I'm trying to implement this myself :)
Adding a new `includeExtensions?: boolean` option to `ssrExchange`. When this option is enabled the `extensions` field of the operation results will be included in the serialised cache, and will be restored when restoring the cache.
The motivation behind this is to make cached and non-cached operations behave more consistently.
For example, when `extensions` include some metadata for the consumer to use (e.g. tracing/tracking info), then these data are not available when restoring the cache currently, as the `extensions` field don't get serialised/restored.
I added this as an option instead of making …
=> (core) - Add `includeExtensions` option to `ssrExchange`

docs/architecture.md
=> (docs) - fix typo in architecture.md

.changeset/seven-scissors-rescue.md, packages/core/src/types.ts
This tweaks the `ExecutionResult` type to line up with:
- [`graphql-ws`](https://github.com/graphql/graphql-js/blob/main/src/execution/execute.ts#L131)
- [`subscription-transport-ws`](https://github.com/graphql/graphql-js/blob/main/src/execution/execute.ts#L131)
Both link to `graphql` as they reuse this `ExecutionResult`, should we do too?
Resolves https://github.com/FormidableLabs/urql/issues/1989
- tweak error to `GraphQLError`
=> (core) - tweak ExecutionResult to line up with the graphql lib

.changeset/hungry-monkeys-fry.md, exchanges/execute/src/execute.test.ts, exchanges/execute/src/execute.ts, scripts/eslint/common.js
* add support for subscriptions in execute exchange
The execute exchange is excellent for testing and various other uses cases. This PR adds support for subscriptions. In `graphql-js` v16, this will be even easier to implement since `execute` will support subscriptions out of the box.
These changes are non-breaking, but let me know if this requires an RFC.
Example of a subscription that generates numbers. This can be added to e.g. `rootValues`:
```js
const subscription = async function* numbers(...args) {
let number = 0
while (true) {
await sleep(1000)
yield { number: number++ }
}
}
```
- Added subscription support
- Added new `subscribeFieldResolver` argument to the exchange
- Changed `execute` argument to object
- When an operation has ended, call `done` on the generator.
- Updated …
=> (execute) - Subscription support

.changeset/spotty-bees-beam.md, packages/next-urql/src/with-urql-client.ts
Adds support for [Per page layouts](https://nextjs.org/docs/basic-features/layouts#per-page-layouts)
ex: https://codesandbox.io/s/confident-matsumoto-65389?file=/pages/index.js
- Checks the page and hoists the `getLayout` function up
=> (next) - support per page layout

docs/graphcache/offline.md, packages/storage-rn/README.md
Forgot to update the installation instructions for storage-rn after renaming the package.
- update the installation script in the readme
- add the installation script to the docs site
=> (docs) - update storage-rn installation instructions

docs/basics/ui-patterns.md
We were missing the pause in the `useQuery` hook
=> (docs) - add pause to lazy-query

.changeset/metal-monkeys-knock.md, packages/core/src/utils/maskTypename.test.ts, packages/core/src/utils/maskTypename.ts
resolves https://github.com/FormidableLabs/urql/issues/2072
`maskTypename` wasn't taking array shapes in account when traversing the result shape
- add `isArray` argument to `maskTypename` so the recursion can hold on to array shapes
=> (core) - Fix maskTypename not handling nested arrays

examples/with-refresh-auth/src/App.jsx
I decided to try and test the auth exchange package's example and noticed it wasn't compiling so I added the missing imports (useState and useEffect).
=> (examples) - Added missing useState and useEffect import.

.changeset/real-hairs-attend.md, packages/next-urql/src/with-urql-client.ts
When `getInitialProps` indicates that the response has ended, we should not go into `prepass` but instead we should just return the data we have up until that point. As it indicates that the route has errored _or_ redirected
- check `res.finished` before continuing the prepass
=> (next-urql) - prevent next-urql from doing a prepass when the response has ended

.changeset/green-queens-exercise.md, exchanges/refocus/src/refocusExchange.ts
Resolves #2094
We used to lose the context on all operations we reexecute once focus is regained.
- Spread context into new operation
=> (refocus) - use context of the operation we are reexecuting

.changeset/four-moose-scream.md, exchanges/retry/src/retryExchange.ts
Resolve #1932 
**NOTE:** This is simply an _attempt_ at resolving the issue above. I'm not sure if this is actually the cause so it'll need to be tested.
Our current theory is that because the `delay` operator separately applies a timeout (e.g. `setTimeout`) to each signal, that signals in the same tick (in this case `Push` then `End`) are sometimes flipped. Usually this isn't an issue but with only one value to push the reordering can cause the signal to be swallowed entirely.
To mitigate this I'm attempting to simply validate this by swapping out `delay` with `debounce`, since the latter applies timeouts differently but otherwise behaves identically (in theory) for single values.
- Replace `delay` with `debounce` in `retryExchange` retry logic
=> (retry) - Fix delay misqueue in React Native

.changeset/twenty-dolphins-grab.md, exchanges/persisted-fetch/src/sha256.ts
Resolves #2077 
Add support for Web Workers via the `self` global and fix support in Node ESM by trying a dynamic import when `require` fails. This also fixes up a mistake in IE11 support, where `msCrypto` was treated as `msCrypto.subtle` accidentally.
- Check for `self` and `window` global
- Fix `msCrypto.subtle` usage
- Add dynamic `import("crypto")` fallback in require check
=> (persisted-fetch) - Fix Crypto API support for Web Workers and Node ESM mode

docs/api/core.md
`takes are of` -> `takes care of`
=> (docs) - Fix typo in core.md documentation

.changeset/chilly-camels-know.md, exchanges/graphcache/default-storage/package.json, package.json, yarn.lock
Upgrade to latest release of `babel-plugin-modular-import` to guarantee consistent imports across all three major releases of `graphql`.
- Update `babel-plugin-modular-graphql`
- Bump `@urql/exchange-execute`
=> (chore) - Upgrade babel-plugin-modular-import

.changeset/gentle-readers-tan.md, packages/core/package.json, packages/svelte-urql/src/operationStore.ts, packages/svelte-urql/src/operations.ts, yarn.lock
[typed-document-node v3.1.1 introduces gql16 capabilities](https://github.com/dotansimha/graphql-typed-document-node/releases/tag/core%40v3.1.1)
- bump our dep to 3.1.1 for all folks upgrading
=> (core) - bump typed document node for gql16

.changeset/fix-use-mutation-in-react-18.md, packages/react-urql/src/hooks/useMutation.ts
Resolves #2109.
React 18 has introduced [Strict Effects](https://github.com/reactwg/react-18/discussions/19) in Strict Mode, which results in all effects being executed twice in dev mode, regardless of whether the contents of the dependency array has changed. I've also noticed that the same thing happens with Fast Refresh in React 17: all effects re-run. `useEffect`, even when called with dependency array of `[]`, doesn't give any semantic guarantees that it'll only be executed once (something I've only realised recently, and now have to rethink how I approach writing effects in React).
Currently, `useMutation` has a `useEffect` that's incompatible with React 18 or Fast Refresh. The fix seems to be rather simple: set `isMounted` reference to `true` when the hook gets executed.
- Should we …
=> (react) Ensure useMutation is compatible with React 18

docs/graphcache/cache-updates.md
I was a little confused to understand how it works, until I realized that the mutation name was wrong.
=> (docs) - Fix wrong mutation names in graphcache docs

docs/advanced/authentication.md, docs/advanced/server-side-rendering.md, docs/advanced/testing.md
Resolves #2187 
This PR adds missing imports to chapters that were missing them.
- add imports to a few chapters including ssr/auth
=> (docs) - add missing imports to code-blocks

.changeset/bright-llamas-report.md, packages/core/src/client.ts
Resolves #2184 
When we are dealing with mutations of let's say `files` then the key could be equal for different sets of variables, this PR moves mutations from key-checking to referential equality of the `operation` itself, this means that every request will have it's own result-source. This allows for us to repeat a set of mutations with different inputs
This was triggered by the discussion in https://github.com/FormidableLabs/urql/discussions/2183
- move from key-checking to operation checking
=> (core) - allow for multiple concurrent mutations of the same key

.changeset/strong-islands-hope.md, packages/core/src/exchanges/ssr.ts
On the prior lines we defer clearing the data by a microtick which means that the redispatched "network-only" request will also be served from the ssr-cache. We could also opt to defer the redispatch by a microtick but imo it's better to treat network-only requests as bypassing this. Another possible solution would be to check whether we've seen this before as a `revalidation`
fixes #2059
- filter `network-only` from being served by the ssr-exchange
=> (core) - filter network-only requests from the ssrExchange

.changeset/smart-brooms-fix.md, packages/core/src/internal/fetchSource.ts
When we introduced incremental fetch we made sure that the backwards exchanges flow could be triggered multiple times for an `OperationResult` this made it so that the `fetchSource` would actually have the backwards execution of the exchanges like GraphCache writing data, ... inside of the `try catch` which means that if one of these throws we end up in the catch and handle this as if we encountered a `GraphQL` error.
fixes https://github.com/FormidableLabs/urql/issues/2191
- filter out `Syntax`, `Type` and normal `Error` scenario's coming from the reverse-exchange run
=> (core) - fix incremental fetch not bubbling up JS-errors

.changeset/moody-eels-cough.md, packages/storage-rn/README.md, packages/storage-rn/src/makeAsyncStorage.ts
When clearing the React Native Storage (for example, on logout), the AsyncStorage keys are cleared correctly. However, @urql/storage-rn caches these keys in local memory. This isn't cleared correctly, which means that unless you recreate the entire Urql client the old data persists in local memory even after calling `clear()`.
* Set the `allData` variable to an empty object when `clear()` is called
=> (storage-rn) - Fix issue where cache data is not cleared correctly

.changeset/early-shoes-crash.md, packages/react-urql/package.json, yarn.lock
pin correct version of use-sync-external store as it was automatically going to experimental versions
- pin correct version of use-sync-external store
=> (react-urql) - pin correct version of use-sync-external store

.changeset/funny-pugs-tan.md, packages/react-urql/src/hooks/useQuery.ts
Resolve #2226
Previously, the `useSyncExternalStore` reimplementation regressed
on us constructing the correct initial state on mount, and instead
relied on an abort on mount, which is confusing to users.
Instead, we can simply revert to what we've done prior to the
change and ensure that the initial state is accurate.
This fix **does not** change any of the current behaviour, but simply avoids the confusing state transition on mount.
- Update initial state in `useQuery` implementation
=> (react) - Update initial state to not require abort on mount

.changeset/shaggy-frogs-attack.md, packages/core/src/client.test.ts, packages/core/src/client.ts, packages/core/src/types.ts
Resolve #2225
This addresses a regression from #2189 where a mutation's operation is compared to filter results.
Such a comparison will always fail in the presence of cache exchanges that create new operations to update
the document of the operation (or variables)
Instead, we can introduce a stand-in identity object for the mutation instead and use that to compare.
This isn't a final resolution of the issue but a quick workaround.
- Add `OperationContext._identity` to compare mutation identities
=> (core) - Fix (cloned) mutation operation being compared rather than a stable identity

.changeset/selfish-singers-nail.md, packages/react-urql/src/hooks/useQuery.ts
Issue found in https://github.com/FormidableLabs/urql/discussions/2235 we were setting the resolved promise as the cache-entry resulting in an infinite loop.
[Fixed React sandbox](https://codesandbox.io/s/stoic-pond-q81st?file=/src/useQuery.ts)
[Fixed Next sandbox](https://codesandbox.io/s/crimson-fire-pv25l?file=/lib/useQuery.ts)
fixes #2239
- set cache after assigning `result`
=> (react) - fix issue where the cache infinitely loops

.changeset/loud-vans-try.md, packages/react-urql/src/hooks/state.ts
Fixes #2236
Currently we just merge in with `...result` which will override the data coming from the `...prevState` with undefined for a small amount of time.
[fixed repro](https://codesandbox.io/s/silly-estrela-dupqi)
- don't just spread in result, look at the data attribute individually
=> (react) - diff data correctly for the next state computing

.changeset/ninety-colts-tap.md, packages/introspection/src/getIntrospectedSchema.ts
Fix #2250
Resolves an issue where the old version of `babel-plugin-modular-graphql` wasn't warning us forcefully about `executeSync` not being present in all versions we support, which resulted in it being imported from `"graphql"`, which then instantiates non-mjs duplicate modules in some versions of Node.js (i.e. when Node isn't in ESM mode)
- Replace `executeSync` with `execute`
This release will simply then cause a rebuild and re-release with `babel-plugin-modular-graphql@1.1.0`
=> (introspection) - Fix usage of `executeSync` causing invalid mjs import

docs/advanced/retry-operations.md
This documents the `retryWith` option to implement client-side failover/fallback as discussed in #2254.
add a subsection "Failover / Fallback"
=> (docs) - add fallback via retryWith option to advanced/retry-operations

.changeset/serious-queens-suffer.md, packages/core/src/utils/request.test.ts, packages/core/src/utils/request.ts
Resolve #2290
Resolve #1960
This updates our string sanitization to exclude replacing ignored characters inside of strings.
This is pretty crude but should stop us from accidentally messing up queries to the point where they don't produce valid hashes any longer.
Edit: Bundlesize will be affected in shared import by +59B.
- Update `createRequest`'s stringification to exclude strings in sanitization
- Add appropriate test (previous test wasn't actually checking _our_ string sanitization)
=> (core) - Prevent ignored characters from being sanitized in strings

.changeset/pretty-dingos-argue.md, packages/react-urql/package.json, packages/react-urql/src/hooks/useQuery.ts, yarn.lock
Resolves #2307
Resolves #2299
Resolves #2298
This reverts https://github.com/FormidableLabs/urql/pull/2164  there are a lot of issues going on with manual reexecution and ssr in general, the timings used seem hard to work with and our own source-behavior seems better tailored and was concurrent and suspense-safe
- Revert #2164
=> fix(urql): call `cache.get` inside of snapshots

.changeset/bright-masks-learn.md, packages/core/src/internal/fetchOptions.ts
Fixes https://github.com/FormidableLabs/urql/issues/2374
Currently it looks like the lowest common denominator in url-size is 2048 characters. This means that currently when a query  grows big we can't really send it as GET without it erroring on some browsers.
This PR aims to fix that as when it calculates the url it will check the length and revert back to `POST` if it's too big
- fall back to `POST` when the URL is too lengthy
=> fix(core): limit the url-size to 2048 characters

.changeset/poor-games-teach.md, packages/core/src/utils/streamUtils.ts
Resolves #2364
Fix issue where a synchronous `toPromise()` return would not result in the stream tearing down, this would make it so that subsequent calls would not pass through the exchange-chain
- refactor the implementation of `toPromise` to leverage a subscription that returns on first non-stale completed result
=> fix(core): fix issue with synchronous `toPromise` queries

packages/next-urql/README.md
I noticed the last code block in the next-urql README.md was not highlighted.
Added javascript as the language used for the code block and removed unused import in the example.
=> docs(next-urql): fix README syntax highlighting

docs/advanced/subscriptions.md
In the standalone client example, a variable newMessages holding a query MessageSub is defined but never used; in the body an undefined variable MessageSub is referenced. Renamed to MessageSub uniformly.
Docs have an example that can't be run
one-line docfix
=> Variable name mismatch in subscription docs

.changeset/small-points-protect.md, packages/vue-urql/src/useQuery.ts
Fixes #2409 
Due to the promise already being executed we would be returning old data to the user, this was enforced by us unsubscribing immediately in `take(1)`. Now we wait for the first non fetching and stale result.
- wait for the first non-stale result
=> fix(vue): prevent executeQuery from taking a fetching or prior result

.changeset/pink-turkeys-live.md, .changeset/unlucky-moles-stare.md, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/store/data.test.ts, exchanges/graphcache/src/store/data.ts
This pull request introduces several small tweaks to Graphcache's data layering.
Usually we reserve layers per query operation, create optimistic layers for optimistic mutations, and write to these layers as responses come in in the order they've been reserved in. If they haven't been reserved they'll be created on demand. This means that layers are essentially just queues and we `unshift` to this queue whenever a layer is created. Queueing in order isn't always desireable however.
As we've found out, when a layer expects future updates (`hasNext: true`, as it's been added with deferred results, via `@defer`) it's added to the queue and multiple queries that are started while this layer is still waiting for updates will layer on top of it. We've deemed this acceptable. After all, it's …
=> fix(graphcache): Shift layers with future updates and improve layer behaviour

.changeset/fluffy-toys-live.md, exchanges/graphcache/src/extras/relayPagination.test.ts, exchanges/graphcache/src/extras/relayPagination.ts
Resolves #2430 
Ignores empty pages in the `relayPagination` helper when there is at least one result, so as to preserve the start & end cursor when an empty result is returned with null cursor values.
- Ignore empty pages when we already have at least one page in the cursor
- Adds test for the intended behavior
=> fix: ignore empty relay pagination pages

.changeset/heavy-rabbits-beam.md, packages/core/src/internal/fetchSource.ts
Resolves #2441 
Currently if your `fetch` implementation issues an abort  we will never trigger a result meaning `toPromise()` calls will hang forever. It is actually safe to dispatch a result as in the usual cases this will happen due to the `Query` unmounting or closing the subscription.
- return an error result for an abort
=> fix(core): support aborting in `withPromise` cases

.changeset/two-masks-draw.md, exchanges/graphcache/src/default-storage/index.ts
Resolves https://github.com/FormidableLabs/urql/issues/2443
In the default-storage when we call `clear` we should reset the batch else our users aren't able to reset the normalized cache without reading out the previous cached storage.
- reset `batch` to an empty object
=> fix(graphcache): default storage not clearing idb batch result

.changeset/tasty-cooks-promise.md, packages/react-urql/src/hooks/useSubscription.ts
Resolves #2330
This is a similar fix to https://github.com/FormidableLabs/urql/pull/1982
A paused subscription would not execute with the proper variables if they were different from the point of pausing, this because we would commit the previous deps which would result in the hook thinking nothing changed, this resets the source to null.
- fix stale sources in subscriptions
=> fix(react): execute subscriptions with latest vars

docs/api/svelte.md, docs/basics/svelte.md
Fixes out of date links to Svelte documentation for the `Context` section
and also removes a ZWNBSP character which breaks the H2 for
`Pausable` heading.
=> fix: svelte documentation links for context

.changeset/rich-panthers-wait.md, .github/workflows/ci.yml, exchanges/graphcache/src/store/data.ts, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/test-utils/examples-1.test.ts
Resolves #2478
What was happening was that we have two optimistic mutations with the same key, let's refer to them as `a` and `b`, `a` would set the state to true and `b` would set the state to false.
When `a` comes in we tell our store that our current order of optimistic layers is `[a]` and apply the data of `state: true` to said layer, now we dispatch `b` we tell the store that our order is `[b, a]` and apply the state. Everything is fine up until now, until we dispatch `a` again as optimistic, we would not reorder the layers to say `[a, b]` and instead would hold on to our layer-ordering which prevented the correct state from being read.
This was a bit challenging as we use the ordering for both commutative and optimistic keys, hence the check whether we have a commutative key for the …
=> fix(graphcache): support repeated optimistic updates

.changeset/heavy-carpets-join.md, packages/svelte-urql/src/queryStore.ts, packages/svelte-urql/src/subscriptionStore.ts
Resolves #2513 
Resolves #2508
Resolves #2473
Apparently `derivable` calls `unsubscribe` eagerly on initial invocation making it so that none of our stores were actually listening for changes.
- unsubscribe in writable
=> fix(svelte): delay unsubscribe to writeable

.changeset/quiet-bears-tan.md, scripts/rollup/cleanup-plugin.js, scripts/rollup/plugins.js
Avoid making the imports of `@urql/introspection` more specific than they need to be, this because we aren't optimizing for bundle size and in pure node usage this can confuse Node as `import x from 'graphql'` won't share the same module scope as `import x from 'graphql/x/y.mjs'`
- creates an exclusion on the modular-graphql-imports for `introspection`
=> fix(introspection): usage in node-esm

docs/advanced/server-side-rendering.md
Pass required option to `initUrqlClient` function.
Update documentation of Next.js SSR section to pass required suspense option to `initUrqlClient`.
=> docs: add required suspense option to `initUrqlClient` for Next.js example

.changeset/fast-spoons-relate.md, packages/core/src/exchanges/subscription.test.ts, packages/core/src/exchanges/subscription.ts
I have a live query implementation that can use the existing `subscriptionExchange`, but it would require customizing the `isSubscriptionOperation` function to the following:
```ts
import { isLiveQueryOperationDefinitionNode } from "@n1ru4l/graphql-live-query"
const isSubscriptionOperation = ({ query, variables }) => {
const definition = getMainDefinition(query);
const isSubscription =  definition.kind === 'OperationDefinition' &&  definition.operation === 'subscription'
const isLiveQuery =  isLiveQueryOperationDefinitionNode(definition, variables)
return isSubscription || isLiveQuery
}
```
However, currently, this is not possible, requiring me to copy the subscription exchange code. Other solutions like relay and apollo easily allow customizing this.
Adds a new parameter to …
=> feat: allow providing a custom isSubscriptionOperation function

.changeset/hip-ears-wash.md, packages/core/src/client.ts, packages/react-urql/src/hooks/useQuery.ts
Resolve #2554
⚠️ **We urgently recommend all users of the React bindings to upgrade to this patch as soon as it becomes available!**
Don't forget to deduplicate `@urql/core` to the newest version if you do upgrade, since its fix is important.
During some circumstances we may receive an update that then leads to a mount. React may decide to then recursively & synchronously continue this mount. During it, we used to then block other updates using a `currentInit` flag while the component synchronously reads from the cache. However, since the cache read dispatched its operation (and then terminated), we previously then "piggybacked" off of this dispatch, and flushed other operations.
This means that some potential updates could get lost if they were queued up by the update that  lead to the …
=> fix(react): Prevent the operation queue from being flushed during synchronous cache reads

.changeset/light-dolls-taste.md, exchanges/execute/src/execute.ts
Resolves #2580
This corrects the return type to be the same as just passing one without a function `any`
=> fix(execute): correct return for context function

docs/basics/svelte.md, docs/basics/vue.md
Replace `isn't dissimilar from` with `is similar to`.
... or was there a reason for the double negation? I stumbled across this for so many times now, that I had to make this PR 😅
=> docs: remove double negation

docs/graphcache/local-resolvers.md
Fix cursor value of relayPagination example
Change `after` value from `1` to `a`
=> (docs) - Fix relayPagination example

.changeset/beige-chefs-add.md, package.json, scripts/rollup/cleanup-plugin.js, yarn.lock
Resolves #2539
It seems like importing from `graphql` makes us run into issues, especially in node-environments as imports from the root and imports from the specific packages make us run into the infamous multiple GraphQL instances error. Until the main package moves to full ESM compat with export maps, ... this will be the best fix to support previous versions of GraphQL and current ones
- remove the modular babel plugin
=> chore(build): remove modular graphql

packages/site/src/screens/docs/article.js
Hi there! 👋 
This PR adds overflow for article legend component to add vertical scroll on small height screens:
Added `overflow: auto` and `height` rules for styled `Legend` component
Thank you! This library is awesome :heart:
=> fix(docs): Add overflow for article legend

.changeset/four-dots-camp.md, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts
Resolves https://github.com/FormidableLabs/urql/issues/2274
We update the types here to support nested refs in the `variables` for `useSubscription` and `useQuery`. We currently don't support refs in the callback for `useMutation`, I would leave it be for now personally.
- add the updated type
=> fix(vue): update types to support nested refs

.changeset/hungry-swans-tell.md, docs/api/graphcache.md, docs/graphcache/errors.md, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/store/store.ts
Resolves https://github.com/FormidableLabs/urql/issues/2566
When re-using document-nodes that contain queries/multiple fragments we might need to target a fragment rather than going for the first one. This PR introduces a new argument named `fragmentName` which allows people to target a specific `FragmentDefinitionNode` in a `DocumentNode` by name.
- add `fragmentName` argument to write and read operations
=> feat(graphcache): support passing in name for fragments

.changeset/stale-plants-design.md, exchanges/graphcache/src/types.ts, packages/core/src/client.ts, packages/core/src/exchanges/subscription.ts, packages/core/src/internal/fetchOptions.ts, packages/core/src/types.ts, packages/core/src/utils/request.ts, packages/preact-urql/src/components/Mutation.ts, packages/preact-urql/src/components/Query.ts, packages/preact-urql/src/components/Subscription.ts, packages/preact-urql/src/hooks/useMutation.ts, packages/preact-urql/src/hooks/useQuery.ts, packages/preact-urql/src/hooks/useRequest.ts, packages/preact-urql/src/hooks/useSubscription.ts, packages/react-urql/src/components/Mutation.ts, packages/react-urql/src/components/Query.ts, packages/react-urql/src/components/Subscription.ts, packages/react-urql/src/hooks/useMutation.ts, packages/react-urql/src/hooks/useQuery.ts, packages/react-urql/src/hooks/useRequest.ts, packages/react-urql/src/hooks/useSubscription.ts, packages/svelte-urql/src/common.ts, packages/svelte-urql/src/mutationStore.ts, packages/svelte-urql/src/queryStore.ts, packages/svelte-urql/src/subscriptionStore.ts, packages/vue-urql/src/useMutation.ts, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts, packages/vue-urql/src/utils.ts
Resolve #2606
This attempts to introduce a stricter type for variables preventing it from being an optional property or argument (i.e. `variables?: Variables`) in all parts of the codebase. To do this, we also need to make its type a little more strict with `AnyVariables`, which explicitly defaults the generic to a type of `void | undefined | { ... }`. In case of a generic that's passed in, this also becomes the extension type.
This is currently a draft because some methods on `Client` and some utility functions, like `createRequest`, are affected by this change. We have to check that these behave as expected (as per the change and RFC) and that we don't break them if that isn't necessary
- Add `AnyVariables` and make generics `Variables extends AnyVariables = AnyVariables`
- Update core …
=> fix(core): Implement stricter variable typings on generic

packages/core/src/exchanges/dedup.ts, packages/core/src/exchanges/fetch.ts, packages/core/src/exchanges/subscription.ts, packages/core/src/utils/request.ts, packages/core/src/utils/stringifyVariables.ts, packages/core/src/utils/typenames.ts
- Simplify `dedupExchange` logic
- Prevent `onPush` in `fetch` for production environments
- Replace several `for`-loops with `for-of` loops
- Use `Set` in `collectTypes`
- Remove `.some` from `formatNode`
I'm explicitly not adding a changeset, since it doesn't actually affect the output code and to not pollute the eventual changelog with irrelevant entries.
=> chore(core): Refactor utilities to reduce size (*.min.mjs) by -50B gzip'd

.changeset/four-jokes-tease.md, exchanges/retry/src/retryExchange.ts
Resolves #2614 
As rightfully pointed out in #2614 the OR operator will also make `false`  become `true`
=> fix(retry): make randomDelay work

.changeset/six-rules-study.md, packages/core/src/__snapshots__/client.test.ts.snap, packages/core/src/client.ts, packages/core/src/exchanges/fetch.ts, packages/core/src/exchanges/ssr.ts, packages/core/src/gql.ts, packages/core/src/internal/fetchOptions.ts, packages/core/src/internal/fetchSource.ts, packages/core/src/utils/error.ts, packages/core/src/utils/hash.ts, packages/core/src/utils/maskTypename.ts, packages/next-urql/src/__tests__/init-urql-client.spec.ts, packages/next-urql/src/__tests__/with-urql-client.spec.ts
Follow-up to #2611
This refactors multiple parts of the core package, further reducing size (*.min.mjs) by -100B gzip'd down to nice and round 6kB.
**This contains a breaking change (see changeset)**
This pull request finally removes options on the `Client` and only leaves `Client.suspense` around, which we're using internally and may be needed for some other React functionality.
It removes all other options, like `url`, `fetch`, `fetchOptions`, and so on, which are now constant and not modifiable after the `Client` has been created.
This further builds on and encourages use of #2610. (`setContextExchange`). We could further consider deprecating `fetchOptions`, but I see that as too extreme, really.
- Remove `Client.createOperationContext`
- Remove on-client options that are modifiable …
=> chore(core): Refactor core code and remove modifiable Client options

docs/basics/react-preact.md, docs/basics/vue.md
Using the bang operator (!) on non-boolean values can lead to unexpected results. For example, in the case of [this example](../blob/main/docs/basics/react-preact.md#pausing-usequery), using the `pause` option inside the `useQuery` hook, one might set the value of the `from` variable to be `0`. In that case the checks would be inaccurate since `!0 === true`. However, we only expect to pause the query only when `from` or `limit` is nullish. We can replace that condition with a more robust one.
Yes, it's an edge case, but new developers reading this documentation might not be aware of the presence of this bug and might have some unexpected results using this example in their code.
Replaced `!from || !limit` with the more accurate `from === undefined || from === null || limit === undefined …
=> docs: refactored examples that use the logical `!`

.changeset/great-eggs-battle.md, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/offlineExchange.test.ts, exchanges/graphcache/src/offlineExchange.ts, exchanges/graphcache/src/store/data.ts
Resolves #1512 
This enables graph-cache to forward operations while hydration is ongoing, this benefits application in various ways
- they can benefit from synchronous rehydration due to the `ssrExchange`
- does not cause an extra delay for empty caches or missing operations
- remove buffering of operations
=> major(graphcache): stop buffering operations while the cache hydrates

.changeset/stupid-lizards-eat.md, packages/preact-urql/src/hooks/useQuery.ts, packages/preact-urql/src/hooks/useSubscription.ts, packages/react-urql/src/hooks/useQuery.ts, packages/react-urql/src/hooks/useSubscription.ts, packages/svelte-urql/src/mutationStore.ts, packages/svelte-urql/src/queryStore.ts, packages/svelte-urql/src/subscriptionStore.ts, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts
Resolves #2622 
When all keys are nullable we should make the variables nullable as well, this fixes an issue we had with graphql-code-generator when encountering a shape like `{ key: T | null }`
=> fix(bindings): omit variables when all keys are nullable

docs/advanced/authentication.md, docs/advanced/authoring-exchanges.md, docs/advanced/persistence-and-uploads.md, docs/advanced/subscriptions.md, docs/api/auth-exchange.md, docs/api/core.md, docs/api/execute-exchange.md, docs/api/multipart-fetch-exchange.md, docs/api/refocus-exchange.md, docs/api/request-policy-exchange.md, docs/architecture.md, exchanges/refocus/README.md
In `@urql/core` we don't support relative URL's anymore when using the `GET` method because we use the `URL` constructor.
=> docs: remove relative url's

.changeset/afraid-islands-stare.md, package.json, packages/vue-urql/src/useQuery.ts, scripts/rollup/plugins.js, yarn.lock
Resolve #2628
We previously transpiled `let`/`const` to `var` as a standard transpilation by Buble, since it's an extremely safe transpilation step. However, this altered some of the characteristics of the code.
Specifically, it caused an issue (and I'm not sure why TypeScript didn't object) where we forgot to instantiate the variable before calling it inside a closure passed to a function that may be immediately invoked.
Specifically, if our Vue binding's `useQuery` hook was used with its promise-based (suspense) feature, and a result was delivered synchronously it'd be unable to call `sub.unsubscribe`.
I've readded the transpilation step while also fixing the code, since, as I said, it's very safe and simply sidesteps these issues entirely. But I'm refraining from bumping any versions …
=> fix(vue): Fix immediate result by Client causing useQuery to fail

.changeset/quick-crabs-tickle.md, packages/core/src/client.ts
Resolves #2631 
Currently we input `requestPolicy: undefined` from the bindings making it override client-set defaults.
- explicitly set cache-and-network
=> fix(core): prevent inputting undefined overriding defaults

docs/basics/vue.md
Fix docs for return typ of `useQuery()` which is a result object, not a tuple.
=> Fix docs for useQuery() return type with Vue

.changeset/many-worms-bow.md, packages/core/src/client.ts, packages/core/src/utils/maskTypename.test.ts, packages/core/src/utils/maskTypename.ts
=> fix: #2642 root element have no __typename field

.changeset/many-worms-bow.md
Follow up to #2643 
Did not notice we were doing this in a minor rather than a patch
=> fix(workspace): change the changeset to be a patch

.changeset/tame-bananas-bow.md, exchanges/graphcache/src/ast/schema.ts, exchanges/graphcache/src/ast/schemaPredicates.ts
Tiny change to avoid creating a map eagerly for all types, fields, interfaces, and such too early, since some types may never end up being used, and some checks may end up never being run.
=> feat(graphcache): Refactor schema checks to be lazy

.changeset/flat-plants-pull.md, packages/storybook-addon/package.json, packages/storybook-addon/src/exchange.ts
Currently we depend on `react-urql` in the storybook exchange, we should change this to `@urql/core` so we can allow for all integrations.
- rename `urql` import to `@urql/core`
=> fix(storybook): remove dependency on `react-urql`

.changeset/silly-rice-jam.md, exchanges/multipart-fetch/src/multipartFetchExchange.ts
Resolves #2652 
We have a bit of a suboptimal feature in place where we need to construct the URL before we construct the `fetchOptions` else we aren't reverting `GET` when the URL is too long [here](https://github.com/FormidableLabs/urql/blob/main/packages/core/src/internal/fetchOptions.ts#L43)
This PR ensures we first construct the URL as a fix to the issue. Ideally we could do this check in `fetchOptions` as well so we don't rely on mutating context as well as not needing this implicit ordering.
=> fix(multipart): url overflow with GET

.changeset/selfish-wolves-poke.md, packages/preact-urql/src/components/Mutation.ts, packages/preact-urql/src/components/Query.ts, packages/react-urql/src/components/Mutation.ts, packages/react-urql/src/components/Query.ts
Resolves #2662 
We hadn't updated the Variables for the render-props components, this equalizes them to their hook equivalent.
Follow up to #2607
=> fix(react-preact): variable types for render-props components

.changeset/wet-nails-develop.md, packages/core/src/utils/operation.ts
Related to https://github.com/pmndrs/jotai/issues/1384
Fixes the `makeOperation` types to adhere to the changes made in #2607
=> fix(core): variable types for makeOperation

.changeset/tame-crews-grab.md, packages/react-urql/src/hooks/useSubscription.ts
Resolves #2648 
When we changes `variables` `onEnd` seems to fire later than us establishing the new connection, this means we set `fetching` to a truthy value and then switch it off as we assume that we aren't fetching anymore.
Now when a subscription ends we check whether there is a new source already and base our fetching state off that, [sandbox](https://codesandbox.io/s/kind-currying-8v8yvw?file=/src/components/Messages.js)
CC @elias-pap
- rely on `source` to flip `fetching` state
=> fix(react): set `fetching` to the lack or presence of `source`

docs/comparison.md
Updated to match the [the redirect](https://github.com/FormidableLabs/urql/blob/53dec134328be48e25ba78e54b21acfe8df5cb42/packages/site/static.config.js#L84-L87) — also added the #anchor for the most pertinent section for the link.
=> Fix a docs link in comparison.md

packages/storybook-addon/README.md
The README for `@urql/storybook-addon` uses the `getQueryName` function, but urql does not seem to export it.
For clarity, I have replaced it with the `getOperationName` function that urql exports.
- README of `@urql/storybook-addon`
=> docs(storybook): fix wrong function name

docs/basics/svelte.md
Had a leftover from the old API
=> fix(docs): remove `query` ref from svelte docs

.changeset/beige-paws-draw.md, packages/core/src/exchanges/ssr.ts
Resolve #2689
Resolve #2588
This fixes a not so subtle bug which caused all `network-only` operations to be dropped.
Essentially, this prevented `staleWhileRevalidate` from working on the `ssrExchange` itself, but also prevented other `network-only` operations from being forwarded to the next exchange at all, which caused no operation from being sent when this policy was used.
- Add missing `network-only` exception to forwarded operations
=> fix(core): Fix ssrExchange dropping network-only operations

docs/comparison.md
Hi there! This PR contains a small update to the comparison chart to reflect that Apollo Client now supports the `@defer` directive as of v3.7.0, though `@stream` is not yet supported ([release notes](https://github.com/apollographql/apollo-client/releases/tag/v3.7.0)).
Happy to format it differently - I went with ✅/🛑 to communicate both statuses since they're contained in a single cell.
This is a docs-only change.
=> chore(docs): update comparison chart with Apollo Client defer support

.changeset/stupid-rules-mix.md, exchanges/graphcache/src/offlineExchange.test.ts, exchanges/graphcache/src/offlineExchange.ts, packages/core/src/client.ts, packages/core/src/types.ts
Resolve #2726
While we don't imply or implicitly disallow cloning `OperationContext`, and it's definitely not expected and encouraged, if it's done, it can have some unexpected consequences.
Specifically, if an `OperationContext` is deeply cloned rather than spread, then `OperationContext._identity` is destroyed. This leads to the `Client` not being able to find the right mutation result for a given operation with an unknown `_identity`.
Previously, we assigned identities with an empty array (`[]`). There are alternatives, of course, like `{}`, symbols, functions, etc. But all may be instances that will be swapped out by users.
Instead, we now assign a numeric ID to the field, which is marked as an opaque type in TypeScript. This is a rolling-over 32-bit counter, which is sufficient to …
=> fix(core): Fix OperationContext._identity not allowing operation contexts to be deeply cloned

.changeset/good-kids-sleep.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts
Resolve #2701
This prevents us from using the formatted GraphQL document, as per the output of `@urql/core`'s `formatDocument`, in Graphcache's later stage to query data against the cache. This is problematic because it changes the shape of data and hence disallows us to preserve referential equality of any given data.
Instead, we now use existing data structures to retrieve the original operation before it's been forwarded to the next exchanges.
- Retrieve the original operation when writing a query result to the cache
=> fix(graphcache): Use original operation document when updating the cache

.changeset/lovely-monkeys-wink.md, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/store/store.test.ts
Resolve #2701
(NOTE: This is a missing piece that's also required to fix a new optimistic mutation case)
This adds a missing piece of logic that we forgot to update in #2616, which allows optimistic mutations to not only be based on the field name (not alias) and nested functions, but also to return partial results.
Previously to this fix, partial mutation updates would cause cache misses by deleting cache values instead of skipping them.
- Skip `undefined` fields on optimistic mutation results
=> fix(graphcache): Fix partial optimistic mutation results

.changeset/twelve-beds-appear.md, exchanges/graphcache/src/cacheExchange.ts
Resolve #2701
This fixes a small typo that causes the results cache to be updated with the API result rather than the updated cache result
- Fix typo
=> fix(graphcache): Fix typo in results cache

.changeset/smart-pears-sing.md, exchanges/graphcache/src/cacheExchange.ts
**NOTE: This fix isn't fully verified yet and the code needs to be verified to not break any existing behaviour.**
See prior approach in #2731.
When an operation is read from the cache, if we encounter a cache miss then a network request is sent, which subsequently updates the cache.
However, suppose an operation has several dependencies on the cache-missed operation. If any of the dependent operations then also experience a cache-miss, this will then subsequently retrigger the original operation as well. This is because any dependencies between operations will always be bi-directional by definition.
The easiest approach to solve this issue is to prevent direct cycles, meaning, if an operation triggers another, then we disallow the subsequent operation to trigger the first again, hence …
=> fix(graphcache): Prevent refetch cycles when handling cache misses

.github/actions/yarn-run/action.yml, .github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/site.yml, package.json, yarn.lock
In our action-runs we are seeing a lot of warnings [example](https://github.com/FormidableLabs/urql/actions/runs/3248814934) this addresses all the warnings by:
- bumping to Node 16
- removing `set-output`
- bumping the `@actions/*` packages
Feels good being free of warnings https://github.com/FormidableLabs/urql/actions/runs/3283099992
=> chore(workspace): update to node 16 and remove deprecated set-output

.changeset/quiet-turkeys-brake.md, scripts/babel/transform-debug-target.js
Resolves #2690 
When leveraging `transform-debug-target`  we fill in the `source` everywhere, this does not work for the `compose.ts` file as it's not an exchange. The bug is caused by us taking the latest transformed exchange and pushing `source: name` into the object invocation, resulting in [this](https://www.runpkg.com/?@urql/core@3.0.4/dist/urql-core.js#689). This PR effectively excludes `compose.ts` and hence fixes our future builds.
=> fix(core): build debug target correctly

.changeset/flat-feet-look.md, exchanges/graphcache/src/cacheExchange.ts
Currently we initiate loop protection for all operations, this should actually only happen for queries reexecuting one another
=> fix(graphcache): case where a mutation would also be counted in the loop-protection

.changeset/lucky-terms-greet.md, exchanges/graphcache/src/store/data.test.ts, exchanges/graphcache/src/store/data.ts
Resolve #2766
Previously we included subscriptions in the logic we use to layer when a result has more results coming in due to `@stream` or `@defer`. We forgot to port this line over so when we are dealing with a result that isn't optimistic but comes from a subscription we erroneously removed the previous to-be squashed layer.
=> fix(graphcache): avoid removing subscription layers

.changeset/pink-melons-joke.md, exchanges/graphcache/src/cacheExchange.ts
Resolves #2768 
When we update the cache we aren't writing to the `operations` map anymore because we moved this setter from the `updateDependencies` loop to the relevant functions in https://github.com/FormidableLabs/urql/pull/2736.
=> fix(graphcache): set operation when updating the cache with a result

.changeset/healthy-hornets-warn.md, exchanges/execute/src/execute.ts
When using useSubscription, I expected that when the teardown function runs in exchange execute, the iterator would also end. But it made one call to next() and then ended the iterator. By adding iterator.return() to the teardown function, the iterator will not make any extra call to next() when the subscription ends.
- Call iterator.return() when teardown function runs in exhange execute
=> fix(execute): end iterator on teardown

README.md, docs/advanced/server-side-rendering.md, exchanges/context/README.md, exchanges/execute/README.md, exchanges/graphcache/README.md, exchanges/graphcache/help.md, exchanges/graphcache/package.json, packages/preact-urql/README.md, packages/site/src/constants.js, packages/site/src/screens/home/hero.js, packages/storybook-addon/package.json, packages/vue-urql/README.md, scripts/changesets/changelog.js
We had a few resdiual maintenance status, invalid links, ... This also changes a few things about the main readme, it adds Vue, uses `@urql/core` for the DL number and removes `react installation`
=> chore: cleanup readmes for the new repo

exchanges/auth/src/index.ts, exchanges/context/src/index.ts, exchanges/execute/src/index.ts, exchanges/retry/src/index.ts, packages/core/src/types.ts, packages/vue-urql/src/index.ts, tsconfig.json
This is simply a small change to give ourselves more options when bundling in the future and avoid accidental issues with unresolveable modules.
- Enable `isolatedModules: true` in root `tsconfig.json`
- Refactor various exports to use isolated modules syntax
=> chore(workspace): Enable TypeScript's isolatedModules compiler option

.changeset/cuddly-needles-work.md, exchanges/graphcache/e2e-tests/query.spec.tsx, exchanges/graphcache/src/cacheExchange.ts
Resolve #2830 
When we have a partial result we should stop the query from re-fetching, this was a case that we hadn't caught yet. The issue here being that we will also eat the error as we aren't caching those. Basically the query will complete and we will get two results from cache without the errors rather than the plain result with an error added on top.
=> fix(graphcache): fix loop bug when schema is present

.changeset/beige-fishes-relate.md, packages/next-urql/src/init-urql-client.ts
Currently, `initUrqlClient` cannot be used in Nextjs server components because it uses `createContext`. Per [a discussion](https://github.com/urql-graphql/urql/discussions/2829#discussioncomment-4234974) with @JoviDeCroock the other day, the solution to this seems to be to import from @urql/core instead of urql.
The only change is changing the import for `init-urql-client.ts` from urql to @urql/core. This should not be a breaking change.
=> fix(next-urql): Change import for init-urql-client to @urql/core to prevent it from using createContext

.changeset/swift-fireants-itch.md, package.json, packages/core/package.json, pnpm-lock.yaml
Resolves #2355
Fixes a memory leak in Node.js, which was caused by `takeUntil` in the `fetchExchange` not actually terminating an incoming notifier source.
=> fix(core): Fix Node.js fetch leak due to missing takeUntil cleanup

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/site.yml
We set the output to `pnpm_cache_dir` but were erroneously referencing `dir`
=> fix(workspace): set cache dir correctly

scripts/rollup/settings.mjs
This is a tiny issue that was introduced when adding missing dependencies in `@urql/exchange-graphcache`. Our non-ESM build mode is activated when React is installed, however, instead, we shouldn't check `devDependencies` for that, since currently the E2E tests require us to have it installed in `@urql/exchange-graphcache`.
=> chore(workspace): Fix detection of non-ESM builds

.changeset/poor-items-shake.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/store/data.ts
Resolve #2853
This fixes a deadlock that could occur in the layers of Graphcache, when a deferred layer (subscriptions or otherwise `hasNext` layers) would be moved past previously optimistic layers (like mutations). In such cases, it would become impossible for preceding layers (i.e. mutations) to ever squash and move "out of the way" causing a deadlock that'd make it impossible for the deferred layer's data to show up when the two layers had overlaps.
Instead, we now will try to clear out deferred layers more aggressively. This means that we will squash its data even when it's deferred, when data is written.
Furthermore, we then move the layer from its current position (or recreate it) when it's re-registered, i.e. when a new message/update comes in for the deferred layer.
This should …
=> fix(graphcache): Fix deadlocked layers between deferred and optimistic layers

.changeset/quiet-mugs-travel.md, exchanges/multipart-fetch/src/__snapshots__/multipartFetchExchange.test.ts.snap, packages/core/src/exchanges/__snapshots__/fetch.test.ts.snap, packages/core/src/exchanges/__snapshots__/subscription.test.ts.snap, packages/core/src/exchanges/subscription.test.ts, packages/core/src/exchanges/subscription.ts, packages/core/src/gql.test.ts, packages/core/src/internal/__snapshots__/fetchSource.test.ts.snap, packages/core/src/internal/fetchOptions.ts, packages/core/src/utils/hash.test.ts, packages/core/src/utils/hash.ts, packages/core/src/utils/request.test.ts, packages/core/src/utils/request.ts, packages/svelte-urql/src/mutationStore.test.ts, packages/svelte-urql/src/queryStore.test.ts, packages/svelte-urql/src/subscriptionStore.test.ts
Resolves #2787
This changes the internals of `@urql/core` to allow us to reuse `stringifyDocument` in `fetchOptions` and other places, to ensure that printing is memoised whenever possible — including for `formatDocument` outputs.
This means that we had to adjust our hashing slightly to account for the different outputs; that said, sanitisation will still be applied to `stringifyDocument` inputs. However, we will no longer reuse `loc.source` strings when they haven't been printed by `@urql/core`.
- Replace `phash` hashing function and create opaque type for clarity
- Refactor `request.ts`' `stringifyDocument` and hashing
- Reuse `stringifyDocument` in `subscriptionExchange` and `fetchOptions`
- Update document sanitisation to only remove comments
- Update hashing to add the operation name …
=> feat(core): Reuse stringifyDocument and cached prints across @urql/core

.changeset/big-melons-leave.md, packages/core/src/exchanges/ssr.test.ts, packages/core/src/exchanges/ssr.ts
Discovered in https://github.com/urql-graphql/urql/discussions/2867 when our ssr-exchange fufills a cache hit we incorrectly mark it as a cache-miss.
=> fix(core): add cache ssr hit

.changeset/large-eggs-cough.md, packages/core/src/utils/request.test.ts, packages/core/src/utils/request.ts, packages/core/src/utils/typenames.ts, packages/svelte-urql/src/mutationStore.test.ts
Related to #2869 reproduces the issue.
[this](https://github.com/urql-graphql/urql/blob/main/packages/core/src/utils/request.ts#L43-L53) looks to be the problem, when we use `createRequest` we fill in `gql` as the source name and don't update the printed string when looping over it with `formatDocument`. When we use `gql` the name will be `graphql request` hence not hitting this clause.
The thing concerning me here is if people would be implementing local-only exchanges whether that would mess with i.e. them removing a field when seeing `@local`
=> fix(core): Fix regression causing stringifyDocument to not reprint after formatDocument

.changeset/odd-rockets-behave.md, exchanges/graphcache/src/cacheExchange.ts
Resolve #2835
This fixes Graphcache blocking legitimate reexecutions triggerd by the UI. These reexecutions could be triggered due to the previously introduced looping protection #2737.
When an operation is torn down and reactivated without any other network request inbetween, then Graphcache wouldn't clean up the operations that'd be blocked from refetching. This meant that it'd erroneously block a legitimate operation triggered by the UI.
The protection is meant to only trigger requests that'd potentially infinitely trigger requests, i.e. non-`network-only` operations triggered by cache misses.
This has been addressed by adding a missing clean up call in reaction to teardowns.
- Add missing `reexecutingOperations` clean up to `teardown` handler
- Remove typings/build testing line that …
=> fix(graphcache): Fix blocking of legitimate reexecutions after teardowns

docs/basics/typescript-integration.md
Resolves #2883
Corrects to our array destructuring syntax
=> fix(docs): correct TS `useQuery` example

.changeset/gentle-ligers-design.md, exchanges/graphcache/src/store/store.ts
This PR will correct error message for https://formidable.com/open-source/urql/docs/graphcache/errors/#19-cant-generate-a-key-for-invalidate
current
```
CombinedError: [Network] [object Object]`.
```
expected
```
CombinedError: [Network] Can't generate a key for invalidate(...).
```
`@urql/exchange-graphcache`
=> fix(graphcache): Patch message for `(19) Can't generate a key for invalidate(...)` error

.changeset/flat-lions-talk.md, exchanges/graphcache/src/operations/shared.ts
This PR will fix warning message for https://formidable.com/open-source/urql/docs/graphcache/errors/#16-heuristic-fragment-matching
current
```
Since GraphQL allows for interfaces `???` may be aninterface.
```
expected
```
Since GraphQL allows for interfaces `???` may be an interface.
```
`@urql/exchange-graphcache`
=> fix(graphcache): Patch message for `(16) Heuristic Fragment Matching`

packages/next-urql/README.md
Using the correct name "Next.js" instead of "NextJS".
=> docs: using correct name for Next.js

.changeset/rare-panthers-sit.md, packages/next-urql/src/with-urql-client.ts
Resolves #2892
Closes #2574
This adds an empty `pageProps` object, the reason behind putting it before the spread is that if we have some HOC wrapping `next-urql` we don't want to override the existing pageProps.
=> fix(next): add empty pageprops object

docs/graphcache/local-resolvers.md
Just noticed it whilst reading docs
Just noticed a typo in the docs
Literally just correcting the spelling of a word
=> Fix typo in local-resolvers.md

.changeset/fast-fishes-destroy.md, exchanges/graphcache/src/offlineExchange.test.ts, exchanges/graphcache/src/offlineExchange.ts
It's important that onOnline isn't established until after mutations are read from storage and processed by flushQueue. If the storage adapter's onOnline implementation calls flushQueue in the same task, then the storage will be wiped before it is read from, and all mutations that were in the metadata storage will be deleted before they can be read and processed.
Our team ran into this in our react-native project. The library we use for listening to network information state changes immediately invokes the event listener we install on it. Therefore, it's calling flushQueue before urql's offlineExchange even attempts to read from metadata storage.
- Change how onOnline is set up in offlineExchange. Wait to install the onOnline callback on the StorageAdapter until after the mutations have …
=> fix(graphcache): Fix onOnline data loss bug in offlineExchange

docs/basics/typescript-integration.md
Hello :)
Links to see the VueJS example for the typescript codegen does not work anymore.
Just update links.
Thanks
=> docs: Update links in typescript-integration

docs/graphcache/cache-updates.md
Hello :)
There is a little typo in an optimistic update in a code example
Just update param name.
Thanks
=> docs: Fix typo in cache-updates doc about optimistic updates

docs/api/core.md
Updated type of OperationContext's preferGetMethod to be the same as Client's preferGetMethod.
Docs only.
=> docs(core): Update type of OperationContext's preferGetMethod

package.json, pnpm-lock.yaml
Saw this passing by, vitest has been working hard on performance so wanted to see the impact on the urql repo.
Before: `Duration  83.82s (transform 1.28s, setup 861ms, collect 14.04s, tests 7.64s)`
After: ` Duration  62.48s (transform 1.14s, setup 780ms, collect 11.40s, tests 7.21s)`
=> chore(deps): update vitest

docs/advanced/subscriptions.md
See: https://github.com/urql-graphql/urql/discussions/2984
`graphql-ws` doesn't seem to filter the input payload anymore (or never has?) which causes some GraphQL APIs to obviously fail on the extra properties we're passing in our operation abstraction.
=> docs(core): Update subscriptions instructions for graphql-ws

.changeset/wet-buses-hide.md, docs/graphcache/errors.md, docs/graphcache/local-resolvers.md, docs/graphcache/normalized-caching.md, exchanges/graphcache/src/helpers/help.ts, exchanges/graphcache/src/store/data.ts, exchanges/graphcache/src/store/store.test.ts
Resolves #2977 
This adds the missing invariants to `data.ts` that prevent cache writes during read/query operations, since users are not allowed to modify the cache during read operations.
- Add dev-only invariant to prevent writes inside cache reads
- Exclude `squashLayer` operations from this restriction
- Update tests accordingly
=> fix(graphcache): Prevent cache writes during query operations

.changeset/afraid-gorillas-hope.md, exchanges/graphcache/e2e-tests/query.spec.tsx, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/offlineExchange.test.ts, exchanges/graphcache/src/store/__snapshots__/store.test.ts.snap
Resolves #2937
This fixes `stale: true` not being set on partial responses that had been blocked by the looping protection. Even if we detect that a partial response may lead to a loop, the `stale` flag should still be set to indicate that the response is incomplete/partial, as per the documentation.
This is a regression from #2831
- Add `result.stale` for partial results, even if the reexecution is blockd
=> fix(graphcache): Fix regressed stale flag for looping protection

.changeset/thirty-pears-lay.md, docs/graphcache/errors.md, exchanges/graphcache/src/ast/schemaPredicates.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/store/__snapshots__/store.test.ts.snap, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/test-utils/examples-1.test.ts, exchanges/graphcache/src/types.ts
Resolves #2977 
This allows arbitrary `updates` configurations to react to any type and not just `Mutation` and `Subscription`.
Users will now be able to write updaters that react to arbitrary entity field updates. Since this is now permissible, but a very nieche use-case, we currently don't foresee documenting this just yet. It's useful when a schema isn't built to touch on related data invalidating, and when the UI can't compensate for this, but this can also sometimes be a footgun.
**Important Note:** Due to an implementation mistake in the past, we never used `updates[rootName]` and instead normalised `updates.Mutation` and `updates.Subscription` according to the `schema` (partial or not) that is passed to the `cacheExchange`.
Instead, we now expect that `updates[rootName]` is passed …
=> feat(graphcache): Allow arbitrary types in updates config

.changeset/silent-emus-brake.md, packages/core/src/exchanges/__snapshots__/subscription.test.ts.snap, packages/core/src/exchanges/subscription.ts, packages/core/src/utils/result.ts
Not all subscription transports have a built-in way of deduplicating subscriptions, since this may not be desireable. However, the presence of this in some transports has previously masked this issue.
The `dedupExchange` can prevent multiple identical operations. However, it backs off when a result comes in that has `hasNext === false` set.
The issue here is that `subscriptionExchange`s need to set `hasNext` to `true` by default for subscription operations to ensure that no duplicate subscriptions are triggered
- Set default `hasNext` field to `true` for subscriptions in `makeResult`
=> fix(core): Set default hasNext for subscription results

.changeset/stupid-cobras-clap.md, exchanges/auth/src/authExchange.test.ts, exchanges/auth/src/authExchange.ts
When operations are waiting for `authPromise` to resolve, i.e. they're not queued but instead are waiting for the authentication update/refresh to resolve, `willAuthError` will actually _not_ be called, even if it's provided.
This can lead to an easy mistake, where the authentication state may have been rehydrated (on startup), but is never checked to be valid.
We now queue operations that are waiting for the promise like we do for failed operations, which simplifies the logic a little, and make sure to call `willAuthError` on them again.
- Call `willAuthError` on queued retry operations
- Reuse queue for waiting operations
- Update how `mutate` bypasses the authentication logic
=> fix(auth): Fix willAuthError not being called on waiting operations

docs/advanced/subscriptions.md
first crack at #2992 
Updates svelte subscription docs for clarity and to remove obsolete examples.
- removes the language around `handleSubscription` in svelte subscriptionStore example
- adds reference to second param for subscription handler on `subscriptionStore`
- corrects bad link to additional reading
- corrects code example in svelte subscription example to include data object
=> docs(svelte): first draft of clarifying subscription language for svelte

.changeset/clean-tables-exercise.md, packages/vue-urql/package.json, packages/vue-urql/src/useClient.test.ts, packages/vue-urql/src/useClient.ts, pnpm-lock.yaml
Resolves #2879
This change allows `provideClient` to be immediately effective and usable in the same component, which allows for definitions like the following:
```js
import { useQuery, provideClient, createClient } from '@urql/vue';
const Component = {
setup() {
provideClient(createClient({ url: 'URI' }));
const { data } = useQuery({
query: gql`
query Customers {
customers {
id
name
}
}
`,
});
},
};
```
- Add `WeakMap` of component instances to clients provided
=> fix(vue): Allow a client provided in the same component to be used there

.changeset/perfect-lobsters-kiss.md, docs/advanced/authentication.md, docs/api/auth-exchange.md, exchanges/auth/README.md, exchanges/auth/src/authExchange.test.ts, exchanges/auth/src/authExchange.ts, exchanges/auth/src/index.ts
Resolves #2815
**This is a breaking change, which updates the `authExchange` API.**
This PR eliminates the need for an `authState` (i.e. the authentication state) to be kept with the `authExchange`, and moves it into the responsibility of the user.
It also eliminates `getAuth`'s "double duty" of being called, both, to initialize the authentication state, and to refresh the authentication state after an authentication error.
The `authExchange` now accepts an initializer function, which is an async function (or a function returning a promise). This function is user-defined and will receive a utilities object and _must_ return an authentication configuration object.
This configuration object is unchanged but now contains `refreshAuth` rather than `getAuth`. Several arguments that its …
=> refactor(auth): Implement new initializer function API

.changeset/popular-carpets-compare.md, docs/graphcache/offline.md, exchanges/graphcache/src/offlineExchange.ts
When using the offline plugin I think it'd make sense to simplify the isOffline check to apply to all network errors.
Simplify the isOffline check to apply for all network errors.
=> feat(graphcache): Add isOfflineError option to offlineExchange

.changeset/slimy-shirts-bow.md, .changeset/tricky-ears-add.md, packages/core/src/types.ts, packages/preact-urql/src/hooks/useQuery.ts, packages/preact-urql/src/hooks/useSubscription.ts, packages/react-urql/src/hooks/useQuery.ts, packages/react-urql/src/hooks/useSubscription.ts, packages/svelte-urql/src/mutationStore.ts, packages/svelte-urql/src/queryStore.ts, packages/svelte-urql/src/subscriptionStore.ts, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts
Resolves #2668
Previously, we had a couple of cases that wouldn't allow us to correctly identify when the `variables` input should be optional, e.g. allowing for:
```ts
import { useQuery, TypedDocumentNode } from 'urql';
const x: TypedDocumentNode<{ data: null }, { test: string | null }> = {} as any;
useQuery({ query: x });
```
Additionally, it wasn't always easily possible to proxy generic inputs to our hooks and bindings, e.g. allowing for:
```ts
import { useQuery, TypedDocumentNode, AnyVariables } from 'urql';
export function wrapper<Data, Variables extends AnyVariables = AnyVariables>(
query: TypedDocumentNode<Data, Variables>,
variables: Variables,
) {
return useQuery({ query, variables });
}
```
This is now resolved and to prevent future mistakes a `GraphQLRequestParams` utility …
=> fix(core/bindings): Fix conditional/optional variables type based on TypedDocumentNode generic

.changeset/stupid-cherries-join.md, exchanges/persisted-fetch/src/__snapshots__/persistedFetchExchange.test.ts.snap, exchanges/populate/src/populateExchange.test.ts, exchanges/populate/src/populateExchange.ts, packages/react-urql/src/hooks/__snapshots__/useMutation.test.tsx.snap, packages/react-urql/src/hooks/__snapshots__/useQuery.test.tsx.snap, packages/react-urql/src/hooks/__snapshots__/useSubscription.test.tsx.snap
This introduces a `maxDepth` and `skipType` (naming suggestion welcome) option to the `populateExchange`, this is mainly meant to avoid having long running applications have infinitely deep selection-sets due to seeing a lot of queries and a root-type being mutated.
=> feat(populate): add way to limit depth and skip certain types from that depth-count

.changeset/dry-islands-double.md, packages/core/src/types.ts
Resolves #3026
Fix generated empty `Variables` type as passed to generics, that outputs a type of `{ [var: string]: never; }`.
A legacy/unsupported version of `typescript-urql`, which wraps `urql`'s React hooks, generates
empty variables types as the following code snippet, which is not detected:
```ts
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Variables = Exact<{ [key: string]: never }>;
```
**NOTE:** We cannot guarantee that this actually fixes `@graphql-codegen/typescript-urql`, which will going forward be unsupported. Generally, we choose not to create test harnesses for outside type generators like these, until we'd have our own type/code generator.
We cannot guarantee that types of hook/wrapper generators don't break, and instead recommend and …
=> fix(core): Fix legacy GCG generated Variables types

.github/workflows/site.yml
Left the build command intact as we need that to test whether everything is okay but commented out deploy for now as the staging token is seen as invalid.
=> chore(workspace): temp disable staging docs deploy, staging token is broken

.changeset/early-crabs-draw.md, packages/core/src/internal/fetchOptions.ts
Follow up to https://github.com/urql-graphql/urql/pull/3007
In React-Native-Fetch streaming isn't supported meaning that the inclusion of `multipart/mixed` can lead to errors. We move it to the end of the Accept headers to avoid running into this bug. This was reported on Discord.
Relates to https://github.com/facebook/react-native/issues/27741
=> fix(core): move `multipart/mixed` to end of accept headers

exchanges/request-policy/src/requestPolicyExchange.ts
This adds inline TSDoc annotations for the request-policy exchange, this should make adopting it a bit easier. I am considering adding a changeset here as the frequency of changes to this exchange are pretty low.
=> chore(request-policy): add TSDoc for the requestPolicyExchange

exchanges/graphcache/default-storage/package.json, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/helpers/operation.ts, packages/core/src/gql.ts, packages/core/src/types.ts, packages/core/src/utils/hash.ts, packages/core/src/utils/request.ts, packages/core/src/utils/result.ts, packages/core/src/utils/streamUtils.ts, packages/core/src/utils/stringifyVariables.ts, scripts/babel/transform-debug-target.mjs
Follow-up to #3035
This further attempts to reduce the size and clean up some implementations in `@urql/core`.
`6.2kB -> 6.06kB` gzip+min
- Reformat `phash`
- Reformat `hashDocument` and `createRequest`
- Remove `OperationContext.meta` in production by compiling away `addMetadata` calls
- Reformat and remove redundant `'incremental'` check in `makeResult`
- Reformat legacy fallback in `mergeResultPatch`
- Reformat `withPromise` and rewrite with `wonka` update (**NOTE:** This should work due to wonka's `toPromise` fix)
- Reformat `gql` implementation
- Reformat `stringify` in `stringifyVariables`
=> chore(core): Reformat some code to reduce @urql/core size

.changeset/fifty-jeans-invite.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts
Before we send out the mutation we filter the variables so extraneous variables don't cause an issue on the server. However this makes it so that we don't restore them afterwards as they are not part of the `operations` Map. This gives us a way to restore variables on mutations.
Works now: https://codesandbox.io/s/empty-water-6tm6yy?file=/src/index.js
=> fix(graphcache): fix restoring variables on mutation operations

.changeset/real-donkeys-act.md, exchanges/execute/src/execute.test.ts, exchanges/graphcache/src/offlineExchange.test.ts, exchanges/multipart-fetch/src/multipartFetchExchange.test.ts, exchanges/persisted-fetch/src/persistedFetchExchange.test.ts, packages/core/src/exchanges/fetch.test.ts, packages/core/src/internal/__snapshots__/fetchSource.test.ts.snap, packages/core/src/internal/fetchSource.test.ts, packages/core/src/internal/fetchSource.ts, packages/svelte-urql/src/mutationStore.test.ts, packages/svelte-urql/src/queryStore.test.ts, packages/svelte-urql/src/subscriptionStore.test.ts, pnpm-lock.yaml
This builds on `fix/node-memory-leak-fetch-source` to finally reimplement the fetch source implementation as an async generator, wrapped in a `fromAsyncIterable` conversion from `wonka`.
This also simplifies some of the existing logic, as per how `meros` works, and how Incremental Delivery is defined. For instance, we now assume that each chunk is a JSON blob instead of checking headers, which we aren't using or merging anyway.
`6.06kB -> 5.89 kB` min+gzip
- Reimplement `makeFetchSource` with async generator
- Remove headers regex check
=> feat(core): Reimplement fetch source as async generator

.changeset/proud-buses-change.md, packages/core/src/internal/fetchOptions.ts, packages/core/src/internal/fetchSource.test.ts, packages/core/src/internal/fetchSource.ts
This implements support for `text/event-stream` responses, as per GraphQL SSE.
We've used GraphQL Yoga's "push" mechanism as a general template for what this must look like: https://github.com/dotansimha/graphql-yoga/blob/d2060c1/packages/graphql-yoga/src/plugins/resultProcessor/push.ts
And this generally adheres to the GraphQL SSE protocol: https://github.com/enisdenjo/graphql-sse/blob/master/PROTOCOL.md
The current implementation found it unnecessary to respect `event:` type fields, instead it will just loosely look at `data:` fields and attempt to parse them.
We generally regard this as an alternative to `multipart/mixed` responses, and the protocol is loosely supported alongside it, while basically being an alternative to `text/event-stream`.
Currently, it's unclear to us when which …
=> feat(core): Implement GraphQL SSE Response Support

.changeset/brave-sloths-bathe.md, exchanges/persisted-fetch/src/persistedFetchExchange.ts, exchanges/persisted-fetch/src/sha256.ts
This is a small refactor of `persistedFetchExchange` to save a couple of bytes.
Nothing else has changed and this doesn't address the `subscriptionExchange` just yet.
- Refactor `sha256.ts` to save on size
- Use `padLeft` in `sha256` utility
- Minify body logic in `persistedFetchExchange`
- Strip no-op `onPush` in production
=> chore(persisted): Refactor sha256 utilities and persistedFetchExchange

.changeset/fuzzy-baboons-add.md, .changeset/poor-pumpkins-greet.md, packages/core/src/exchanges/subscription.ts, packages/core/src/utils/result.ts
Add missing `errors` patching into `mergeResultPatch` and support incremental results in `subscriptionExchange`.
This should have no breaking changes, but only adds incremental result support to third-party exchanges.
- Add `errors` merging to non-incremental result updates
- Add incremental result support to `subscriptionExchange`
=> fix(core): Add missing error patching and support incremental results in subscriptionExchange

.changeset/clever-plants-greet.md, .changeset/slow-glasses-attend.md, docs/advanced/subscriptions.md, packages/core/src/exchanges/subscription.test.ts, packages/core/src/exchanges/subscription.ts, packages/core/src/internal/fetchOptions.ts, packages/core/src/types.ts, packages/core/src/utils/operation.ts, packages/core/src/utils/request.ts
This updates the `GraphQLRequest` type to contain an `extensions` field. This field will currently remain unavailable to bindings/UI code, but can be used to interact with spec extensions in exchanges.
Specifically, this enables us to replace `persistedFetchExchange` with a `persitedExchange` in the future that only interacts with the rest of the exchange pipeline by modifying `Operation.extensions` without triggering a `fetch` request.
The `subscriptionExchange` has been updated accordingly to receive the entire `FetchBody` type, to bring it inline with the default `fetchExchange` and `@urql/core/internal` utilities.
This is a **breaking change** as the properties `key` and `context` are now missing in the first argument that `forwardSubscription` receives. To compensate, the exchange …
=> feat(core): Support GraphQLRequest.extensions and update subscriptionExchange

.changeset/polite-penguins-notice.md, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/offlineExchange.test.ts, packages/core/src/exchanges/ssr.test.ts, packages/core/src/exchanges/ssr.ts
Ensures that the `ssrExchange` and Graphcache's `cacheExchange` don't accidentally remove `hasNext` (or `stale`) flags.
- Add `hasNext` passthrough to Graphcache
- Add `hasNext` passthrough to `ssrExchange`
=> fix(core/graphcache): Add missing hasNext/stale flags to cached results

.changeset/four-boxes-impress.md, exchanges/auth/src/authExchange.test.ts, exchanges/context/src/context.test.ts, exchanges/execute/src/execute.test.ts, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/offlineExchange.test.ts, exchanges/multipart-fetch/src/__snapshots__/multipartFetchExchange.test.ts.snap, exchanges/refocus/src/refocusExchange.test.ts, exchanges/request-policy/src/requestPolicyExchange.test.ts, packages/core/src/client.test.ts, packages/core/src/exchanges/__snapshots__/fetch.test.ts.snap, packages/core/src/exchanges/__snapshots__/subscription.test.ts.snap, packages/core/src/exchanges/cache.ts, packages/core/src/exchanges/map.test.ts, packages/core/src/exchanges/ssr.test.ts, packages/core/src/internal/__snapshots__/fetchSource.test.ts.snap, packages/core/src/test-utils/samples.ts, packages/core/src/types.ts, packages/core/src/utils/result.test.ts, packages/core/src/utils/result.ts, packages/react-urql/src/test-utils/ssr.test.tsx, packages/svelte-urql/src/common.ts
Since `OperationResult.hasNext` is now important to determine whether operations should be deduplicated (as before, to be fair), and `OperationResult.stale` is important for `toPromise` to find the right result, it's a little dangerous not to have them be required.
Hence, the thinking here is to make them required and to ensure that for `@defer`/`@stream` we won't run into cases where those never reset to `false` or where deferred/streamed responses are duplicated.
- Update `hasNext` and `stale` to be required
- Update tests and types
=> refactor(core): Refactor hasNext/stale on OperationResult to be required

.changeset/quick-seahorses-cross.md, .changeset/young-lamps-help.md, exchanges/execute/src/execute.test.ts, exchanges/execute/src/execute.ts, packages/core/src/index.ts, packages/core/src/utils/request.ts
I don't think there's a good reason for us to expose this, as we also don't expose `getOperationType`, et al. I think this went a step too far and removing it now with a breaking change is likely appropriate.
- Remove `getOperationName` export from `@urql/core`
- Replace `getOperationName` implementation on `@urql/exchange-execute`
- Fix `getOperationName` returning first name rather than the first operation's name
=> refactor(core): Remove getOperationName helper from @urql/core

.changeset/wise-hairs-pump.md, exchanges/context/src/context.ts, exchanges/execute/src/execute.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/default-storage/index.ts, exchanges/graphcache/src/extras/relayPagination.ts, exchanges/graphcache/src/extras/simplePagination.ts, exchanges/graphcache/src/offlineExchange.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/types.ts, exchanges/persisted/src/persistedExchange.ts, exchanges/populate/src/populateExchange.ts, exchanges/refocus/src/refocusExchange.ts, exchanges/request-policy/src/requestPolicyExchange.ts, exchanges/retry/src/retryExchange.ts, packages/core/src/client.ts, packages/core/src/exchanges/cache.ts, packages/core/src/types.ts, packages/core/src/utils/error.ts
Follow-up to #2962
**Note:** This only adds TSDocs to `exchanges/*` not `packages/*`.
This adds inline TSDocs to all of our exchange packages, including Graphcache, which should make learning and using these APIs, in the presence of an editor with TS language server support, much easier.
=> docs(exchanges): Add TSDocs to all exchanges

packages/core/src/exchanges/fetch.test.ts, packages/core/src/internal/fetchSource.test.ts, packages/core/src/internal/fetchSource.ts
Follow-up to #3043
The async generator implementation has regressed on the previous one since it doesn't include a delay that respects immediate `teardown` signals. This is because no `yield` was present after the initial microtick and before the `fetch` call.
I'm still trying to find a more elegant solution to this, but it doesn't seem possible to yield without emitting a value, and async generators may not abort on `await` statements, which seems counterintuitive.
Changeset hasn't been added since it's a follow-up fix.
- Add `yield` after microtick delay to allow `fetchOperation` to abort early
- Update tests to correctly detect missing early-terminations
=> fix(core): Fix immediate cancellation of fetch requests

.changeset/many-cats-travel.md, packages/svelte-urql/src/mutationStore.ts, packages/svelte-urql/src/subscriptionStore.ts
The `SubscriptionHandler` argument was accidentally defined and implemented on the `mutationStore` rather than the `subscriptionStore`.
It's now been moved, which is a breaking change.
The handler was never intended to be on the `mutationStore`!
- Move handler from `mutationStore` to `subscriptionStore`
=> fix(svelte): Move handler from mutationStore to subscriptionStore

.changeset/hungry-panthers-fly.md, packages/core/src/types.ts
`graphql.js` now has a built-in type for typed `DocumentNode`s, which we must adopt to support tools that rely on this type instead of `@graphql-typed-document-node/core`.
We can maintain our prior approach of having a copied type to maintain backwards- and forwards- compatibility by extending our own type with the type property carrying the types we need. The only difference to the other package is that `graphql.js` uses a different name for the property: https://github.com/graphql/graphql-js/blob/e171a14/src/utilities/typedQueryDocumentNode.ts#L8-L22
This has been tested with the following ts file:
```ts
import { Client, TypedDocumentNode } from '@urql/core';
import type { TypedQueryDocumentNode } from 'graphql';
import type { TypedDocumentNode as LegacyTypedDocumentNode } from …
```
=> feat(core): Add support for graphql.js’ built-in TypedQueryDocumentNode

packages/core/src/client.ts
This removes the redundant `context.suspense` disabling from `client.query` that doesn't do anything. This was relevant before from when suspense was implement in the `@urql/core` library.
- Remove redundant `client.query` suspense normalisation
=> fix(core): Remove redundant suspense options change in client.query

.changeset/cuddly-actors-look.md, .changeset/five-lies-collect.md, docs/advanced/authoring-exchanges.md, exchanges/auth/src/authExchange.test.ts, exchanges/auth/src/authExchange.ts, exchanges/context/src/context.ts, exchanges/execute/src/execute.ts, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/offlineExchange.test.ts, exchanges/graphcache/src/offlineExchange.ts, exchanges/multipart-fetch/src/multipartFetchExchange.ts, exchanges/persisted/src/persistedExchange.ts, exchanges/retry/src/retryExchange.ts, packages/core/src/exchanges/cache.ts, packages/core/src/exchanges/compose.ts, packages/core/src/exchanges/fetch.ts, packages/core/src/exchanges/ssr.ts, packages/core/src/exchanges/subscription.ts, packages/core/src/types.ts
This is a small quality of life improvement for the `composeExchanges` helper in `@urql/core` that should make it easier for users to write and understand `Exchange`s.
It simply removes the need for `share` to be called manually on `Exchange`s by wrapping the `ExchangeIO` function in share calls automatically.
This shortens our docs on "Authoring Exchanges" by a whole large section, simplifies some exchanges, and shouldn't have any negative consequences, except for mocked `ExchangeIO` in tests requiring a `share` call now.
- Wrap `forward`'s argument and return value in `share` in `composeExchanges`
- Add invariant in development that enforces exchanges to call `forward` just once
- Update all exchanges to remove redundant `share` calls
=> feat(core): Wrap ExchangeIO in share calls in composeExchanges (QOL)

.changeset/pink-penguins-grin.md, packages/core/src/utils/error.ts
I was reminded me of having multiple copies of `graphql`, or a future where some `graphql` imports are aliased to `@0no-co/graphql.web` or `graphql-web-lite`, but not all.
Our `CombinedError` now passes through `GraphQLError`s but it isn't yet permissive enough to allow for any object that vaguely adheres to the `GraphQLError` shape to be passed through.
- Allow for any object that adheres to the `GraphQLError` shape to be passed through to `CombinedError.graphQLErrors`
=> fix(core): Allow permissive passthrough for CombinedError.graphQLErrors

.changeset/giant-flies-exercise.md, exchanges/graphcache/src/offlineExchange.ts, exchanges/graphcache/src/types.ts
Adds missing `operation.extensions` serialization and replaces `print()` usage with `stringifyDocument()` from `@urql/core`
- Replace `print` with `stringifyDocument`
- Serialize `operation.extensions`
=> fix(graphcache): Use stringifyDocument in offlineExchange and support extensions

.changeset/good-ads-watch.md, packages/react-urql/src/hooks/state.ts, packages/react-urql/src/hooks/useMutation.ts, packages/react-urql/src/hooks/useQuery.ts, packages/react-urql/src/hooks/useSubscription.ts
Resolves #3088
> **Background Note:** To be honest, I'm really sick of having to explain that this is safe to ignore and does what it's supposed to, so instead, I've decided that it's best to add a small check to silence the warning.
This is hard to reproduce, so I'm not sure if it's effective in all cases.
**Explanation:** When a different component, during its update cycle — or an external store/function during an update cycle — triggers a side-effect that dispatches a query to the `Client`, which then sends a new result to a component using `useQuery` synchronously, React will be inside a render phase and will receive an update.
This is fine. React is designed to handle updates during render phases. In fact, in other cases it doesn't actually output a warning. This warning is designed …
=> fix(react-urql): Silence react render phase warning

exchanges/auth/package.json, exchanges/context/package.json, exchanges/execute/package.json, exchanges/graphcache/package.json, exchanges/multipart-fetch/package.json, exchanges/persisted/package.json, exchanges/populate/package.json, exchanges/refocus/package.json, exchanges/request-policy/package.json, exchanges/retry/package.json, package.json, packages/core/package.json, packages/preact-urql/package.json, packages/react-urql/package.json, packages/svelte-urql/package.json, packages/vue-urql/package.json, pnpm-lock.yaml
No changeset added since this is not critical and will just go into the next release batch.
=> chore: Bump wonka to ^6.2.6 across all packages

.changeset/soft-glasses-guess.md, package.json, packages/core/src/client.ts, pnpm-lock.yaml
This cleans up the `Client`’s `createExecutionRequest` and `makeResultSource` logic. Specifically, it groups a couple of code branches, and refactors the reused source to use a simple `lazy` source rather than a `make` source.
Furthermore, it will allow multiple mutation results to be issued. A follow-up PR for bindings is needed here.
- Clean up `Client` logic
- Replace `make` result source with `lazy`
- Add `takeWhile(result => !!result.hasNext, true)` instead of `take(1)` on mutations
=> refactor: Clean up Client result source logic and allow multiple mutation results

packages/core/src/client.test.ts, packages/core/src/client.ts
This gets rid of the last `{ ...result }` cloning code that we had left in the `Client`.
- Remove `{ ...result, stale: true }` in favour of direct assignment
- Prevent issuing additional `stale: true` result for own result
=> refactor(core): Prevent result cloning in Client

.changeset/tricky-poets-clap.md, packages/core/src/client.ts, packages/core/src/exchanges/fetch.ts, packages/core/src/internal/fetchOptions.ts, packages/core/src/types.ts
This is a proposal which allows the `fetchExchange` to handle subscriptions.
This has been submitted to validate the following two assumptions:
- `OperationContext.fetchSubscriptions` & `ClientOptions.fetchSubscriptions` may or may not be a good idea
- GraphQL API frameworks like `graphql-yoga` will be able to handle subscriptions via `text/event-stream`/`multipart/mixed` response streams
If these two assumptions are fine, we can go ahead and merge this, I reckon.
- Add `OperationContext.fetchSubscriptions` & `ClientOptions.fetchSubscriptions`
- Allow `fetchExchange` to handle subscriptions when enabled
- Switch `Accept` header when a subscription is sent
=> feat(core): Allow fetch exchange to handle subscriptions

.github/workflows/release.yml
This was missing in latest run
=> fix(workspace): add GITHUB_TOKEN env

.changeset/friendly-flies-smile.md, packages/core/src/internal/fetchOptions.test.ts, packages/core/src/internal/fetchOptions.ts
The multipart request spec actually specifies that `map` is of type `Record<string, string[]>` rather than `Record<string, string>`. While this is easy to miss, it's likely for upload deduplication, which we don't do but have to respect.
- Convert `FormData` `map` field to `[prop: string]: [string]`
=> fix(core): Fix multipart FormData map field format

.changeset/hungry-coins-lie.md, packages/core/package.json, packages/core/src/internal/fetchSource.test.ts, packages/core/src/utils/result.test.ts, packages/core/src/utils/result.ts, pnpm-lock.yaml
Resolves #3122
This deeply merges (while cloning) result sets from Incremental Delivery results, and handles deep merges on the root payload as well, which we previously didn't realise was a legal usage of `@defer`.
- Add deep-clone merging of incremental delivery payloads
- Add handling of merging patches into root (i.e. `path: []`)
=> fix(core): Fix Incremental Delivery payloads deep merging and root patches

.changeset/eight-kangaroos-wave.md, packages/core/src/internal/fetchSource.test.ts, packages/core/src/internal/fetchSource.ts
Resolves #3128
We had a missing catch case, where `!response` wasn't handled, which can happen if `fetch` rejects immediately rather than delivering a failed response. This would happen in particular due to offline network errors or broken connection attempts.
This is a regression introduced in the fetch refactor, and was introduced because we don't have two catch handlers anymore, hence `response!` was an invalid non-undefined assertion.
- Add missing `!response` case
- Add test
=> fix(core): Handle fetch rejections and pass to makeErrorResult

.changeset/nice-flowers-think.md, packages/core/src/utils/result.test.ts, packages/core/src/utils/result.ts
Fixes an issue where `hasNext` would be updated to `false` and a subscription would be ended early when the `subscriptionExchange`’s sink doesn't actually set `hasNext: true` on a following result.
This is a similar issue to the missing `defaultHasNext` in `makeResult` we had to add.
- Add default `hasNext` value to merged results
- Add unit tests
=> fix(core): Fix early closing of subscriptions

.changeset/nervous-forks-drum.md, packages/core/src/internal/fetchSource.ts
Resolve #3153
The spec makes no stipulations as per what the boundary should be changed to when the content happens to contain the boundary. So, naturally, we'll need to split on `CRLF` with the boundary.
- Add `CRLF` to boundary splitting
=> fix(core): Fix multipart stream being split when content contains boundary

.changeset/warm-poets-battle.md, exchanges/graphcache/src/offlineExchange.ts
Resolves #3142
Fixes a missing `share` call in `offlineExchange` which would lead to duplicated offline mutations being queued up.
- Add missing `forward` `share` call
=> fix(graphcache): Fix offlineExchange duplicating offline mutations

.changeset/wicked-eggs-talk.md, packages/core/src/client.ts
This covers all operation kinds in `client.reexecuteOperation`, in case we end up using it as an arbitrary dispatcher. I realised, the old behaviour may have been confusing and there isn't an alternative to this method, so it really shouldn't be.
- Handle subscriptions and teardowns properly in `client.reexecuteOperation`
=> fix(core): Improve reexecuteOperation of arbitrary operations

.changeset/strange-elephants-serve.md, exchanges/auth/src/authExchange.ts
There were scenario's where the `operation` would get altered and hence we wouldn't see it in the bypassQueue, now to make sure the first thing we do is we add the operation in the `bypassQueue` by the mutation identity.
Secondly we prevent ever calling `didAuthError` on operations produced by `utils.mutate` and last but not least we have started cleaning up the Set when results do come in.
- assert on a `operationc.context._identity` match
- key the bypassQueue by `operationc.context._identity`
- clear the queue after a result comes in
=> fix(auth): prevent retrying the operation produced by `mutate`

.changeset/rich-taxis-end.md, exchanges/graphcache/e2e-tests/query.spec.tsx, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/shared.ts
Resolves #3161
Previously, as `hasNext` wasn't consistently handled across the `urql` codebase prior to `v4`, we didn't have a signal and logic to handle partial, deferred results. We can now add the `hasNext` flag to `@urql/exchange-graphcache` and let deferred, uncached results fall through the usual cached result handling, and instead, pass the query on to the API.
- Add `hasNext` flag to cached query results
- Handle `hasNext` cache results in `cacheExchange` and pass them on
- Increase consistency of `stale` flag for `cache-only` operations
=> fix(graphcache): Mark deferred, uncached results as partial

.changeset/gentle-melons-march.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/extras/relayPagination.test.ts, exchanges/graphcache/src/extras/simplePagination.test.ts, exchanges/graphcache/src/index.ts, exchanges/graphcache/src/offlineExchange.test.ts, exchanges/graphcache/src/operations/index.ts, exchanges/graphcache/src/operations/query.test.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/shared.ts, exchanges/graphcache/src/operations/write.test.ts, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/store/data.ts, exchanges/graphcache/src/store/index.ts, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/test-utils/examples-1.test.ts, exchanges/graphcache/src/test-utils/examples-2.test.ts, exchanges/graphcache/src/test-utils/examples-3.test.ts, exchanges/graphcache/src/test-utils/suite.test.ts
Resolves #3160
This prevents us from:
- copying the incoming API data causing `__typename` to be applied to output data by default
- reusing incoming API data and treating it as equivalent to Graphcache’s owned data
In short, we don't differentiate in the `cacheExchange` whether we're passing `query()` previous Graphcache data or API data. This data is then used to diff against the new result, reusing as much of it as possible when it's unchanged. It's also used to complete the output data when some cache resolution fails, to fall back to API data.
However, we shouldn't reuse this data blindly when it's API data, since that data can slightly differ and carry `__typename` fields even when those aren't specified in the selection set.
- Replace `originalVariables` with better …
=> fix(graphcache): Improve separation of API and owned data

.changeset/real-queens-crash.md, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/shared.test.ts, exchanges/graphcache/src/operations/shared.ts, exchanges/graphcache/src/operations/write.ts
Resolves #3161
**Note:** This will need a rebase after #3165 is merged and should be merged on top.
A rather old regression would cause `@defer` directives to manipulate the `deferRef` state and then become “sticky”, meaning that all future fields would also be considered deferred.
Instead, we need to make sure that this field resets properly and that the state returns to normal.
On a side-note, I tried to convert `makeSelectionIterator` to a generator function, since this would make it more elegant, but an initial rough implementation decreased overall cache read/write performance by 15–20%, so we'll have to investigate whether there's more we can do here. In general, traversal is the most expensive part of the cache operations, so if we can instead make it faster we'd profit from that …
=> fix(graphcache): Fix defer field state becoming sticky and affecting future fields

.changeset/afraid-seas-arrive.md, packages/core/src/internal/fetchOptions.test.ts, packages/core/src/utils/variables.test.ts, packages/core/src/utils/variables.ts
Resolves #3168
Seems like some APIs/frameworks actually care about this 🤷 Currently, this will affect operation keys, however, since mutations have unique instances, we can probably get away with making the keys for variables identical for queries.
- Replace `File` and `Blob` with `null` in stringified variables
=> fix(core): Replace File/Blob objects with null in serialized variables

.changeset/itchy-queens-scream.md, packages/core/src/internal/fetchSource.ts
This implements a fix for a regression in #3155.
Basically, we now split the incoming `multipart/mixed` response by `CRLF` and the boundary. However, our tests send the preamble split by `CRLF` + boundary, while some newer variations would only send the boundary as the preamble and only after use `CRLF`
This caused the first payload to be malformed and disregarded.
- Add preamble recovery depending on `CRLF` splitting
=> fix(core): Handle both variations of multipart/mixed preamble

.changeset/moody-hats-attend.md, packages/core/src/client.test.ts, packages/core/src/client.ts
Resolves regression from #3157
This prevents us from blocking `network-only` operations which follow `cache-and-network` operations, if the latter has queued them up while the cached result comes in.
In other words, if `result.stale` is set, we still allow `dispatched.delete` to remove the key and unblock it if the current operations queue contains that operation. This basically is the equivalent of saying that we unblock operations, even if they're marked as `stale` if a new operation for them is already waiting to be sent.
- Allow operations to be run if they're queued up already while a `result.stale` marked result comes in
=> fix(core): Fix regression that broke cache-and-network

docs/advanced/debugging.md
The changes in this PR updates a typo in documentation, regarding a function call.
This could cause confusion for the readers of the documentation.
The statement is the following: 
> While it's possible to call
`client.subscsubscribeToDebugTarget` in an exchange it's only valuable when creating a debugging
Besides the typo, the statement is true. Though, the typo assumes that the `subscsubscribeToDebugTarget` method is available on the `client` object, [which it isn't](https://github.com/urql-graphql/urql/blob/ff5d7397a14497193e28bfc69b719abe8dcdcaf8/packages/core/src/client.ts#L720).
- Altered the content of `docs/advanced/debugging.md`
=> Fix typo in docs/advanced/debugging.md

.changeset/sixty-masks-itch.md, exchanges/graphcache/src/cacheExchange.ts
Resolves #3188
A regression caused operations to not be recognised internally by Graphcache anymore when they were previously torn down and then queried from the cache without refetching. In short, the `cacheExchange` would lose its record of the `Operation` and would be unable to issue updates for the queries.
- Add missing `operations.set` record entry for cached results
=> fix(graphcache): Add missing operations record on cache result

.changeset/fair-eels-march.md, docs/advanced/persistence-and-uploads.md, exchanges/persisted/src/persistedExchange.test.ts, exchanges/persisted/src/persistedExchange.ts
This PR aims to resolve https://github.com/urql-graphql/urql/issues/3185.
Currently, `@urql/exchange-persisted`'s `options.preferGetForPersistedQueries` doesn't allow for `persistedOperation.context.preferGetMethod` to be set to `true` or `'within-url-limit'`, and instead sets `persistedOperation.context.preferGetMethod` to `'force'` when `options.preferGetForPersistedQueries` is `true`. This leads to broken GET requests when queries become massive.
Another issue was that although the TSDocs suggest that [the default value](https://github.com/urql-graphql/urql/blob/cb628ca4e9207b1928a5e137fddbd14c33afb6e4/exchanges/persisted/src/persistedExchange.ts#L42) of `options.preferGetForPersistedQueries` is `true`, this wasn't reflected in the logic.
In `@urql/exchange-persisted`:
- The type of …
=> fix(persisted): persisted queries can use GETs within URL limits

.changeset/fifty-sheep-battle.md, CONTRIBUTING.md, packages/react-urql/src/hooks/state.ts
When component A uses `useQuery` and has already loaded a result and then component B mounts and uses the same query, it currently causes component A to re-render because `operation` is not shallowly equal even though nothing about the result is changing.
This is a performance issue because it causes unnecessary re-renders.
It also can cause an infinite render loop with lazily loaded components because it can trigger a state update further up the tree during the initial render of the lazily loaded component which makes React back out of the render (which happened in my application, although I've had trouble creating a minimal reproduction). This issue is resolved with this change in my application.
- Added a special case to `isShallowDifferent` for `operation` where it checks the …
=> Fix re-rendering when another component reuses the same query

.changeset/wet-crabs-dream.md, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/offlineExchange.test.ts, exchanges/graphcache/src/offlineExchange.ts, exchanges/graphcache/src/store/data.ts
Resolves #3093
Adds missing retries of query operations when offline rehydration has completed and fix the timing of flushing the failed queue of operations after rehydration.
The former can lead to operations only awaiting network requests even after finishing storage rehydration, since no additional operations would be issued.
The latter can lead to stalled operations when the device is offline on load.
- Add query operations to `failedQueue` while rehydrating
- Delay timing of `flushQueue` to after storage rehydration
- Move `onOnline` register to `flushQueue`
=> fix(graphcache): Add missing retries after offline rehydration

.changeset/green-geese-switch.md, packages/core/src/exchanges/subscription.ts
Resolves #3205
Always exclude `teardown` from the accepted operations in `subscriptionExchange` to avoid confusion, since it's nonsensical to let it handle them as a normal operation.
- Add `teardown` check to `subscriptionExchange`'s filters
=> fix(core): Always exclude teardowns from subscriptionExchange

exchanges/auth/package.json, exchanges/context/package.json, exchanges/execute/package.json, exchanges/graphcache/default-storage/package.json, exchanges/graphcache/package.json, exchanges/persisted/package.json, exchanges/populate/package.json, exchanges/refocus/package.json, exchanges/request-policy/package.json, exchanges/retry/package.json, packages/core/package.json, packages/introspection/package.json, packages/preact-urql/package.json, packages/storage-rn/package.json, packages/svelte-urql/package.json, packages/vue-urql/package.json
I moved `types` condition to the front. `package.json#exports` are **order-sensitive** - they are always matched from the top to the bottom. When a match is found then it should be used and no further matching should occur. 
Right now, the current setup works in TypeScript but it's considered a bug and it should not be relied upon, see the thread and the comment [here](https://github.com/microsoft/TypeScript/issues/50762#issuecomment-1528318260). For that reason, I would like to fix all popular packages that misconfigured their `exports` this way so the bug can be fixed in TypeScript.
⚠️ this PR focuses solely on fixing "🐛 Used fallback condition" problem but the "🎭 Masquerading as CJS" remains here. You can check the reported errors …
=> fix(types): move `types` condition to the front

.github/workflows/site.yml, packages/site/static.config.js
This PR tweaks the react-static docs config _a tiny bit_ so that we can deploy the urql docs on Vercel. The end result:
- Vercel for staging previews on PRs. [See here](https://urql-docs-m6qsbtehz-formidable-labs.vercel.app/) for an example from this PR. For staging previews, the docs will be deployed at root of deployment site.
- We'll be using Vercel for production deploys here soon as well (instead of S3), so production Vercel deployment will still be nested at `/open-source/urql` so that it can be "stitched" into the upcoming formidable.com site.
- Removing all traces of Surge for deployments.
- Once formidable.com is migrated to new Next.js site, we'll follow up and remove formideploy logic as well.
=> Vercel for Docs Deployment

.changeset/spicy-comics-shave.md, exchanges/graphcache/src/operations/query.test.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/store/data.ts, packages/site/vercel.json
A prior fix in #3165 prevented us from mixing API and Graphcache’s data. While we previously avoided modifying API data or prior results from Graphcache, this created new corner cases that were hard to cover.
Specifically, nested lists are hard to diff against prior results as they can be re-entered, `null` must be skipped, and there’s more cases where comparing data and returning previous results could be dangerous and lead to the wrong outcome.
This PR aims to start addressing this issue but may forget to cover some corner cases.
- Restore and create lists against prior data
=> fix(graphcache): Fix reference equality of lists not always being preserved

.changeset/breezy-melons-deny.md, packages/core/src/exchanges/cache.ts
Resolves #3223
Allow subscriptions to also be annotated with `additionalTypenames` and use them to re-execute queries.
- Include subscriptions in response handling in document cache
=> fix(core): Respect additionalTypenames option on subscriptions

.changeset/curvy-poems-compare.md, exchanges/retry/src/retryExchange.test.ts, exchanges/retry/src/retryExchange.ts
Resolves #3220
This resets operations’ `delay` and `count` states if they succeed. This may be important to recover from failing subscriptions, since a new result should be able to restore the retry state to where it was before the subscription failed.
- Add resetting object state to `retryExchange`
- Add test case
=> fix(retry): Reset delay/count state if an operation succeeds

.changeset/hungry-zebras-count.md, exchanges/graphcache/src/offlineExchange.ts
Follow-up to #3199
Resolves #3093
- Add a crude teardown+seen routine to `failedQueue` in `offlineExchange`'s `flushQueue`
=> fix(graphcache): Prevent offlineExchange from issuing duplicate operations

.changeset/dull-fishes-push.md, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/types.ts
Resolves #3176
Add `globalIDs` option to omit typenames from entity cache keys.
This allows schemas with global ID guarantees and no ID overlap to combine entities in the cache. While this isn't recommended per se, since it's often a schema design problem, rather than a cache problem, it can be used to create strategic overlaps in the cache, when a type of an object implementing an interface “changes”
- Add `globalIDs` option and update `keyOfEntity` function
=> feat(graphcache): Add globalIDs option

.changeset/weak-eagles-walk.md, exchanges/auth/src/authExchange.ts
A regression caused the `authExchange` to disregard teardowns and still issue retries for operations that were cancelled.
- Add `retryQueue.delete` call for teardowns
=> fix(auth): Fix authExchange’s retry queue ignoring teardowns

.changeset/pretty-dodos-happen.md, exchanges/graphcache/src/offlineExchange.ts
Related to #3235
Remove queries from `offlineExchange`’s failed queue that are torn down during rehydration.
This may become important to prevent fetching queries that are no longer relevant.
- Add filtering to `failedQueue` for teardowns
=> fix(graphcache): Fix offlineExchange’s failed queue not being filtered for teardowns

.changeset/famous-snakes-double.md, packages/core/src/internal/fetchSource.ts
Related #3234
This PR returns the `AbortController` invocation to its previous behaviour, when it used to be more forceful.
The `fetchSource` will now properly abort the request outside of when its async generator yields results. This means that it can now abort _after_ headers have been delivered but _before_ a response body becomes available. This will cause us to now cancel requests again that are stalled and hence not wait for a response body if it's not needed any longer.
- Move `AbortController` logic outside of async generator
=> fix(core): Return fetch source cancellation to old behaviour

docs/basics/ui-patterns.md, docs/graphcache/local-resolvers.md, examples/README.md, examples/with-infinite-pagination/README.md, examples/with-infinite-pagination/index.html, examples/with-infinite-pagination/package.json, examples/with-infinite-pagination/src/App.jsx, examples/with-infinite-pagination/src/SearchResults.jsx, examples/with-infinite-pagination/src/index.jsx, examples/with-infinite-pagination/vite.config.js, examples/with-pagination/README.md
Add example for UI-only infinite pagination to our examples folder, that doesn't keep an array of variables, and instead renders pages dynamically and recursively, which is often preferable, and also restores all pages on initial mount against the cache.
While this is a simple pattern, it's often overlooked and not considered. Worst of all, because we had no example of this, it was hard to communicate this as a _real_ example to handling infinite pagination via:
- added state
- added effects
- Graphcache
Which is all not preferable to this new example, unless a flat list of items is needed (in such a case, Graphcache's pagination helpers are still preferred)
=> docs: Add more extensive infinite pagination example code

docs/basics/svelte.md
store objects must be unpaused directly
The docs are wrong
removes '$' from todo store reference
=> docs(svelte): correct unpause code example

.changeset/five-icons-agree.md, exchanges/graphcache/src/operations/query.test.ts, exchanges/graphcache/src/operations/write.test.ts, exchanges/graphcache/src/operations/write.ts
We basically had some logic that would allow writes to be incomplete, however, this didn't apply to optimistic results, which would always cause cached fields to be deleted. Furthermore, in production, partial results will always lead to cached values being deleted from the cache.
Instead, we can apply a better heuristic which only triggers the warning when a field is missing from the cache, but always allow writes to continue, no matter whether values are set or not.
This should in theory be safe, since we're moving potential errors over to reading from the cache.
This also adds a change which makes optimistic mutations read previous keys and `__typename` fields from the cache to complete mutation results from prior cache results. This should tremendously help the developer experience of …
=> fix(graphcache): Allow partial optimistic results

.changeset/serious-dots-sit.md, exchanges/graphcache/src/cacheExchange.ts
Prevent marking operations as reexecuting when an optimistic mutation executes and instead delay rotating them
- Prevent `reexecutingOperations` rotation after optimistic mutation
=> fix(graphcache): Prevent marking operations as reexecuting after optimistic mutation

.changeset/wild-hotels-kick.md, exchanges/graphcache/src/operations/write.ts
Fixes a typo in `updateContext` that caused `info.parentKey` to be incorrectly set for updaters and optimistic updaters
- Update `typename` in `updateContext` calls in `write` to `entityKey || typename`
=> fix(graphcache): Fix info.parentKey for updaters and optimistic updaters

.changeset/healthy-chefs-learn.md, exchanges/graphcache/src/store/store.ts, scripts/eslint/preset.js
Resolves #3274
Fixes untranspiled class property initializer syntax being leftover in build output due to syntax used in the `Store`.
This is a regression in #3053, and further regressions will be prevented by adding an ESLint rule.
- Relace class property initializer in `Store`
=> fix(graphcache): Fix untranspiled class field initializer syntax in bundle

.changeset/honest-hairs-wave.md, packages/core/src/exchanges/cache.ts, packages/core/src/exchanges/ssr.test.ts, packages/core/src/exchanges/ssr.ts
Resolves use-cases where the server-side omits the `cacheExchange` and, hence, misses formatting of the document.
- Add `formatDocument` to `ssrExchange`
=> fix(core): Add typename formatting to SSR Exchange

.changeset/swift-camels-draw.md, packages/core/src/client.ts, packages/core/src/utils/maskTypename.ts
See: https://github.com/urql-graphql/urql/issues/3297#issuecomment-1612987757
This PR, when applied, deprecates `maskTypename` (both the option and the utility).
The option may be removed sooner than the utility function.
In short, applying `maskTypename` was not recommended and applying it in an exchange yourself is still supported in the future.
This is because it's often only used (and requested) by users given that they want to pass GraphQL objects back into their mutations as GraphQL input objects, which requires the following pre-conditions to apply:
- the API mimicks inputs that mirror outputs
- the user doesn't actually provide the inputs
- the selection sets of both match precisely
However, compared to Graphcache's output for example, it leads to non-faithful data shapes, and is …
=> chore(core): Deprecate maskTypename option

.changeset/rich-crews-wink.md, examples/with-svelte/package.json, examples/with-svelte/vite.config.mjs, packages/svelte-urql/package.json
Resolves #3300
This allows the package to be installed in projects using svelte 4
Changed @urql/svelte
Added Svelte ^4.0.0 as a peer dependency (in addition to the ^3.0.0 that was already there.
=> chore(svelte): Increase peer dependency range for Svelte 4

.changeset/five-penguins-unite.md, exchanges/persisted/src/persistedExchange.ts
Resolves #3311
Add missing `teardown` support to the `persistedExchange`. Since the hashing function is promisified and hence deferred, initial operation reads that are cancelled (i.e. particularly in React/Preact) need to cancel the ongoing operation correctly.
- Add missing `takeUntil` teardown source to `persistedExchange`
=> fix(persisted): Add missing teardown source

.changeset/light-kangaroos-smash.md, exchanges/auth/src/authExchange.test.ts, exchanges/auth/src/authExchange.ts
This adds a `catch(errorQueue)` case to `refreshAuth` and replaces `finally(flushQueue)` with `then(flushQueue)`. The rejection case will issue `OperationResult`s for all `Operation`s in the queue and will pass the authentication error that `refreshAuth` rejected with on as the network error.
- Add error handling to `refreshAuth` rejections
=> feat(auth): Handle refreshAuth rejections gracefully

.changeset/eleven-snakes-look.md, .changeset/two-ants-relate.md, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/offlineExchange.ts, exchanges/graphcache/src/test-utils/examples-1.test.ts, packages/core/src/types.ts
This PR, when applied, makes two changes.
Primarily, requesdt policies other than `cache-first` are now allowed in the `offlineExchange` when re-running failed operations. After rehydration or when replaying failed queries, queries will now not be forced to `cache-first` policies, and instead use the highest policy that was issued, preferring network policies (`cache-only` < `cache-first` < `network-only` < `cache-and-network`).
Additionally, instead of checking manually which mutations have made optimistic changes, the `cacheExchange` will now mark optimistic mutations' contexts with `optimistic: true` instead.
- Add `OperationContext.optimistic` indicating optimistic updates have been made
- Remove `cache-first` forcing in `offlineExchange`
- Pick highest policy that has been seen in …
=> fix(graphcache): Re-enable offlineExchange issuing non-cache request policies

.github/ISSUE_TEMPLATE/bug_report.yaml, CONTRIBUTING.md, docs/advanced/authentication.md, docs/advanced/persistence-and-uploads.md, docs/advanced/retry-operations.md, docs/advanced/subscriptions.md, examples/README.md, examples/with-apq/README.md, examples/with-apq/package.json, examples/with-defer-stream-directives/README.md, examples/with-graphcache-pagination/README.md, examples/with-graphcache-updates/README.md, examples/with-infinite-pagination/README.md, examples/with-multipart/README.md, examples/with-next/README.md, examples/with-pagination/README.md, examples/with-react-native/README.md, examples/with-react/README.md, examples/with-refresh-auth/README.md, examples/with-retry/README.md, examples/with-subscriptions-via-fetch/README.md, examples/with-svelte/README.md, examples/with-vue3/README.md
- Refactor `examples/README` to contain a table with more links
- Add Stackblitz & CodeSandbox links to each example's `README`
- Add links to examples to various docs pages
- Add subscriptions via `fetch` instructions to docs
=> docs(workspace): Add additional sandbox links and links to examples

.changeset/seven-adults-fix.md, exchanges/persisted/src/persistedExchange.test.ts, exchanges/persisted/src/persistedExchange.ts
This allows `generateHash` to resolve to `null | undefined`, effectively allowing the persisted logic to be skipped selectively for individual operations.
- Allow `null | undefined` to be returned by `generateHash`
- Add test for new case
=> feat(persisted): Allow nullish hashes for skipping persisted logic

.changeset/many-rabbits-wave.md, packages/svelte-urql/src/queryStore.ts, packages/svelte-urql/src/subscriptionStore.ts
Resolves #3329
This moves the source subscription to the result `writable` in `queryStore` and `subscriptionStore`. We must subscribe when the `StartStopNotifier` is called, so to start the subscription whenever there isn't an active one to the `Client`.
If we don't start the subscription on demand, then unsubscribing (with all observers) from the stores will let them “die”. They won’t have an active subscription and won’t be able to start a new one.
The `writable` in Svelte already checks when to call `StartStopNotifier` via semaphore logic, so no extra code is needed.
The only risk with this fix is whether people relied on `queryStore` starting a subscription implicitly. This really shouldn't have been done before as it's pointless to instantiate a store without reading from it, so I …
=> fix(svelte): Move Client subscription to writable start

.changeset/thin-badgers-return.md, docs/graphcache/local-resolvers.md, docs/graphcache/normalized-caching.md, exchanges/graphcache/src/operations/shared.ts, exchanges/graphcache/src/store/data.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/types.ts
This updates `cache.resolve` to return `undefined` for uncached fields.
This has two reasons:
- Resolvers allow users to return `undefined` to signal a cache miss, however, this wasn't clear — both because of the documentation, and because `cache.resolve` itself never returns `undefined`. Hence, while it's popular to end a resolver in a `cache.resolve` call, this meant that a cache miss could never be caused on this field.
- Not being able to return `undefined` meant that the `Cache` interface virtually had little to no ways of actually letting a user check whether a field was cached or not. By returning `undefined` this now becomes clear
This isn't considered a breaking change since it shouldn't alter prior behaviour significantly:
- A user may now correctly see a cache miss, where …
=> feat(graphcache): Allow cache.resolve to return undefined for uncached fields

.changeset/cyan-melons-drive.md, exchanges/graphcache/src/store/data.ts
This changes the expected behaviour for when dependencies are recorded for caches accesses.
> **Note:** Dependencies are basically entity or field keys marking a cache read or write. When a cache write updates a dependency, then all cache reads (i.e. queries) that have the same cache dependency will be updated accordingly, i.e. re-queried. This is how Graphcache issues updates to queries after cache writes.
While this wasn't a bug, any usage of `cache.resolve(entity, '__typename')` wouldn't actually record a dependency, which could cause confusion. The exception has now been removed.
- Remove dependency exception for accessing `__typename` on entities
=> fix(graphcache): Record dependencies for __typename accesses

docs/graphcache/cache-updates.md
We have to clarify in our docs why cache updates may be written and when they can be avoided. This can trivially be done by explaining what cache updaters are for.
Additionally, while we now support partial, optimistic updaters, we don't actually clarify that this is possible in the docs, and instead state that it still isn't. The docs now state that we don't have to define all fields.
- Add section on cache updates
- Add section on partial, optimistic updates
=> docs(graphcache): Update cache update docs

.changeset/hungry-experts-admire.md, .changeset/tame-ways-obey.md, exchanges/graphcache/src/helpers/dict.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/store/data.ts, exchanges/graphcache/src/store/store.test.ts
While looking at a code snippet, I found that we didn't come back to providing `parent[info.fieldName]` for scalar resolvers. This is an easy way of making this work. It does add a bit of overhead, but I think it's the only way to add this without a breaking change (and without doing a weird set/delete dance, which is likely to be slower)
The other issue is that `info.parentFieldKey` isn't consistently populated with the `fieldKey` (as is implied and documented) but with `info.parentKey` joined with the `fieldKey`, i.e. a full key.
This means that `cache.resolve(parent, info.parentFieldKey)` wouldn't work in resolvers, but would work in updaters.
- Replace incorrect `updateContext` calls to fix `info.parentFieldKey` in resolvers
- Update parent input for scalar fields to have both …
=> fix(graphcache): Improve Graphcache resolver consistency

.changeset/heavy-shirts-smash.md, exchanges/graphcache/src/helpers/defaultDirectives.ts, exchanges/graphcache/src/store/store.ts
- Fix `info.parentKey` and `info.parentFieldKey` usage in default directives
- Add missing `info.partial = true` setter to `@_optional`
=> fix(graphcache): Fix partial and info usage in default directives

.changeset/few-garlics-judge.md, exchanges/graphcache/src/operations/query.ts
**Note:** It shouldn't currently be possible to trigger this edge case! However, I can't predict whether the code will change and cause us to create a case for this in the future, so changing this is the safest course of action.
When a field, hypothetically speaking, flips `info.partial = true`, but a parent field aborts with a cache miss, and a parent field then recovers by setting the value to `null`, then `info.partial` won't be reset to its prior value, which could've been `false`. 
- Restore `ctx.partial` to initial value in `readSelection` loop on early return
- Restore `ctx.partial` to initial alue in `readResolverResult`'s and `readLink`'s array loop in early return case
=> fix(graphcache): Fix info.partial edge case for @_optional

.changeset/polite-kangaroos-rhyme.md, exchanges/auth/src/authExchange.test.ts, exchanges/auth/src/authExchange.ts
See: https://github.com/vercel/next.js/issues/49373
It's unexpected and undefined behaviour to throw/reject in the initialization function passed to the `authExchange()` and any rejections will be uncaught.
This can make thes situations hard to debug, as the promise will be uncaught.
Instead, errors during initialization will now be caught, queued up `Operation`s will be fulfilled with an `OperationResult` with their error populated to the caught error, and a warning will be output in development that tells users what's going on.
This essentially allows uncaught errors in the initialization function to be discovered and handled properly. At worst, it'll fail all operations coming in and will retry the initialization function if the operations are retried.
- Catch initialization function …
=> fix(auth): Catch unexpected errors during initialization

.changeset/shy-maps-raise.md, packages/core/src/exchanges/subscription.ts
Resolves #3345
**Note**: I'd prefer not to ship this and there's an ongoing discussion in #3345, that requires confirmation before this change is made. This is simply already submitted for reference for the discussion.
The reason why I'd prefer not to ship this is that we're basically forced to simply check using `Array.isArray` for an array value on the error callback and then circumvent issuing a network error and instead issue a result — potentially merging prior results — when `GraphQLError[]` is passed as a value.
I find this extremely odd precisely because using `next` + `complete` feels much more natural here. `GraphQLError[]`, as part of the `ExecutionResult`'s `errors`, is a defined shape of a result and can be accepted at any time. Receiving it in `errors` basically forces a new …
=> feat(core): Handle GraphQLError[] value in error observer callback of subscriptionExchange

.changeset/odd-parrots-fix.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts
Resolves #3355
Changes in #3317 accidentally removed code that preserved the original operation for optimistic and non-optimistic mutation updaters, and needed to be reverted to their previous state.
This was caused by a merge conflict between `optimistic` mutation markers and the changes in #3317 and the prior lines that retrieved the original operation had gotten lost in testing.
A new unit test was added to prevent further regressions.
- Add unit tests for extra variables to prevent regressions
- Update code for `optimistic` flagging
- Add removed lines to retrieve original operation in mutation result updates
=> fix(graphcache): Fix extra variables regression

.changeset/wicked-seahorses-smash.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/store/data.test.ts, packages/core/src/client.test.ts, packages/core/src/client.ts
Resolves #3254
Previously, when Graphcache issued an optimistic mutation that led to a cache miss, the cache-missed query operation would stall since it wasn't allowed to be issued again.
This patch prevents such “stalls” by forcing operations to be dispatched when `client.reexecuteOperation` is called. This allows Graphcache and related exchanges to force re-execution of operations, regardless of the deduplication behaviour.
- Add forced dispatching to `client.reexecuteOperation`
=> fix(core): Force client.reexecuteOperation to dispatch

docs/advanced/server-side-rendering.md
The non-rsc example is missing the `suspense: true` argument, so the query never runs on the server like the copy suggests.
Just enabling suspense in the docs, like it's done in the Next non-rsc example in https://github.com/urql-graphql/urql/blob/main/examples/with-next/app/non-rsc/layout.tsx
=> docs(next): Enable suspense in non-rsc example

docs/advanced/server-side-rendering.md, examples/with-next/app/non-rsc/layout.tsx
Resolves #3367 
When we are streaming the results to the client and the server instance gets re-used we risk leaking results from the `ssrExchange` across streamed renders.
=> docs(next): move ssr and client creation to function body

docs/advanced/server-side-rendering.md
In the documentation, useRouter is imported from next/router, but if you are using App Router, you need to import from next/navigation.
https://nextjs.org/docs/app/api-reference/functions/use-router#migrating-from-nextrouter
The refresh method is not exported from next/router.
=> docs(next): fix import source of useRouter

.changeset/real-ducks-speak.md, exchanges/graphcache/src/operations/query.test.ts, exchanges/graphcache/src/operations/query.ts
Resolves #3370
This fixes a typo in an inverted condition for an owned data check in `resolveResolverResult`. The equivalent check in `resolveLink` is `isOwnedData && prevData === null`, i.e. when a prior result was `null` it keeps the field set to `null`.
Instead, the resolver did the opposite and hence turned a first resolution of a `prevData === null` result into a nulled value, i.e. preventing subsequent results from succeeding.
- Fix inverted `resolveResolverResult` condition for owned `null` values
=> fix(graphcache): Fix typo in owned data null resolution for resolvers

examples/with-react-native/README.md
Broken link, `App.js` is in root not src. 
- This fixes link and updates text
=> examples: Fixing link in with-react-native README.md

docs/architecture.md
https://github.com/urql-graphql/urql/blob/656495100ea3861075b70b48516b10914efbcfd6/exchanges/persisted/CHANGELOG.md?plain=1#L42
Rename persisted-fetch-exchange to persisted-exchange in `architecture.md` as the usage was confusing. 
Updated the doc file.
=> docs: Rename persisted-fetch-exchange to persisted-exchange in architecture.md

.changeset/old-swans-relate.md, packages/core/src/exchanges/ssr.ts
Resolves #3384
This adds a missing exception for forwarding `teardown` operations.
Without this exception, `teardown` operations would be swallowed for operations recorded by the `ssrExchange` which would then trigger unnecessarily in some cases and could be turned into results.
- Add missing `operation.kind` check to `ssrExchange`
=> fix(core): Add missing teardown handling to ssrExchange

.changeset/fast-jeans-pay.md, packages/core/src/internal/fetchSource.ts, packages/core/src/types.ts, packages/core/src/utils/result.test.ts, packages/core/src/utils/result.ts
In the [new June 2023 spec](https://github.com/graphql/defer-stream-wg/discussions/69) we get the introduction of `pending` on both incremental and execution results, pending contains an array of id and path.
The id will be used in incremental payloads, we can then do a lookup in `pending` and find a path, the path indicates where the fragment got spread starting at the root.
Another addition here is the `subPath` which can be present on an incremental payload and builds on the path we can retrieve through `id`, when deferred selection-sets are mixed with the non-deferred one this subPath will point at where we have to start merging.
=> feat(core): Update defer/stream protocol as per spec

.changeset/hungry-rings-switch.md, packages/next-urql/src/DataHydrationContext.ts, packages/next-urql/src/Provider.ts, packages/next-urql/src/useUrqlValue.ts
Resolves #3400 
When leveraging the compatibility settings for React and using the default import we get a very weird statement that isn't supported by all CJS using bundlers.
=> fix(next): invalid CJS React import

.changeset/kind-trains-wink.md, packages/next-urql/src/DataHydrationContext.ts, packages/next-urql/src/Provider.ts
Next.js 13.5 has put in some work into achieving a strict CSP through [documentation](https://nextjs.org/docs/pages/building-your-application/configuring/content-security-policy), [example](https://github.com/vercel/next.js/tree/canary/examples/with-strict-csp), and [code](https://github.com/vercel/next.js/discussions/54907).
When trying it out, I discovered the next urql provider doesn't pass through a nonce. This PR adds a optional nonce parameter to the provider:
```
<UrqlProvider client={client} ssr={ssr} nonce={nonce} >
{children}
</UrqlProvider>
``` 
When passed, the script will render with it:
```
<script nonce="NjJiMGYxNDUtZTRjMS00ODYwLWI3ZTUtYmZmMDVkMzY1YTUw">(window[Symbol.for("urql_transport")] ??= []).push({"rehydrate":{"-8349710366": ... />
```
* added nonce parameter to …
=> feat(next): nonce support

docs/showcase.md
I've created a new package `urql-rest-exchange`. This is a custom exchange for URQL that facilitates GraphQL queries and mutations through REST endpoints. The addition aims to provide users with more tools to integrate REST endpoints with their URQL client seamlessly.
=> docs: Add urql-rest-exchange to the showcase section

.changeset/real-geese-grow.md, packages/preact-urql/src/hooks/useQuery.ts, packages/react-urql/src/hooks/useQuery.ts
Resolves #3426 
When `context.suspense` is defined we should respect that value and only fallback to `client.suspense` when it's undefined
=> fix(react): prioritise context.suspense

.changeset/silver-planets-sniff.md, packages/core/src/internal/fetchSource.ts
As seen in https://github.com/urql-graphql/urql/discussions/3429, some servers send back the response as `text/plain` which can still be valid JSON.
=> chore(core): try to parse a text/plain content-type response as json

.changeset/late-plants-poke.md, exchanges/persisted/src/persistedExchange.test.ts, exchanges/persisted/src/persistedExchange.ts
Closes #3441
When a `persistedExchange()` sees a persisted-miss error, it will retry the operation while disabling persisted serialization using the `miss: true` flag. However, we had no guard to check whether `miss: true` was already set.
This meant that if an API/exchange erroneously keeps replying with persisted-miss errors then `persistedExchange()` wouldn't stop retrying the operation.
When an `ssrExchange()` on the server-side caches this error, this is made worse, since `ssrExchange`'s results are synchronous and this hence causes an infinite loop.
A development-time warning has been added that explicitly tells people that this is what's going on and how to resolve it.
- Add failing test for repeated persisted-miss errors
- Handle & Ignore repeated persisted-miss errors and log …
=> fix(persisted): Add dev warning for persisted-miss results for an already persisted-miss errored operation (repeated retries)

.changeset/stale-eagles-hide.md, docs/api/graphcache.md, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/default-storage/index.ts, exchanges/graphcache/src/types.ts
Resolves https://github.com/urql-graphql/urql/issues/3422
We used to buffer operations while the cache hydrates from storage, this got disabled in our latest release however we can enable folks to still have this. We now support the `cacheExchange` calling `storage.onCacheHydrated` this way folks can load their shell but leave the content in a loading state while the storage hydrates the data.
=> feat(graphcache): add onCacheHydrated event

.changeset/tender-files-tie.md, docs/api/graphcache.md, exchanges/graphcache/src/ast/schemaPredicates.test.ts, exchanges/graphcache/src/ast/schemaPredicates.ts, exchanges/graphcache/src/helpers/help.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/shared.ts, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/types.ts
Resolves #3404
This adds an option to the `graphCache` constructor named `Logger` we will use the logger to convey information that is encountered during development. In doing so a user can choose to remove the warnings by stubbing the logger with `() => {}` or adding other custom logic to filter things out.
- add `Logger` interface for graph-cache
=> feat(graphcache): add logger interface

docs/api/graphcache.md
Noticed we had a new setting that wasn't documented
=> docs(graphcache): add missing globalids setting

.changeset/small-rings-drop.md, packages/next-urql/src/Provider.ts
Related to #3448 and #3408
We have seen a few issues where folks forget their Suspense boundary which leads to infinite requests. We will shield from infinite requests by providing our own underneath the `urql` provider so the client doesn't get re-created and give the user a warning when we are not in production.
=> chore(next): warn for missing suspense boundary

.changeset/funny-hornets-heal.md, packages/next-urql/src/Provider.ts
In response to a comment on https://github.com/urql-graphql/urql/pull/3449#discussion_r1418516774 this opts you into streaming automatically 😅 which is probably not what we want by default. This moves the defaulting to only in the browser
CC @SoraKumo001
=> fix(next): only inject `<Suspense` and warning during client-side rendering

.changeset/fifty-tables-happen.md, packages/core/src/utils/variables.test.ts, packages/core/src/utils/variables.ts
In EdgeRuntime in Next.js, the constructor of an object does not match Object.
Therefore, it is necessary to determine if it inherits from Object.
The following changes are made to the determination of the part that creates the keys of variables.
`x.constructor !== Object`
　　　↓
`!(x.constructor instanceof Object)`
=> fix(core): Fix JSON stringification in Vercel Edge runtime

.changeset/funny-hornets-heal.md, .changeset/small-rings-drop.md, packages/next-urql/src/Provider.ts
This introduces a new functional component which means that we can interfere with `useId`
=> fix(next): remove next warning, could interfere with useId

docs/basics/typescript-integration.md
Resolves #3110
There is currently no in-svelte way of getting typed-document-nodes within GraphQL Code Generator
=> fix(docs): remove svelte section from ts integrations

.changeset/silly-pigs-return.md, packages/core/src/exchanges/cache.ts
Resolves #3462 
In the document cache we put the `cache-outcome` behind a dev-flag, which is inconsistent as we rely on it in other exchanges and it's not behind a flag in our normalized and ssr cache.
=> fix(core): add back cacheOutcome

.changeset/witty-peas-love.md, exchanges/retry/src/retryExchange.test.ts, exchanges/retry/src/retryExchange.ts
Retry delays are not actually working as specified in the docs. Currently, retry delays are not persisted between retries, resulting in exponential backoff not actually increasing the delay amount as time goes on. The linear backoff also does not currently work.
I've added a unit test for this, as well as the change for the behavior to comply with what's actually stated in the docs.
- Made retry delays persist in the context, allowing backoffs to work
- Added unit test for retry delay
- Modified an existing unit test that was failing (I believe it might have been incorrect, but I'm not entirely sure, please verify! It seems like the retry value is meant to reset after a retry that was successful [so, a successful operation], but the unit test was checking the `retry` values after a …
=> fix: retry delay not persisting between calls

.changeset/tiny-candles-dress.md, packages/introspection/src/minifyIntrospectionQuery.ts
Previously, boolean condition typos prevented the `Any` type from not being included when it wasn't needed.
- Fix `_hasAnyType` tracking
=> fix(introspetion): Fix Any type being included when it isn’t needed

.changeset/strange-drinks-sip.md, packages/storage-rn/package.json, pnpm-lock.yaml
Update outdated React Native peer reqs
Currently @urql/storage-rn is breaking the update process to Expo version 50 due to the set peer dependencies in this package. In Expo 50 they bumped RN Netinfo to v11.
- Updated React Native NetInfo package to version 11 and upped the peer reqs in package.json
- Updated React Native Async Storage to 1.21 and upped the peer reqs in package.json
=> chore(rn-storage): Update outdated React Native dependencies

.changeset/serious-tables-ring.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/operations/shared.ts
Related to #3167
This fixes the `@defer` states becoming “sticky” and carrying over to subsequent
operations sometimes, causing incomplete results to be generated under certain conditions.
- Forcefully reset `deferRef` when a new operation is started
=> fix(graphcache): Fix `@defer` state carrying over to next operation

.changeset/giant-beans-act.md, exchanges/graphcache/e2e-tests/query.spec.tsx, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/store/data.ts
> **Note:** I wasn't reasonably able to write tests for the looping protection yet that hit this particular case. Manual testing is needed!
For partial cache results, `stale: false` was being set when the looping protection kicks in. In simple words, if an operation is triggered twice, once as part of an unrelated query updating, causing a partial result, then again, the second trigger will create a cache result with `stale: false`, even if the operation would be in flight.
This PR restores `stale: true` being set, if we reasonably believe the operation is still in flight.
- Add separate `stale: true` override if operation is in flight
=> fix(graphcache): Restore `stale` being set to `true` on blocked (but in-flight) operations

.changeset/seven-toys-applaud.md, docs/basics/svelte.md, examples/with-svelte/package.json, examples/with-svelte/src/PokemonList.svelte, packages/svelte-urql/src/queryStore.ts
Resolves #3221
This adds back a way to reexecute queries arbitrarily in svelte's query-store. It has been a while since I touched `wonka` and it was a learning experience all over again 😅 love the types though, they really go so far in helping out in figuring all of this out
=> feat(svelte): add first class reexecute to svelte

docs/graphcache/cache-updates.md
This is a fix to the Cache Updates doc, which improves clarity of the section on Optimistic Updates.
=> clarity fix in optimistic updates section of cache-updates.md

.changeset/small-cheetahs-jam.md, packages/core/src/types.ts, packages/core/src/utils/result.test.ts, packages/core/src/utils/result.ts
A missing feature for `multipart/mixed` was pointed out where we were missing support for the apollo subscriptions spec which adds a `payload` property
=> feat(core): Support Apollo Federation subscriptions multipart payloads

.changeset/two-bananas-grow.md, packages/core/src/internal/fetchOptions.test.ts, packages/core/src/internal/fetchOptions.ts, packages/core/src/types.ts
This PR adds support for persisted documents, as long as:
- An input GraphQL AST contains a `documentId` property
- A GraphQL API accepts the `documentId` parameter as a replacement for the `query` parameter
When we detect the `documentId` property on a document which has no definitions (either an empty array or not defined), we send a `documentId` instead of a `query`.
This is similar to Automatic Persisted Queries (APQs), but those require the `@urql/exchange-persisted` exchange, to facilitate generating persisted queries on the fly (as per the spec) and retrying them.
This is to comply with: https://github.com/graphql/graphql-over-http/pull/264
- Add `documentId` property to detected GraphQL document types
- Send `documentId` on `FetchBody` when a persisted document is passed
=> feat: Add support for persisted documents via the `documentId` property

docs/graphcache/cache-updates.md, examples/with-graphcache-updates/src/client.js
It's confusing that we use mutative operations in our updaters when that can alter the base-layer when we i.e. are working with optimistic layers.
=> docs(graphcache): remove mutative operations

.changeset/wicked-kids-joke.md, exchanges/graphcache/src/store/store.ts
See related PR: https://github.com/urql-graphql/urql/pull/3503
When `cache.resolve` returns a list of entity links, i.e. an array link, a user may be tempted to mutate this list before writing it back to the store.
This can have unforeseen consequences if:
- `cache.link` then doesn't write to the same layer
- `cache.link` isn't called at all
- the array is completely changed and then read back in an unrelated operation
This is because, unlike `cache.link`, `cache.resolve` doesn't make a copy of links before returning them. This means that mutating a link array leads to direct modifications to the internal caching layer.
- Call `ensureLink` before returning the links via `cache.resolve` to copy them
=> fix(graphcache): Mutable links on InMemoryData store

.changeset/tall-buttons-fetch.md, docs/graphcache/cache-updates.md, exchanges/graphcache/src/operations/invalidate.ts, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/store/data.test.ts, exchanges/graphcache/src/store/data.ts, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/store/store.ts
Related to #3470
This starts tracking a mapping of `__typename` to a list of `entityKey`, this enables us to perform operations like `invalidate('Todo')` which would invalidate every `entityKey` of the `Todo` type.
We add non-root typenames when going through the `write` operation and we clean up entities in the list when we are going through `gc` runs.
In the future this can instruct us for operations where we can't derive an entity i.e. a create-mutation will invalidate all entities of its own type to ensure we don't run into stale values which leaves us with the scalar return case which won't automatically be handled.
The PR explicitly does not add the `updater` logic yet so we can see that the explicit API surface does not grow, we support more cases instead.
- Add Map of `__typename` …
=> feat(graphcache): track types in the data-structure

.changeset/fluffy-poets-protect.md, packages/core/src/internal/fetchOptions.test.ts, packages/core/src/internal/fetchOptions.ts
Resolves #3504 
This aims to solve the problem of supporting `Headers` I opted not to do do a `instanceof` check for this to support node versions that don't have this by default. The downside of doing the `forEach` check is that we also get the `[[string, string]]` `HeadersInit` in there which is a tad harder to support
=> fix(core): support Headers being passed in fetchOptions

.changeset/sixty-needles-exercise.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/shared.ts, exchanges/graphcache/src/operations/write.ts
This fixes `@_optional` to work when the selection contains a sub-selection fragment spread. Previously, other fragment spreads inside an `@_optional` spread would become non-optional/non-required again, since the value of `deferRef` would be reset with another `isOptional()` check.
This also applies the same principle to `@defer`. Previously, `@defer` would cascade to all child selection fields. This meant that any field nested inside a `@defer`-ed fragment would be able to be deferred and be completely optional, even if it's direct parent wasn't a deferred fragment spread.
- Remove `deferRef` reset from `makeContext`
- Reset `deferRef` with every new child field and only cascade it across fragment spreads
- Cascade `optionalRef` across fragment spreads (but also not new child fields)
- …
=> fix(graphcache): Cascade `@defer`, `@_optional`, and `@_required` state only per nested fragment spread

.changeset/curvy-sheep-drive.md, packages/core/src/internal/fetchOptions.test.ts, packages/core/src/internal/fetchOptions.ts
Changes query parameter handling to allow path-only URLs (i.e. `/api/graphql`) passed to `fetch` to be used with GET requests. This was previously broken as [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL) would throw a `TypeError: Invalid URL` as it only works with fully formed URLs.
Extracting the unparsed query parameters is now done manually, so as to not depend on `URL`. Important to note is that the current method will not handle URLs with fragments (i.e. `/api/graphql#fragment`) in them, but it is easy to add if desired.
=> fix(core): Allow path-only URLs to be used with GET requests

docs/api/urql.md
Updates the [docs](https://commerce.nearform.com/open-source/urql/docs/api/urql/#usesubscription) so these match:
=> Update urql.md with small typo fix

.changeset/plenty-elephants-lay.md, exchanges/request-policy/src/requestPolicyExchange.ts
Resolves #3508
This PR removes the logic of asserting the cacheState of a given operation and moves us to asserting whether the operation was resolved synchronously. When we are dealing with a synchronously resolved operation we can see this as a cache-hit, when it's higher than the last dispatched we can see this as a cache miss.
```
cache-first --> request-policy (time 1) --> cache-miss --> fetch --> request-policy (time x > 1)
cache-and-network--> request-policy (time 1) --> cache-hit --> request-policy (time = 1) --> fetch --> request-policy (time x > 1)
```
=> fix(request-policy): avoid relying on cache internals to assert misses

.changeset/honest-queens-approve.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/store/data.ts
Resolves #3470
This adds a default updater when the response contains an entity that has no links to yet, this implies the creation of a new entity. When this creation has no associated updater we'll invalidate the `type`, this ensures that lists are invalidated. This gets us to an easier adoption path and allows for optimising where the user wants to.
The remaining issue here would be cases where the user returns a scalar or when an updater shifts the ordering of a list.
This brings the default graphcache a bit closer to document caching in terms of mutation reactions.
=> feat(graphcache): default updater when none found

docs/advanced/server-side-rendering.md
I was following through [this guide](https://commerce.nearform.com/open-source/urql/docs/advanced/server-side-rendering/#nextjs) and found some minor typos and unused imports.
- Added missing letter on the word "pass"
```diff
- we pas both
+ we pass both
```
- Removed unused import `next/head` (since it's also deprecated in the app router)
```diff
// app/page.tsx
import React from 'react';
- import Head from 'next/head';
import { cacheExchange, createClient, fetchExchange, gql } from '@urql/core';
import { registerUrql } from '@urql/next/rsc';
```
```diff
// pages/index.js
import React from 'react';
- import Head from 'next/head';
import { useQuery } from 'urql';
import { withUrqlClient } from 'next-urql';
```
=> docs: fix typo and remove unused imports

.changeset/eight-garlics-move.md, exchanges/persisted/src/persistedExchange.ts
This PR adds a new option to the `persistedExchange` where we allow passing in `enableForSubscriptions` which enables persisted operations for subscriptions.
=> feat(persisted-exchange): add support for persisted subscriptions

.changeset/silly-vans-do.md, README.md, exchanges/graphcache/package.json, exchanges/graphcache/src/operations/shared.test.ts, package.json, packages/core/package.json, packages/core/src/exchanges/__snapshots__/fetch.test.ts.snap, packages/core/src/exchanges/__snapshots__/subscription.test.ts.snap, packages/core/src/internal/__snapshots__/fetchSource.test.ts.snap, packages/core/src/utils/formatDocument.test.ts, pnpm-lock.yaml
This won't need to be backported, but brings `main` to a new minimum requirement for the next major.
- Upgrade `@0no-co/graphql.web` to 1.0.5
- Update tests
=> chore: Upgrade `@0no-co/graphql.web` to 1.0.5

.changeset/rich-suns-sit.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/operations/invalidate.ts, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/store/store.ts
After a conversation in Discord we discovered that an old "bug" is biting us with the new default functionality. The old bug goes as follows: when we invalidate in a mutation-updater and the invalidated entity belongs to the mutation response we effectively make the mutation response go to null due to us re-querying the data after our write, the re-querying happens so we respect `resolvers` for our mutation data.
This is an ad-hoc fix to reduce the impact of this change, we effectively exclude the entities we find in the mutation response so we can return a good response. In the future we might be able to establish a similar principle for custom invalidations/updates as well.
=> fix(graphcache): ignore current entity during invalidateType

.changeset/lucky-timers-hear.md, scripts/rollup/cleanup-plugin.mjs
See: https://github.com/0no-co/graphql.web/pull/27
=> fix(core): Fix `@ts-ignore` directive on TS import in type declaration output

.changeset/nine-walls-behave.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts, exchanges/graphcache/src/operations/write.ts, exchanges/graphcache/src/store/data.test.ts, exchanges/graphcache/src/store/data.ts
This is kind of an optimisation, say we have three operations that are all watching different fields of `Todo`, only one of these operations watches `Todo.completed`. When a mutation changes `Todo.completed` we should only invoke that one operation, this is slightly more performant. Not sure if worth it but it could also enable us to create a granular re-rendering mechanism with a first-class `fragment` citizen.
=> feat(graphcache): only add dependency if we are changing the value

.changeset/tiny-pots-allow.md, packages/core/src/client.test.ts, packages/core/src/client.ts
Resolves #3565
In the initial issue we were faced with the following issue, imagine a query that returns a list with values `[Todo:1, Todo:2]` we use this list to return components that in turn has its own query to fetch the details of this `Todo`. Both this list and the details have a shared parent field let's name it `Query.author`, this is important for graph-cache to re-dispatch operations.
This diagram of this looks like the following
```
Operation List
Completed Operation List
Operation Todo:1
Operation Todo:2
Completed Operation Todo:1
Operation Todo:2
Completed Operation Todo:2
Completed Operation Todo:2
```
Notice that we re-dispatch `Todo:2` even though it is already in-flight, this is problematic as in the cache it has not resolved to a response yet and hence we send off …
=> fix(client): eager unblocking of in-flight operations

.changeset/forty-walls-hug.md, packages/core/src/utils/request.test.ts, packages/core/src/utils/request.ts
When persisted documents have hidden definitions (i.e. `definitions: []`), but have a `documentId`, we'd generate identical keys for all of these documents.
Instead, we should always use `documentId` to create a request key when it's available.
- Use `documentId` in `hashDocument`
=> fix(core): Use documentId for operation hash if it's available

.changeset/two-hounds-yell.md, exchanges/auth/package.json, exchanges/context/package.json, exchanges/execute/package.json, exchanges/graphcache/package.json, exchanges/persisted/package.json, exchanges/populate/package.json, exchanges/refocus/package.json, exchanges/request-policy/package.json, exchanges/retry/package.json, packages/introspection/package.json, packages/preact-urql/package.json, packages/react-urql/package.json, packages/svelte-urql/package.json, packages/vue-urql/package.json, pnpm-lock.yaml, scripts/prepare/index.js
Originally (I reckon during the introduction of `@urql/core`), we decided to only include `@urql/core` as a dependency, since it never is a direct dependency. This allowed it to install automatically and deduplicate as long as all ranges match.
This wasn't ever a problem assuming deduplication was working (which it sometimes isn't in Yarn Legacy). However, `@urql/core` is only actively instantiated once in any given app. This means that for all exchanges it's only used to share types.
Problems with this is though, `@urql/core`'s types contain instances that TypeScript will always consider as incompatible if they're duplicated. This means that this approach stopped working for TypeScript.
While we could provide shared global namespace types in `@urql/core`, which is my alternative proposal …
=> patch: Mark `@urql/core` as a peer as well as a regular dependency

.changeset/famous-deers-marry.md, packages/preact-urql/src/hooks/useSubscription.ts, packages/react-urql/src/hooks/useSubscription.ts, packages/svelte-urql/src/subscriptionStore.ts, packages/vue-urql/src/useSubscription.ts
> [!NOTE]
> Reported on Discord
The subscription handlers infer their new value argument type as `T` of `OperationResult<T>`. This means that `data: null` cases are uncovered and the handler may accidentally receive `null` values when the types specify that this isn't possible.
This may happen when a trailing value of a subscription contains a fatal error rather than a result value.
In this case it should be safe to ignore the value, since the subscription will either be restarted by the subscription client (or a `retryExchange`), or will terminate.
- Handle `null` values before passing `result.data` to subscription handlers
=> fix(bindings): Fix handlers for subscriptions receiving null

.changeset/itchy-cups-remember.md, packages/vue-urql/src/useMutation.ts, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts, packages/vue-urql/src/utils.ts
Resolves #3556
Supports getter functions on `MaybeRef`-typed inputs.
- Add `(() => T)` to `MaybeRef` and handle in `unref`
=> fix(vue): Support getter-functions on `MaybeRef`-typed inputs

exchanges/execute/src/execute.test.ts, exchanges/graphcache/src/offlineExchange.test.ts, packages/core/src/exchanges/debug.test.ts, packages/core/src/exchanges/fetch.test.ts, packages/core/src/internal/fetchSource.test.ts, packages/core/src/utils/variables.test.ts, packages/preact-urql/src/components/Mutation.test.tsx, packages/preact-urql/src/components/Query.test.tsx, packages/preact-urql/src/components/Subscription.test.tsx, packages/preact-urql/src/hooks/useMutation.test.tsx, packages/preact-urql/src/hooks/useQuery.test.tsx, packages/preact-urql/src/hooks/useSubscription.test.tsx, packages/react-urql/src/components/Mutation.test.tsx, packages/react-urql/src/components/Query.test.tsx, packages/react-urql/src/hooks/useMutation.test.tsx, packages/react-urql/src/hooks/useQuery.spec.ts, packages/react-urql/src/hooks/useQuery.test.tsx, scripts/vitest/setup.js
This is more of a maintenance change. The Node docs officially recommend to switch to `globalThis` instead of `global`, see https://nodejs.org/api/globals.html#global . `globalThis` is available in all other runtimes as well which makes the test suite easier to run outside of node. I'm working on getting vitest to run in Deno and I'm using urql's test suite for that.
Replaces usages of `global` in the test suite to `globalThis`.
=> chore: change `global` -> `globalThis` in tests

.changeset/eight-mirrors-sing.md, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts
Solves https://github.com/urql-graphql/urql/issues/3594#issue-2316403034
This is just a quick fix for getting isPaused reactive, but there might be some issues with the reactivity of other parameters.
=> fix(vue): Fix regression causing `pause` argument to not be reactive

.github/workflows/ci.yml, .github/workflows/release.yml, exchanges/auth/jsr.json, exchanges/context/jsr.json, exchanges/execute/jsr.json, exchanges/graphcache/jsr.json, exchanges/persisted/jsr.json, exchanges/populate/jsr.json, exchanges/refocus/jsr.json, exchanges/request-policy/jsr.json, exchanges/retry/jsr.json, package.json, packages/core/jsr.json, packages/core/package.json, packages/core/src/utils/error.ts, packages/core/src/utils/formatDocument.ts, packages/core/src/utils/request.ts, packages/core/src/utils/result.ts, packages/core/src/utils/variables.ts, packages/introspection/jsr.json, packages/next-urql/jsr.json, packages/preact-urql/jsr.json, packages/react-urql/jsr.json, packages/storage-rn/jsr.json, packages/svelte-urql/jsr.json, packages/vue-urql/jsr.json, pnpm-lock.yaml, scripts/changesets/jsr.mjs, scripts/changesets/version.mjs
This adds a publishing pipeline to [jsr](https://jsr.io/), for now it will only publish `@urql/core` because we have a lot of "slow types" where it doesn't infer from the generic or is implicit. I'd solve these one by one rather than creating one big PR. The PR already adds the infrastructure in each workspace to publish to JSR by means of the `jsr.json` file. This also adds a new script during versioning where it will bump all the `jsr` packages.
A point for improvement that I'm considering in scope of this PR is a transformation script for our TS codebase where we transform all the `process.env.NODE_ENV` to `import.meta.env.NODE_ENV` or we strip it out. Not doing so will cut out deno support for a while, supporting both Deno as well as Node in JSR would require …
=> chore(workspace): automatically publish urql-core to JSR

.changeset/shaggy-wasps-bow.md, exchanges/graphcache/src/cacheExchange.ts, packages/core/src/utils/variables.ts
Fixes https://github.com/urql-graphql/urql/issues/3541
Change how we calculate the `OperationKey` to take files into account, before we
would encode them to `null` resulting in every mutation with the same variables
(excluding the files) to have the same key. This resulted in mutations that upload
different files at the same time to share a result in GraphCache.
=> fix(core): ensure operationKey is different when dealing with files

packages/core/src/utils/request.ts
=> fix(core): correctly add argument to invocation

packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts, packages/vue-urql/src/utils.ts
Restore reactivity typings for `variables` input.
This regression caused a [number](https://stackoverflow.com/questions/76163956/how-to-allow-urql-typescript-to-accept-vue-reactive-variables-for-queries-crea) of [issues](https://github.com/dotansimha/graphql-code-generator-community/issues/194) using `graphql-code-generator`
Reuse `MaybeRef` type for variables typing.
=> fix(vue): Fix regression causing variables to not be reactive

.changeset/friendly-timers-taste.md, packages/vue-urql/src/useMutation.ts, packages/vue-urql/src/useQuery.test.ts, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts
This PR fixes a bug noted by @negezor: the `pause` property was not working with a getter, see https://github.com/urql-graphql/urql/pull/3595#issuecomment-2142285519.
1) Minor fixes in `useQuery.ts` and `useSubscription.ts` to manage the case where pause is a getter.
2) Corrected some typos in the docs of `useQuery.ts` and `useSubscription.ts`.
3) Modified a test in `useQuery.test.ts` to use a reactive `pause` property with a getter.
=> fix(vue): pause not working with getters

.changeset/old-onions-travel.md, packages/vue-urql/src/useClient.ts, packages/vue-urql/src/useMutation.ts, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts
Instead of using `ref` for deep objects, it is much more efficient from a performance point of view to look at reactivity only at the moment of setting the value, rather than changing its internal properties.
- Replaces `ref` with `shallowRef` for the client in `useClient.ts`
- Replaces `ref` with `shallowRef` for `error`, `operation` and `extensions` in `useMutation.ts`, `useQuery.ts` and `useSubscription.ts`
I don't consider this a breaking change since these properties should always be considered read-only. Since properties are always overwritten completely, and nested reactivity is not needed in them. Because changing them will not lead to the desired result in most cases.
=> Use shallowRef instead of ref for deep objects

.changeset/quick-pens-battle.md, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts
This eliminates the memory leak since reactive always assigned new `watchEffects` to the static request object.
Resolves: https://github.com/urql-graphql/urql/issues/3507#issuecomment-2174017806
Memory leak appeared in this PR https://github.com/urql-graphql/urql/pull/1151
- Removes wrapping `args` in `reactive` in `useQuery.ts` and `useSubscription.ts`
This change is not breaking, since we still do `unref` as before #1151 PR.
=> Remove wrapping request args in reactive to fix memory leak

.changeset/curvy-pets-yawn.md, packages/vue-urql/src/useQuery.test.ts, packages/vue-urql/src/useQuery.ts
Reverts #3612 and adds a test asserting this behavior for the future
Re-opens #3507
We need to identify what specifically causes #3507 to keep allocating new helpers, this might as well be a bug in Vue as multiple libraries seem to leverage this pattern of calling `reactive` on a top-level argument.
=> fix(vue): variables lose reactivity

.changeset/lazy-kangaroos-think.md, exchanges/graphcache/src/operations/shared.ts
=> fix(graphcache): Disregard write-only operation during schema awareness

docs/architecture.md
At least I think this is where it was meant to go. The current one 404s.
=> fix(docs): fix typo'd URL

.changeset/mighty-parents-fetch.md, packages/svelte-urql/package.json
add support for Svelte 5, currently svelte 5 is not supported
svelte-urql package is changed, but shouldn't affect anything
=> add support for Svelte 5

.changeset/chatty-mice-join.md, packages/vue-urql/src/useClientHandle.ts, packages/vue-urql/src/useMutation.test.ts, packages/vue-urql/src/useMutation.ts, packages/vue-urql/src/useQuery.test.ts, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.test.ts, packages/vue-urql/src/useSubscription.ts, packages/vue-urql/src/utils.ts
Resolves https://github.com/urql-graphql/urql/issues/3507
Resolves https://github.com/urql-graphql/urql/issues/3633
This includes https://github.com/urql-graphql/urql/pull/3612, but fixed reactivity loosing here.
In addition, a little refactoring for `use*` composable functions for reducing code duplication and adding more test cases.
* Remove wrapping args in reactive in useQuery.ts and useSubscription.ts
* Add `createRequestWithArgs()`, `useClientState()` and `useRequestState()` utils to avoid code duplication.
* Refactor `useQuery()`, `useSubscription()` and `useMutation()` to use shared  utils mentioned above.
* Add `isReadonly()` check before changing `isPaused` variable, as it could be readonly.
* ~~Remove `onBeforeUnmount` and unwatch handlers, as [watcher automatically stopped …
=> feat(vue): refactor composable functions

.changeset/sweet-goats-judge.md, packages/core/src/exchanges/ssr.ts
Removes the unnecessary `JSON.stringify` when serializing, since it will be called below anyway
Removing the `data` pre-property in exchange/ssr during serialization
=> perf(core): remove duplicate `JSON.stringify` call on `data` in `ssrExchange`

.changeset/old-humans-knock.md, packages/vue-urql/src/useMutation.ts, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts
As graphql response usually contains a quite huge nested objects structure, wrapping it with `ref()` is not memory efficient.
Instead of doing this, it's more efficient to use `shallowRef()` for `data` reactive variable, where the payload is stored.
However, in https://github.com/urql-graphql/urql/pull/3611 while optimizing other variables, @negezor missed the `data` variable. I can assume there was a reason for that, so I consider this PR as a suggestion/discussion. Personally, I don't see any negative side effects from using `shallowRef()`, but maybe you guys have some thought on it.
I see only one possible scenario in which this would be a "breaking change": updating some nested `data` parts manually outside of this plugin, but I'd say - this is a quite specific pattern.
- Replaces …
=> perf(vue): use shallowRef for data

.changeset/good-walls-obey.md, packages/core/src/utils/error.test.ts, packages/core/src/utils/error.ts
Fixes #3649 
Allow for empty error messages when rehydrating
=> fix(core): Allow for empty error messages when rehydrating

.changeset/tidy-spies-turn.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/cacheExchange.ts
The PR #2761 moved `reexecutingOperations = dependentOperations` assignment into `if (operation.kind === 'query')` guard. Thus after a completion of mutation, `dependentOperations = _reexecutingOperations` make reexecuting and dependent operations the same set object.
I noticed this issue after debugging the bug reported in discord https://discord.com/channels/1082378892523864074/1082386845553406002/1281542643670712334
=> fix(graphcache): mutation would cause dependent operations and reexecuting operations become the same set

.changeset/hungry-pandas-accept.md, packages/next-urql/src/index.ts
Export `SSRContext` from @urql/next so the provider can be used in tests.
Exports `SSRContext` from `@urql/next`
=> chore: @urql/next expose SSRContext

.changeset/chilly-cows-brake.md, package.json, packages/solid-urql/src/index.ts
Adds the missing export for context provider component in `@urql/solid`
- Adds the export
=> fix(solid): Export Provider from the entry

.changeset/perfect-worms-deliver.md, packages/solid-urql/src/createMutation.ts, packages/solid-urql/src/createQuery.ts, packages/solid-urql/src/createSubscription.ts
Reconcile data updates, which lets Solid only notify listeners who are subscribing for the exact changed values.
Apply [`reconcile`](https://docs.solidjs.com/reference/store-utilities/reconcile) to data fetching primitives available
=> feat(solid): reconcile data updates

.changeset/healthy-years-ring.md, packages/solid-urql/src/createQuery.ts
This PR fixes a bug in `@urql/solid` that the change tracking for `query.data` is not working when the client has `suspense: true`.
Read data from the store instead of the resource, so further changes on store can be tracked and reflected to the returned value
=> fix(solid): Correctly track query data reads with suspense

packages/site/src/html.js
On any page of the docs site (i.e. https://commerce.nearform.com/open-source/urql/docs/basics/vue/), the _favicon_ is missing, due to a `404` error trying to fetch it.
The path to the _favicon_ is relatively defined in [html.js](https://github.com/urql-graphql/urql/blob/main/packages/site/src/html.js#L28), changing it to absolute path.
=> docs(site): Fix no favicon on site (except on home page)

.changeset/shiny-eagles-join.md, packages/react-urql/src/hooks/useQuery.ts
Fixes an issue where suspending a query with `hasNext: true` - primarily from use of the defer directive - would cause an early teardown and trigger an AbortError
At first glance, not sure how to test this, as I couldn't find an appropriate starting point.
=> Allow @defer to work in queries with suspense enabled

.changeset/tender-moons-watch.md, exchanges/graphcache/src/operations/query.ts, exchanges/graphcache/src/operations/shared.test.ts, exchanges/graphcache/src/operations/shared.ts, exchanges/graphcache/src/operations/write.ts
Related to https://github.com/urql-graphql/urql/pull/3690
Related to https://github.com/0no-co/graphql.web/pull/33
Attempt to get JSC memory usage under control by dropping the nested anonymous-function based iterator implementation with one with a manual stack. This has also been updated to use a `class` in the hopes of getting JSC to drop memory used by the iterator faster and reduce overall usage.
In testing, JSC seems to hang on to a large amount of scope memory due to the prior implementation.
> [!NOTE]
> Synthetic benchmarks are currently not present anymore (TBD). Browser benchmarks don't run anymore. Tests are currently broken for individual packages. In theory, however, we should be able to use Tachometer + Webdriver Safari to run the browser benchmarks on JSC to get comparative …
=> fix(graphcache): Replace selection iterator implementation for JSC memory reduction

.changeset/chatty-toes-melt.md, packages/preact-urql/src/hooks/constants.ts, packages/preact-urql/src/hooks/useMutation.ts, packages/preact-urql/src/hooks/useQuery.ts, packages/preact-urql/src/hooks/useSubscription.test.tsx, packages/react-urql/src/hooks/__snapshots__/useMutation.test.tsx.snap, packages/react-urql/src/hooks/__snapshots__/useQuery.test.tsx.snap, packages/react-urql/src/hooks/__snapshots__/useSubscription.test.tsx.snap, packages/react-urql/src/hooks/state.ts, packages/react-urql/src/hooks/useMutation.ts, packages/react-urql/src/hooks/useQuery.spec.ts, packages/react-urql/src/hooks/useQuery.ts, packages/solid-urql/src/createMutation.ts, packages/solid-urql/src/createQuery.ts, packages/svelte-urql/src/mutationStore.ts, packages/svelte-urql/src/queryStore.ts, packages/vue-urql/src/useMutation.ts, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/utils.ts
Resolves #3702 
Add `hasNext` to query-state, still have to perform this for other bindings.
=> Add `hasNext` to query-state

.changeset/tiny-tigers-lick.md, packages/next-urql/src/useQuery.ts
In PR #3703, `hasNext` was added. However, after upgrading urql to version 4.2.1, the @urql/next `UseQueryState` did not have type information for `hasNext`, resulting in an error.
hasNext has been added to UseQueryState in @urql/next.
=> Add hasNext to urql-next query-state

.changeset/fluffy-starfishes-unite.md, scripts/babel/transform-debug-target.mjs
Fixes https://github.com/urql-graphql/urql/issues/3715
This change addresses a bug where the `addMetadata` function was being stripped or modified in production builds, resulting in the meta field being unavailable. The absence of meta caused inconsistent behaviour between development and production environments, particularly for TTL-based re-requests and cache outcomes. 
Previously, [there was an attempt to add back the meta to production bundles](https://github.com/urql-graphql/urql/pull/3464), but perhaps the babel file was missed. 
Updated the Babel transformer to preserve `addMetadata` calls in production, ensuring metadata (e.g., `cacheOutcome`) is always available.
@urql/core: The core package was updated to fix the issue.
=> fix(core): make `metadata` available in production

docs/advanced/authentication.md
This updates an example code snippet to prevent reading `status` from `undefined`.
According to the type definitions, `response` may be undefined. I can confirm because this [happened in production](https://github.com/chromaui/addon-visual-tests/pull/349).
- Updated `docs/advanced/authentication.md` to add an optional chaining operator to handle undefined response.
=> docs: Fix sample code to avoid reading from `undefined` in `didAuthError`

README.md
I came to the URQL looking for a Solid adapter and went elsewhere because the README didn't list it. A colleague however pointed out that the adapter does exist in the package. Making a PR so other Solid users aren't confused by the README.
=> Adding Solid to README for visibility

.changeset/lucky-bears-promise.md, exchanges/throw-on-error/README.md, exchanges/throw-on-error/package.json, pnpm-lock.yaml
Hi, I'm the maintainer of `graphql-toe` and we just put out a new release, v1.0.0-rc.0, which fixes an issue where errored arrays would be replaced with a null prototype object with array indicies but not an instance of array. We've also overhauled the README with greater detail.
This PR:
- upgrades to this new release of `graphql-toe`
- ~~moves `wonka` from `dependencies` to `devDependencies`~~
- adds extra detail to the README
Please check the instructions I placed in the README, I'm not familiar with the exchanges system (I don't really do frontend work these days, mostly just backend stuff!) so am not certain I put the exchange in the correct position in the array. The tests didn't help clue me in since they don't seem to follow this pattern.
cc @JoviDeCroock who I have been DM-ing …
=> chore(toe): update graphql-toe and add instructions to README

.changeset/nervous-flies-confess.md, packages/core/src/internal/fetchSource.ts
Huge thanks for open-sourcing such a great library. In my private frontend project where I'm using urql, I happened to find an issue where multibyte strings fetched via urql occasionally become garbled. After inspecting the network and logic, I found that the root cause was decoding strings without considering UTF-8 character boundaries.
Fortunately, in frontend development, the TextDecoder API provides a useful `stream` option, and I confirmed that simply enabling this resolves the issue. As for the Node.js or other backend dev environment, I believe the problem could be addressed by using StringDecoder or something, but I haven't explored that part yet.
I would like to request this change be merged in order to simplify my vendoring. I created this PR primarily to share the issue for …
=> fix(core): Fix multibyte character decoding by using `stream` option

.changeset/old-ears-hunt.md, exchanges/graphcache/package.json, exchanges/graphcache/src/ast/graphql.ts, exchanges/graphcache/src/operations/shared.ts, package.json, packages/core/package.json, packages/core/src/utils/graphql.ts, pnpm-lock.yaml
Resolves #3724
1. TypeScript changed the behaviour of "unresolved" any from 5.5 so doing `type Doc = OrNever<UnresolvedType> | LocalType` will always be any.
2. Without `graphql` as optional peer dependency in `@urql/core`, `graphql.web` will be unable to resolve it when using a strict package manager like Yarn Berry.
Both problems are covered by #3724 
1. Changed OrNever to 
```typescript
type OrNever<T> = void extends T ? never : T;
```
Which is compatible with both newer and older TypeScript versions.
2. Added `graphql` as optional peer dependency for packages that are using `graphql.web`
As a sidenote, there is a `graphql` import without fallback in `urql/packages/preact-urql/src/hooks/useRequest.ts` that will also break inference, but I am not sure how would you like to handle that.
=> fix(core,graphcache): Update optional graphql types with TS 5.5 compatible switch

.changeset/heavy-hairs-bow.md, packages/core/src/exchanges/cache.ts
When printing debug message, the following message is printed when an item is returned from the cache:
> The result was successfully retried from the cache
Based on the source code, this has nothing to do with retrying at all, it's just a typo and should be:
> The result was successfully retrieved from the cache
=> fix(core): typo in cacheHit debug message

.changeset/slow-hotels-yawn.md, exchanges/retry/src/retryExchange.ts
Since all options are optional, as they already have default values (as stated in https://nearform.com/open-source/urql/docs/advanced/retry-operations/ ), let's make the `options` argument optional.
So that one can call `retryExchange()` instead of `retryExchange({})`
=> patch(retry): Make options argument optional

.changeset/giant-pets-buy.md, exchanges/persisted/src/persistedExchange.ts, packages/core/src/client.test.ts, packages/core/src/client.ts
I've been thinking about this for quite a while but it's time that this default is switched up, most GraphQL clients force you in this paradigm of always leveraging POST which misses out on a lot of benefits. The settings to actually do it the "right way" HTTP semantically is hidden behind an option.
The downside is that some servers _might_ not support GET, however they are still free to turn this off. I prefer the explicit having to turn it off from having a degraded default experience.
The default should still be persisted operations but at least we take a step forward HTTP semantically wise.
=> major(core|persisted): use GET for queries by default

.changeset/unlucky-apes-change.md, exchanges/graphcache/src/operations/shared.ts, exchanges/graphcache/src/store/store.ts, exchanges/graphcache/src/types.ts
We want to deterministically match fragments, but don't want the downside of schema-aware: security risk, bundle size, partial result on nullable field.
=> feat(graphcache): add possibleTypes config for deterministic fragment matching

.changeset/twenty-cows-roll.md, exchanges/persisted/src/persistedExchange.test.ts, exchanges/persisted/src/persistedExchange.ts, packages/core/src/client.ts
Resolves https://github.com/urql-graphql/urql/issues/3811
Use nullish coalescing instead of `||` for `preferGetMethod` and `preferGetForPersistedQueries` so that `false` is kept if set.
=> fix: use nullish coalescing for get method preference

.changeset/rich-melons-play.md, packages/react-urql/src/hooks/state.ts, packages/react-urql/src/hooks/useQuery.ts
Resolves #3764
Same as before: the warning is irrelevant, and we're looking to mute it. We can make the deferred dispatching permanent, since we don't want to rely on internals
As before, just because the warning is issued that doesn't mean anything is wrong. We're only doing this to mute this warning.
- Update how `ReactCurrentOwner` is accessed using new internals
- Always defer `setState` dispatch unless there's no synchronous/concurrent update in parallel
=> fix(react-urql): Upgrade muted warning code for React 19 internals
