example/src/server/index.js, example/src/server/schema.js
This PR just runs your prettier config over the example code. No changes apart from formatting.
=> Run prettier over the example code

README.md
I just wanted my name in this repo
=> link apollo and team in readme.md

package.json, tsconfig.json, yarn.lock
Doesn't look like you're using pipeline; feel free to turn this down, but I'd rather not accidentally break your build from deleting a branch. ;)
=> Remove dependency on experimental TypeScript build.

package.json, yarn.lock
Upgrade `graphql` dependency from `0.13` release candidate to the latest stable version.
`0.13.0-rc.1` -> `^0.13.1`
=> Upgrade graphql dep to latest stable

README.md
add some instructions to README to use urql without components
=> use urql without using components

package.json, src/components/connect-hoc.tsx, src/tests/components/__snapshots__/connect-hoc.test.tsx.snap, src/tests/components/connect-hoc.test.tsx, yarn.lock
Static hoisting FTW.
This uses https://github.com/mridgway/hoist-non-react-statics, which does a great job!
=> Added static hoisting for ConnectHOC

src/exchanges/cache.ts, src/lib/__snapshots__/client.test.ts.snap, src/lib/client.test.ts, src/lib/typenames.test.ts, src/lib/typenames.ts, tsconfig.json
=> add more tests for typenames and clean up implementation

MIGRATION.md
=> add migration guide

docs/README.md, docs/about/exchanges.md, docs/components/connect-hoc.md, docs/components/connect.md, docs/components/provider.md, docs/utils/createMutation.md, docs/utils/createQuery.md
=> add wiki to docs

README.md
Nit pick, but in line with the Code of Conduct this proposes to change 'Sane' to 'Logical' as it is more inclusive language.
=> Update Readme.md for more inclusive language!

src/exchanges/cache.ts, src/utils/index.ts, src/utils/typenames.test.ts, src/utils/typenames.ts
=> fix typename recursion and add test

docs/getting-started.md
I thought I could get the embed working but it turns out github flavored mardown doesnt support video embed.
=> Link to egghead screencast

src/components/Query.tsx, src/global.d.ts
=> Fix incorrect use of Exclude and added key prop

docs/getting-started.md
Just a quick fix on `npm install` :)
=> Fix typo on getting-started

src/hooks/useMutation.ts, src/hooks/useQuery.ts, src/hooks/useSubscription.ts
=> Export hook response types

package.json
Fixes: https://github.com/FormidableLabs/urql/issues/266
=> (chore) - pkg.json metadata fields

src/hooks/useQuery.test.tsx
Pretty much what it says 😅! Was reviewing @kitten's PRs retrospectively and noticed this one slip thru 🤗!
=> Remove it.only from useQuery.test.tsx.

examples/3-ssr-with-nextjs/components/Submit.js
=> Fix Submit function in examples/3-ssr-with-nextjs

package.json, src/components/Mutation.test.tsx, src/components/Query.test.tsx, src/components/Subscription.test.tsx, src/exchanges/cache.test.ts, src/exchanges/debug.test.ts, src/exchanges/fetch.test.ts, src/hooks/useSubscription.test.tsx, src/test-utils/samples.ts, yarn.lock
Decided to push my changes on a new branch after a mistake....
=> (tests) - coverage

src/hooks/useImmediateState.ts
Fixes: https://github.com/FormidableLabs/urql/issues/287
Reproduced at: https://codesandbox.io/s/nostalgic-sound-psbzf?fontsize=14
I think this is the most consistent fix for this problem.
=> (fix) - fast render should update state

examples/1-getting-started/README.md, examples/1-getting-started/src/app/Home.tsx, examples/1-getting-started/src/app/components/Todo.tsx, examples/1-getting-started/src/app/index.css, examples/1-getting-started/src/app/index.tsx, examples/1-getting-started/yarn.lock
Fix #302
This PR comes in response #295. @akwmak makes a good point that the install instructions are not totally clear here, so I tried to make them a bit more instructive 🤗. While I was here I also wanted to address some small stylistic changes in the example, mostly around types. Happy to address any feedback but likely to be offline for a few days!
=> Add clearer install instructions for Getting Started example. Clean up Getting Started example.

src/components/index.ts
=> Export all types from src/components

examples/3-ssr-with-nextjs/src/init-urql-client.js, examples/3-ssr-with-nextjs/src/with-urql-client.js
Here is the Pull-Request https://github.com/zeit/next.js/pull/7651 to Canary release.
=> adjust next.js example to be more aligned  with apollo example from the Readme

docs/README.md, docs/exchanges.md
This is a proposition as to how we could acknowledge exchanges made by others.
This is meant for people who want to add their own package, we could expand this with a guide on how to write your own exchanges etc, I think people who write exchanges that help others should be able to advertise it somehow on the main repository. Correct me if my thought process is wrong somewhere.
=> (docs) - propose way for third-party exchanges

docs/getting-started.md
Fixes: https://github.com/FormidableLabs/urql/issues/334
=> (docs) - correct invalid syntax in getting started

src/exchanges/__snapshots__/fetch.test.ts.snap, src/exchanges/fetch.test.ts, src/exchanges/fetch.ts
=> Fix bounds checking of HTTP status codes in fetchExchange

src/client.ts
Just a quick patch for https://github.com/FormidableLabs/urql/pull/357 :)
=> (fix) Make fetch option available to fetch exchange

README.md
We should boost the visibility of these packages and link to the full list in the README, so that it becomes more obvious that more features can be enabled/added with extra packages :100:
=> Add section to README for supporting packages

.github/ISSUE_TEMPLATE/bug_report.md
Server repro template: https://codesandbox.io/s/urql-issue-template-server-0ufyz
Client repro template: https://codesandbox.io/s/urql-issue-template-client-iui0o
=> (chore) - create bug report template

examples/1-getting-started/README.md, examples/1-getting-started/package.json, examples/1-getting-started/src/app/index.tsx, examples/1-getting-started/yarn.lock
This expands our getting-started example with using the devtoolsExchange, this way consumers of the urql-package can see it working.
=> (chore) - @urql/devtools

docs/api.md, docs/architecture.md, docs/basics.md, docs/exchanges.md, docs/extending-and-experimenting.md, docs/getting-started.md, docs/guides.md, docs/urql-outside-react.md
These docs are backported from our real docs website, there were some slight alterations, for our own ease I've left the links intact to point to the real docs website.
=> (chore) - backport docs

src/exchanges/__snapshots__/fetch.test.ts.snap, src/exchanges/fetch.test.ts, src/exchanges/fetch.ts, src/types.ts
Related: https://github.com/FormidableLabs/urql-devtools-exchange/pull/2
=> (chore) - remove latency handling from fetchExchange

src/exchanges/__snapshots__/fetch.test.ts.snap, src/exchanges/fetch.test.ts, src/exchanges/fetch.ts
=> Add operationName field to fetch request

examples/1-getting-started/src/app/Home.tsx, examples/1-getting-started/src/app/components/NewTodo.tsx, examples/1-getting-started/src/app/components/Todo.tsx, examples/1-getting-started/src/app/components/index.ts, examples/1-getting-started/src/app/index.css, examples/1-getting-started/src/server/index.js, examples/1-getting-started/src/server/schema.js
This PR adds the feature to delete and add new todos to the example, it helps to better understand how urql caching works when changing adding/removing things
=> add delete and add todo to example 1

src/client.ts
=> Fix context.suspense override being ineffective

src/client.ts, src/components/Mutation.ts, src/exchanges/compose.ts, src/hooks/constants.ts, src/hooks/useMutation.ts, src/hooks/useQuery.ts, src/hooks/useSubscription.ts
- Removes destructuring when the variable is used once
- Moves all initialStates to a centric place (since they're all the same)
=> Golf some bytes

docs/guides.md
Not sure if the other guides need to be updated as well, but this is the change I needed to make in my project for the file exchange.
=> Update file exchange example to work with wonka v4

package.json, src/client.test.ts, src/client.ts, yarn.lock
This either synchronously returns [an `OperationResult`](https://github.com/FormidableLabs/urql/blob/b88b4e78bba942b4443985c909aa508aea0b9ef2/src/types.ts#L62-L73) if an exchange (typically a cache) returns a value immediately, or otherwise returns `null` while cancelling all side-effects.
=> Add client.readQuery

src/hooks/useSource.ts
=> Avoid effects in useBehaviourSubject in suspense-mode

exchanges/graphcache/README.md
Updates the README of graphcache package to use the new documentation urls.
=> Update Graphcache documentation links

.changeset/dry-planets-report.md, .changeset/fresh-owls-hide.md, .changeset/gentle-cows-kiss.md, .changeset/green-files-prove.md, .changeset/large-baboons-train.md, .changeset/sour-actors-sniff.md, .changeset/tame-pumas-peel.md, .changeset/thin-lies-brush.md, .changeset/weak-beds-heal.md, .changeset/wicked-badgers-fetch.md, packages/preact-urql/CHANGELOG.md, scripts/changesets/changelog.js
=> Add changesets for pre-monorepo changes

packages/react-urql/examples/1-getting-started/sandbox.config.json
[This tweet](https://twitter.com/compuives/status/1237701098430963712?s=21)
[Sandbox](https://codesandbox.io/s/github/FormidableLabs/urql/tree/codesandbox-for-examples-part-2/packages/react-urql/examples/1-getting-started)
=> Add template for sandbox config

.changeset/spicy-flies-push.md, packages/site/src/components/sidebar.js
- Add fixed height to fix Logo bug on safari
=> Set logo fixed height for safari bug

packages/core/src/utils/typenames.ts
This removes some redundant code from `core/utils/typenames.ts`
=> (core) - Golf some bytes in typenames

packages/site/src/components/mdx.js, packages/site/src/components/sidebar.js
- Remove trailing slash logic to fix relative links
- Update regex used to trim pathname when determining if a route `isActive`
=> Docs: fix relative links and isActive highlighting

scripts/babel/transform-debug-target.js
https://astexplorer.net/#/gist/7098a93b18f9000dafa4a38ec985ee96/96b512473db6f9c4cebcf8a544b44cd98436efcc
=> update babel plugin

docs/graphcache/normalized-caching.md
Fixes a small typo in `normalized-caching.md`
Only affects `normalized-caching.md`
=> Fix typo in normalized-caching.md

docs/graphcache/normalized-caching.md
Noticed this typo while reading your documentation.
N/A
=> Fix typo in normalized example

docs/advanced/testing.md
Resolves #691 
Update the testing page of the documentation :
- Add more details about the utilities you can use from `wonka`, to create the mock client.
- Add a subscription section
- Update the Simulating Changes code section. 
I am new with this library so I am not sure about the best strategy to test subscription. I was able to test the code from the doc.
=> Enhance testing page

docs/advanced/server-side-rendering.md
=> fix docs advanced-server-side-rendering

docs/advanced/retry-operations.md
Fix a docs misprint (exchanges order) in RetryExchange page
Change exchanges order: "retry" before "fetch"
=> Change exchanges order: "retry" before "fetch"

.changeset/stale-onions-check.md, packages/core/src/utils/stringifyVariables.test.ts, packages/core/src/utils/stringifyVariables.ts
=> Fix stringifyVariables not stringifying toJSON values for scalars

.changeset/wicked-tools-wave.md, packages/preact-urql/package.json, packages/react-urql/package.json, packages/svelte-urql/package.json
Fixes: https://github.com/FormidableLabs/urql/issues/723
=> Bump @urql/core minor for the integrations

.changeset/nine-grapes-lay.md, exchanges/graphcache/src/store/__snapshots__/store.test.ts.snap, exchanges/graphcache/src/store/keys.ts, exchanges/graphcache/src/store/store.test.ts
=> (fix) - Fix data persistence for embedded fields

.changeset/spicy-beds-allow.md, packages/core/package.json
Fixes https://github.com/FormidableLabs/urql/issues/730
=> include /internal for core

docs/README.md, docs/advanced/README.md, docs/basics/README.md, docs/concepts/README.md, docs/graphcache/README.md, docs/overview.md, docs/showcase.md
This touches on the:
- installation (npm/yarn)
- adding the client
- adding a basic query
This is really the bare minimum to get started, we might want to move this to the homepage only though. This gives a url, ... That will just work (all though it could have a cold-start)
Relates to https://github.com/FormidableLabs/urql/issues/663
=> (docs) - quick-start

docs/api/README.md, docs/common-questions.md, docs/showcase.md
This is a start for the common questions, we can start gathering them here.
Relates to https://github.com/FormidableLabs/urql/issues/663
=> (docs) - common questions

exchanges/graphcache/package.json, exchanges/multipart-fetch/package.json, exchanges/persisted-fetch/package.json, exchanges/populate/package.json, exchanges/retry/package.json, exchanges/suspense/package.json, packages/core/package.json, packages/next-urql/package.json, packages/preact-urql/package.json, packages/react-urql/package.json, packages/svelte-urql/package.json, scripts/prepare/index.js
Fix https://github.com/FormidableLabs/urql/issues/744.
=> make prepare script work on windows

docs/concepts/exchanges.md
=> Misprint, I think.

docs/advanced/retry-operations.md, docs/advanced/server-side-rendering.md, docs/advanced/testing.md, docs/api/core.md, docs/api/graphcache.md, docs/basics/errors.md, docs/concepts/core-package.md, docs/concepts/exchanges.md, docs/concepts/philosophy.md, exchanges/graphcache/help.md, packages/core/src/client.test.ts, packages/site/src/screens/home/_content.js
- Fix various spelling mistakes
- Make Wonka capitalisation consistent
=> (docs) - Language/spelling cleanup

docs/basics/mutations.md, docs/basics/queries.md, packages/site/src/components/scroll-to-top.js
Fix broken anchor heading links when navigating from other pages.
- Change the match index used in parsePathname
- Update outdated links
=> (docs) - Fix heading anchor links

README.md
- Replace offensive spectrum badge 😅 
- Use [badgen](https://badgen.net/) for all badges (consistent colors, better perf than shields.io)
- Flaunt that MIT
- Show total downloads
- Add link to docs
[Readme preview](https://github.com/FormidableLabs/urql/blob/less-offensive-badges/README.md)
=> (docs) - Badge tweaks

packages/react-urql/examples/1-getting-started/package.json
This save some time on the devtools examples we're working on (https://github.com/FormidableLabs/urql-devtools-exchange/pull/38)
=> Add build command to example

docs/graphcache/gotchas.md, docs/graphcache/under-the-hood.md
This documents the measures for:
- commutativity
- deferring refetches
Any other ones popping up for any of you?
=> (docs) - graphcache gotcha's

exchanges/multipart-fetch/src/multipartFetchExchange.ts, exchanges/persisted-fetch/src/persistedFetchExchange.ts, packages/core/src/exchanges/fetch.ts, packages/core/src/internal/fetchSource.test.ts, packages/core/src/internal/fetchSource.ts, packages/core/src/types.ts, packages/preact-urql/src/components/Mutation.test.tsx
Fix #777
Provide "raw" json to fetch debugging events
=> (debug) - Dispatch network debug events consistently

packages/next-urql/README.md
Fixed example link to the related path
- packages/next-urql/README.md
=> (docs) - Fix next-urql example link

docs/basics/document-caching.md
Closes https://github.com/FormidableLabs/urql/issues/822
Forgot about the variables as first argument when writing this
=> fix syntax issue in document-caching.md

packages/next-urql/CHANGELOG.md
=> fix(docs): typo on changelog

docs/advanced/auto-populate-mutations.md, exchanges/populate/README.md
Updates the documentation for the populateExchange
Resolves https://github.com/FormidableLabs/urql/issues/867
=> (populate) - update docs

docs/advanced/subscriptions.md
Addresses a spelling issue and a couple minor grammar mistakes.
=> Spelling and grammar fixes

.changeset/six-pumas-taste.md, packages/core/src/exchanges/ssr.test.ts, packages/core/src/exchanges/ssr.ts, packages/react-urql/src/test-utils/ssr.test.tsx
=> (fix) - Delay invalidation in ssrExchange by a tick

packages/next-urql/README.md
Resolves https://github.com/FormidableLabs/urql/issues/888
=> (next-urql) - remove mergeExchanges notion

docs/graphcache/custom-updates.md
=> (docs) - add graphcache docs for inspectFields

docs/graphcache/custom-updates.md
Adds documentation for invalidating lists
=> add example of using inspectFields to invalidate a list

.changeset/hungry-cycles-kiss.md, exchanges/graphcache/src/cacheExchange.test.ts, exchanges/graphcache/src/types.ts
Fixes: https://github.com/FormidableLabs/urql/issues/926
- adds an object return possibility
=> (graphcahce) - fix resolver types

docs/showcase.md
Add the urql-custom-scalars-exchange to the list of community packages
=> Add urql-custom-scalars-exchange to showcase

docs/README.md
=> docs: remove extra 'to'

packages/preact-urql/README.md
There were two badges remaining from the transfer from my user to this repo.
=> (preact) - remove residual badges from repo-transfer

docs/basics/queries.md
Fixes svelte queries examples
None
=> Fix few typos in svelte queries documentation examples

.changeset/ten-guests-study.md, packages/svelte-urql/src/operations.ts
Adds stale property to map
- Adds stale property to map
=> (svelte) - fix stale issue with cache-and-network

docs/graphcache/README.md
Switched `less` with the more grammatically correct `fewer`.
* Updated graphcache docs
=> (docs) - fix grammatical issue in graphcache docs

.changeset/fresh-brooms-fix.md, exchanges/auth/src/authExchange.test.ts, exchanges/execute/src/execute.test.ts, exchanges/graphcache/src/helpers/operation.ts, packages/core/src/utils/deprecation.test.ts, scripts/jest/setup.js
=> (graphcache) - Fix stray operationName warning in addCacheOutcome

.changeset/rotten-buckets-smell.md, packages/storybook-addon/package.json, packages/storybook-addon/src/decorator/preact.ts, packages/storybook-addon/src/decorator/react.ts, yarn.lock
This for the issue #1092 .
It adds the `devToolsExchange` to the exchanges if it can be found.
=> (storybook) - Add devtools exchange

docs/api/graphcache.md
Adds an example of passing variables in `cache.readFragment`. This was previously undocumented.
=> (docs) - Add note about third argument in readFragment

packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts
The current implementation of `useQuery` and `useSubscription` uses refs heavily and also uses `unref` in a lot of places, which adds noise to the code. This PR aims to simplify the implementation and to have more readable code.
1. We can simplify the implementation substantially by using `reactive` on the args object, which will unwrap all nested refs automatically.
2. The conditional ref wrapping for `isPaused` and `scanHandler` can be simplified with `computed` in the former (for casting to a boolean) and a simple `ref()` for the latter (calling `ref()` on a `Ref` simply returns the ref as is).
This is purely an internal refactoring and doesn't have any influence on the API. therefore, I didn't include a changeset. Please let me know if one is required nonetheless and I'll add it.
=> (vue-urql) - Refactor usage of ref/unref

docs/advanced/server-side-rendering.md, docs/advanced/subscriptions.md, docs/api/vue.md, docs/basics/getting-started.md, docs/basics/mutations.md, docs/basics/queries.md, docs/comparison.md, packages/site/src/screens/docs/article.js
**This is still a work-in-progress until all pages are completed**
**Preview Link:** https://formidable-com-urql-staging-1165.surge.sh/docs/
=> (docs) - Add documentation for @urql/vue

.changeset/selfish-humans-destroy.md, package.json, yarn.lock
Fixes: https://github.com/FormidableLabs/urql/issues/1203
Our babel-plugin would postfix the `graphql` dependency with `.mjs` for the `executeSync` import.
- bump dep to fix the build
=> (introspection) - fix the build

docs/graphcache/schema-awareness.md
=> (docs) - Correct a typo in schema-awareness

docs/advanced/server-side-rendering.md
ref: https://codesandbox.io/s/condescending-kapitsa-9p8y7?file=/pages/index.js:548-702
The docs referring to usage in getStaticProps was incorrect.
Resolves: #1279
Fixed example of getStaticProps usage.
=> (docs) - correct next-urql getStaticProps example

docs/advanced/testing.md
Resolve #1325
We may not hoist `mockedClient` if any extensions extend `expect` or reset mocked functions by other means. Generally it's safer to avoid hoisting the implementation unless we can move it to `beforeEach` (or something similar like `beforeAll`) or keep it in local test runs.
=> (docs) - Remove hoisting of mocked client in Jest tests

packages/site/static.config.js
This is an attempt at redirects for the pages we've moved around in our docs-split up
=> (docs) - Redirects

docs/graphcache/normalized-caching.md
Fix wronk link in docs
```diff
- http://localhost:3000/docs/api/graphcache/#cache
+ ../api/graphcache/#cache
```
=> Fix wrong link with localhost:3000

packages/site/static.config.js
Hopefully fixes #1380
Fixed path concatenation in documentation site.
=> (docs) - Fix path rewrites for non client routed links

README.md
fixes https://github.com/FormidableLabs/urql/issues/1433
=> (docs) - update exchanges link

.changeset/late-days-serve.md, packages/storybook-addon/package.json
Hey FormidableLabs! We've created a catalog of Storybook addons and yours is included: https://storybook.js.org/addons/@urql/storybook-addon
To make your addon more discoverable in the catalog, we've curated some of its metadata, and I've included those edits in this PR.
To learn more about the catalog metadata, check out our documentation: https://storybook.js.org/docs/react/addons/addon-catalog
=> Update Storybook addon metadata

docs/advanced/retry-operations.md
=> (docs) - Update retry-operations.md

docs/graphcache/cache-updates.md
Minor doc change, fixing a spurious extra bullet point in a list.
=> (docs) - Fix incorrect bullet list

docs/api/urql.md
Use the same URL as in #1439.  The current one 404s.
=> Fix useQuery `pause` link

examples/with-apq/README.md, examples/with-apq/package.json, examples/with-apq/src/App.js, examples/with-apq/src/index.css, examples/with-apq/src/index.js, examples/with-apq/src/pages/LocationsList.js, examples/with-retry/README.md
Add with-apq example describing the way of using the persistedFetchExchange for Automatic Persisted Queries
=> (examples) Usage of persistedFetchExchange

examples/with-multipart/README.md, examples/with-multipart/package.json, examples/with-multipart/src/App.js, examples/with-multipart/src/index.css, examples/with-multipart/src/index.js, examples/with-multipart/src/pages/FileUpload.js
Add an example to show how to use the multipartFetchExchange exchange to handle file uploads
=> (examples) Add with-multipart example

examples/with-next/pages/index.js, examples/with-next/pages/server.js
=> fix imports on next examples

examples/with-graphcache-pagination/README.md, examples/with-graphcache-pagination/package.json, examples/with-graphcache-pagination/src/App.js, examples/with-graphcache-pagination/src/index.css, examples/with-graphcache-pagination/src/index.js, examples/with-graphcache-pagination/src/pages/PaginatedNpmSearch.js, examples/with-pagination/README.md
Add an example for infinite scrolling pagination using the Graphcache Resolvers
=> (examples) Add with-graphcache-pagination

.gitignore, examples/with-react-native/App.js, examples/with-react-native/README.md, examples/with-react-native/app.json, examples/with-react-native/index.js, examples/with-react-native/package.json, examples/with-react-native/src/screens/PokemonList.js, examples/with-react/src/pages/PokemonList.js
=> Add with-react-native example

examples/with-refresh-auth/src/client/index.js, examples/with-refresh-auth/src/pages/Home.js, examples/with-refresh-auth/src/pages/Profile.js
Add willAuthError to with-refresh-token example
=> (examples) - Add willAuthError to with-refresh-token example

docs/graphcache/cache-updates.md
Remove extra } in the code example
=> (docs) Review cacheExchange code example

examples/with-cache-updates/README.md, examples/with-cache-updates/package.json, examples/with-cache-updates/src/App.js, examples/with-cache-updates/src/client/index.js, examples/with-cache-updates/src/index.css, examples/with-cache-updates/src/index.js, examples/with-cache-updates/src/pages/Home.js, examples/with-cache-updates/src/pages/Links.js, examples/with-cache-updates/src/pages/LoginForm.js
Add with-cache-updates example
=> (examples) Add with-cache-updates example

.changeset/polite-laws-brake.md, exchanges/request-policy/src/requestPolicyExchange.test.ts, exchanges/request-policy/src/requestPolicyExchange.ts
=> (request-policy) - Fix TTL being erased and renewed on cache hits

.changeset/old-colts-breathe.md, exchanges/graphcache/src/types.ts
=> (graphcache) - Loosen ScalarObject type constraint

docs/basics/core.md
Fix typo in docs.
In the "Core usage" docs, change `urql` to `@urql/core` in the import statement.
=> Fix typo in `docs/basics/core.md`.

.changeset/two-beers-exist.md, packages/core/src/utils/request.test.ts, packages/core/src/utils/request.ts
=> (core) - Fix empty and no variables resulting in differing keys

.changeset/popular-sheep-itch.md, packages/svelte-urql/src/operations.test.ts, packages/svelte-urql/src/operations.ts, scripts/jest/setup.js
- use `executeMutation` over `mutation`
=> (svelte) - use executeMutation over mutation

docs/graphcache/local-resolvers.md
Teeny tiny spelling fix 🔬
Change *cecked* to *checked* in the Graphcache docs.
=> Spelling micro-fix in local-resolvers.md

.changeset/tame-pandas-hope.md, exchanges/graphcache/src/extras/relayPagination.ts, exchanges/graphcache/src/extras/simplePagination.ts
=> (graphcache) - Type extras helpers as returning all-matching Resolver

docs/basics/vue.md
Fix typo in docs.
In the "Basic Vue binding" docs change `Svelte` to `Vue` in Reading on section
=> Fix typo in docs  docs/basics/vue.md

.changeset/orange-pets-wave.md, exchanges/auth/src/authExchange.ts
=> (auth) - Fix willAuthError causing duplicate operations

docs/advanced/server-side-rendering.md, docs/api/core.md
Document the feature introduced in #1852
=> (docs) - document ssrExchange/next-urql staleWhileRevalidate option

examples/with-defer-stream-directives/server/index.js
This hack was for Relay, as it wasnt exactly "spec" compliant.
=> (examples) - hacks not needed here

docs/architecture.md
=> (docs) - Fix broken link

docs/basics/README.md, docs/basics/ui-patterns.md
After a conversation on Twitter we realised that we needed a documentation page with a set of common ui patterns as these might not have been sufficiently explained through our basics section. This can also help people "think in urql", If anyone has more suggestions of things that are missing please ping!
Currently the way of thinking is that we document it in React but explain what's happening as these API's are also available in other integrations.
- Add `UI Patterns`
=> (docs) - common ui patterns

scripts/changesets/changelog.js
I’d used this script as inspiration elsewhere and recently [found out](https://twitter.com/donavon/status/1468734889021353991) you could use `Intl.ListFormat` to simplify the code that joins string values, so I thought I’d contribute this change back. This repo uses Node.js 14 which supports this API.
=> Simplify changelog.js by using `Intl.ListFormat`

exchanges/auth/README.md
Fixes a typo where `authState`'s `refreshToken` is accessed with `!.`
instead of `?.`.
- Replace `!.` with `?.` in example code
=> docs: typo on optional chaining

examples/with-svelte/package.json, examples/with-svelte/src/App.svelte, examples/with-svelte/src/PokemonList.svelte
Follow up to #2370 
Updating the example so we leverage the new major version.
=> chore(svelte): update svelte example to @urql/svelte2

docs/advanced/testing.md
Noticed a missing import while reading the testing docs
I fixed the test example by adding the missing import :rocket:
=> chore(docs): improve test examples

.changeset/eighty-snakes-drive.md, packages/svelte-urql/src/mutationStore.ts, packages/svelte-urql/src/queryStore.ts, packages/svelte-urql/src/subscriptionStore.ts
Resolves #2495
Made variables optional in all store operations :)
```
variables: Variables -> variables?: Variables
```
=> (@urql/svelte) - make `variables` optional

packages/next-urql/README.md
=> packages/next-urql/README.md: fix typo

docs/basics/svelte.md
This is a start to the basics documentation for Svelte v2, we have stepped away from the explicit refetching, ... to fully embracing the functional nature of Svelte which has a fun exploration for me personally here to document it 😅
=> docs(svelte): update docs for Svelte v2

docs/advanced/authentication.md
I wanted to fix some typos in the docs
added missing closing curly braces to a few code snippets
=> fix: added missing brackets to examples

docs/advanced/server-side-rendering.md
I noticed docs about SSR with `Next` are a little bit outdated, and missing
some potentially juicy approaches using direct schema execution.
- adjust docs to assume `{ ssr: false}` is the default
- add an explicit section for `{ ssr: true }`
- move note about `_app` static optimisation to section with `{ ssr: true }`
- add section about server-only code and direct schema execution when using `getServerSideProps` and `getStaticProps`
=> docs: clear up section about Next APIs

docs/basics/ui-patterns.md
Hi, the code example was just not okay, some parameters where missing and the component name didn't match.
Fixed parameters and component name
=> docs: fixed code example in ui-patterns

docs/advanced/subscriptions.md
The changes are made specifically for Svelte subscriptions.
=> Updated docs for Svelte Subscriptions

docs/api/request-policy-exchange.md, docs/architecture.md, docs/graphcache/cache-updates.md, docs/graphcache/local-resolvers.md, docs/graphcache/schema-awareness.md
I used the [Grammarly extension for VS Code](https://marketplace.visualstudio.com/items?itemName=znck.grammarly&ssr=false#overview) to find issues.
=> Docs: fix typos

docs/advanced/subscriptions.md
Found a little typo that confused for a second when I copy pasted the code :smile:
None
=> docs: correct typo subscription docs qgl -> gql

.github/workflows/ci.yml, packages/react-urql/cypress/fixtures/example.json, packages/react-urql/cypress/plugins/index.js, packages/react-urql/cypress/support/commands.js, packages/react-urql/cypress/support/index.js, packages/react-urql/e2e-tests/useQuery.spec.tsx
This pull request is aimed at increasing the reliability of our e2e, we were seeming some failures by our API answering too fast.
As a follow-up I would love to start adding graphCache, ... to this and test a real application with graphCache, another follow up would be to update to the new cypress major
- increase speed of CI by only building the core package
- add missing cypress files
- add `delayExchange` to our exchanges in e2e
=> chore(workspace): stabilise reliability of e2e

docs/basics/typescript-integration.md
=> doc(typescript): fix typo in code example

.changeset/curvy-monkeys-collect.md, packages/core/src/client.ts
Adjust types to account for https://github.com/FormidableLabs/urql/pull/2692
=> fix(core): preferGetMethod type

CONTRIBUTING.md
- Update references from `yarn` to `pnpm`
- Update various old references to old tooling
- Update "package update" instructions
=> chore(docs): Update CONTRIBUTING.md for pnpm

docs/advanced/authoring-exchanges.md
docs show example how to create an exchange, but this particular example is not quite correct as it doesn't return the operation which blocks the exchange result
=> Minor docs update authoring-exchanges.md

docs/comparison.md
Add mention of local state management to `docs/comparison.md` and link to relevant discussion in repository issue.
- `docs/comparison.md`
-  Add mention of local state management and remove `also` from the beginning of the following paragraph for better flow.
=> docs/mention local state management in comparison.md

docs/basics/typescript-integration.md
same as the PR title.
This is a docs-only change.
=> docs: fix useQuery usage in doc

docs/showcase.md
=> docs(showcase): add SSE urql exchange package

docs/architecture.md
=> docs: Update architecture.md

docs/graphcache/local-resolvers.md
Without an example it is not obvious that relayPagination can be easily used in the nested fields as well.
Add an example on how to attach relayPagination in nested fields.
=> Clarify the usage of relayPagination

packages/next-urql/README.md
Updated the installation command to include `graphql` as a peerDependency.
=> docs: Update next-urql README.md

docs/advanced/retry-operations.md
Closes #2966
The retry behaviour doesn't match the documentation (see: https://github.com/urql-graphql/urql/pull/2966)
Updated docs to match actual behaviour (2 attempts instead of infinite)
=> docs(retry): Update retry-operations.md

docs/graphcache/normalized-caching.md
=> docs(graphcache): Add docs for flexible key generation

docs/advanced/authentication.md
Fixes typo
Rename 'refershAuth' to 'refreshAuth'
=> fix: change refershAuth to refreshAuth in docs

.github/actions/discord-message/action.js, .github/actions/discord-message/action.yml, .github/workflows/release.yml, package.json, pnpm-lock.yaml
This posts the release to our new Discord so users are notified!
=> feat(workspace): post to discord when we release new packages

docs/graphcache/cache-updates.md
Hello :)
Following comments here https://github.com/urql-graphql/urql/discussions/2279#discussioncomment-5266279 and the fix that will be available soon https://github.com/urql-graphql/urql/pull/3046 <3
I still think it would be nice to have some code example in the documentation.
=> docs(graphcache): Add example to "Variables for Optimistic Updates"

docs/advanced/subscriptions.md
=> docs(core): Update subscription instructions

exchanges/graphcache/src/offlineExchange.test.ts, exchanges/refocus/src/refocusExchange.test.ts, package.json, packages/core/src/internal/fetchOptions.test.ts, packages/core/src/utils/variables.test.ts, packages/preact-urql/src/components/Mutation.test.tsx, packages/preact-urql/src/components/Query.test.tsx, packages/preact-urql/src/components/Subscription.test.tsx, packages/preact-urql/src/hooks/useMutation.test.tsx, packages/preact-urql/src/hooks/useQuery.test.tsx, packages/preact-urql/src/hooks/useSubscription.test.tsx, packages/react-urql/src/components/Mutation.test.tsx, packages/react-urql/src/components/Query.test.tsx, packages/react-urql/src/hooks/useMutation.test.tsx, packages/react-urql/src/hooks/useQuery.test.tsx, packages/vue-urql/src/useClient.test.ts, packages/vue-urql/src/useSubscription.test.ts, pnpm-lock.yaml, vitest.config.ts
- Replace timers with fake timers where applicable
- Avoid instantiating jsdom for every test
- Upgrade vitest
=> test(workspace): Speed up slowest vitest tests

.changeset/gold-pumpkins-type.md, .github/workflows/release.yml, exchanges/auth/package.json, exchanges/context/package.json, exchanges/execute/package.json, exchanges/graphcache/package.json, exchanges/persisted/package.json, exchanges/populate/package.json, exchanges/refocus/package.json, exchanges/request-policy/package.json, exchanges/retry/package.json, package.json, packages/core/package.json, packages/introspection/package.json, packages/next-urql/package.json, packages/preact-urql/package.json, packages/react-urql/package.json, packages/storage-rn/package.json, packages/svelte-urql/package.json, packages/vue-urql/package.json, pnpm-lock.yaml, scripts/prepare/index.js
- Set up npm provenance
- Bump dependencies to provenance versions
- Update lockfiles, workflows, and prepare script
=> chore(workspace): Set up publish with npm provenance

docs/basics/vue.md
=> fix(docs): urql vue plugin exchanges

.changeset/few-snails-burn.md, .changeset/lazy-needles-give.md, examples/with-defer-stream-directives/README.md, examples/with-defer-stream-directives/package.json, examples/with-subscriptions-via-fetch/README.md, examples/with-subscriptions-via-fetch/index.html, examples/with-subscriptions-via-fetch/package.json, examples/with-subscriptions-via-fetch/server/graphql-yoga.js, examples/with-subscriptions-via-fetch/server/schema.js, examples/with-subscriptions-via-fetch/src/App.jsx, examples/with-subscriptions-via-fetch/src/Songs.jsx, examples/with-subscriptions-via-fetch/src/index.jsx, examples/with-subscriptions-via-fetch/vite.config.js, packages/core/src/client.ts, packages/core/src/internal/fetchSource.ts
- Fix `fetchSubscriptions` option on the `Client` not actually being applied to `OperationContext`
- Fix `hasNext: undefined` being treated as end of subscription via fetch request
=> fix(core): Fix subscriptions via fetch

.changeset/yellow-shrimps-admire.md, packages/preact-urql/src/hooks/useSource.ts
=> fix(preact): Check operations for key difference only

.changeset/config.json, .github/workflows/release.yml, exchanges/auth/package.json, exchanges/context/package.json, exchanges/execute/package.json, exchanges/graphcache/package.json, exchanges/persisted/package.json, exchanges/populate/package.json, exchanges/refocus/package.json, exchanges/request-policy/package.json, exchanges/retry/package.json, package.json, packages/core/package.json, packages/introspection/package.json, packages/next-urql/package.json, packages/preact-urql/package.json, packages/react-urql/package.json, packages/storage-rn/package.json, packages/svelte-urql/package.json, packages/vue-urql/package.json, pnpm-lock.yaml, scripts/prepare/index.js
- Update changesets' canary template to use commit hash and calculated version
- Update changesets CLI and Action
- Update prepare script to add `author` field and `exports[].types` check
=> chore(workspace): Update changesets

.changeset/curvy-coins-travel.md, packages/core/src/client.ts
=> fix(core): Apply maskTypename earlier in the chain

docs/graphcache/local-resolvers.md
This adds some initial examples of how to write "advanced" resolvers, since we've got some hidden features that aren't documented yet (apart from TSDocs)
- Add sections on going beyond some limitations of resolvers
=> docs(graphcache): Add advanced resolver tips

CONTRIBUTING.md
Fix small typo in contributing.md
=> chore(docs): Fix typo

docs/architecture.md
Caught this minor issue while reading into exchanges and `graphcache`.
=> docs: fix minor typo

.github/actions/discord-message/action.yml, .github/actions/pnpm-run/action.yml, .github/workflows/ci.yml, .github/workflows/release.yml
Currently this produces warnings in our CI
=> chore: upgrade actions to node 20

docs/advanced/server-side-rendering.md, examples/with-next/app/non-rsc/layout.tsx
=> docs: add correct client detection

.changeset/eight-garlics-move.md, examples/with-apq/package.json, exchanges/persisted/CHANGELOG.md, exchanges/persisted/package.json, exchanges/persisted/src/persistedExchange.ts
=> feat(persisted): add option to enable persisted subscriptions (BACKPORT)

.changeset/ninety-taxis-return.md, exchanges/graphcache/src/store/store.test.ts, exchanges/graphcache/src/store/store.ts
=> fix(graphcache): backport invalidation fix

docs/graphcache/normalized-caching.md
=> docs: Fix broken link

.github/actions/discord-message/action.mjs
This aims to make our automated release posts on Discord a little more compact and automatically remove the embeds that Discord is adding.
- Remove `username` override
- Replace links to remove embeds
- Remove `Submitted by` if it's `undefined` or maintainer username
- Remove `Updated Dependencies` lines
- Remove duplicate newlines
- Remove headings
=> chore: Update Discord hook formatting

docs/basics/ui-patterns.md
Just going through the docs and clicked on a link that led to 404. This PR resolves the link to the correct URL.
```diff
- https://github.com/urql-graphql/urql/tree/main/examples/with-infinite--pagination
+ https://github.com/urql-graphql/urql/tree/main/examples/with-infinite-pagination
```
=> docs: remove extra dash in url

exchanges/auth/jsr.json, exchanges/context/jsr.json, exchanges/execute/jsr.json, exchanges/graphcache/jsr.json, exchanges/persisted/jsr.json, exchanges/populate/jsr.json, exchanges/refocus/jsr.json, exchanges/request-policy/jsr.json, exchanges/retry/jsr.json, packages/core/jsr.json, packages/core/src/utils/variables.ts, packages/introspection/jsr.json, packages/preact-urql/jsr.json, packages/react-urql/jsr.json, packages/svelte-urql/jsr.json, packages/vue-urql/jsr.json
Versions added in our JSR script were a bit outdated, this fixes that. We are only publishing core right now but it skewed how the release PR looked
=> chore(workspace): update versions

.changeset/many-kings-double.md, packages/vue-urql/src/useQuery.ts, packages/vue-urql/src/useSubscription.ts
=> fix(vue): deep options reactivity in subscriptions

docs/showcase.md
I have been using the exchange referred to here https://github.com/urql-graphql/urql/discussions/3440#discussioncomment-8768504 for several months and it's useful, I would like to add it to the documentation.
=> docs: Add `urql-exhaustive-additional-typenames-exchange` to showcase

.github/workflows/ci.yml, .github/workflows/release.yml, package.json, pnpm-lock.yaml
Also adds the `engines` field to package.json
=> chore(workspace): Upgrade pnpm to v9

exchanges/auth/package.json, exchanges/context/package.json, exchanges/execute/package.json, exchanges/graphcache/package.json, exchanges/persisted/package.json, exchanges/populate/package.json, exchanges/refocus/package.json, exchanges/request-policy/package.json, exchanges/retry/package.json, packages/core/package.json, packages/preact-urql/package.json, packages/react-urql/package.json, packages/solid-urql/package.json, packages/storage-rn/package.json, packages/svelte-urql/package.json, packages/vue-urql/package.json, pnpm-lock.yaml
=> chore(workspace): Bump cypress to latest

exchanges/auth/package.json, exchanges/context/package.json, exchanges/execute/package.json, exchanges/graphcache/package.json, exchanges/graphcache/src/store/__snapshots__/store.test.ts.snap, exchanges/graphcache/src/store/data.test.ts, exchanges/persisted/package.json, exchanges/populate/package.json, exchanges/populate/src/populateExchange.test.ts, exchanges/refocus/package.json, exchanges/request-policy/package.json, exchanges/retry/package.json, package.json, packages/core/package.json, packages/core/src/client.test.ts, packages/core/src/exchanges/__snapshots__/fetch.test.ts.snap, packages/core/src/gql.test.ts, packages/core/src/internal/__snapshots__/fetchSource.test.ts.snap, packages/core/src/internal/fetchOptions.test.ts, packages/core/src/utils/request.test.ts, packages/preact-urql/package.json, packages/react-urql/package.json, packages/solid-urql/package.json, packages/storage-rn/package.json, packages/svelte-urql/package.json, packages/vue-urql/package.json, pnpm-lock.yaml
Tried again to get vitest workspaces running but solid seems to refuse to cooperate here 😅
=> chore(workspace): Bump vitest individually and change command

docs/advanced/persistence-and-uploads.md
Resolves https://github.com/urql-graphql/urql/issues/3535
=> Add note about extending File

docs/advanced/server-side-rendering.md
close #3720
Thank you for providing us with this wonderful library called urql.
I found an error in the sample code in the document when I was trying to introduce it to Next.js so I am fixing that.
It does not affect the package because it is only a modification of the document.
=> docs: Syntax errors in Next.js SSR documentation.

.changeset/purple-olives-unite.md, packages/introspection/src/minifyIntrospectionQuery.ts, pnpm-lock.yaml
Supersedes https://github.com/urql-graphql/urql/pull/3727
=> chore(workspace): dedupe lockfile

.github/FUNDING.yml
Removes the link in the top nav
=> Remove funding link

.changeset/beige-penguins-complain.md, packages/next-urql/src/Provider.ts
I've fixed the sample code in the UrqlProvider tsdoc.
I referred to the content of https://github.com/urql-graphql/urql/issues/3367.
=> fix: fix example code in UrqlProvider tsdoc.

docs/basics/errors.md
As per the title, the link has been fixed.
=> docs: fix link for combinederror

.changeset/serious-chefs-march.md, packages/core/src/exchanges/debug.test.ts, packages/core/src/exchanges/debug.ts
=> fix(core): Use `console.debug` verbosity in `debugExchange`

.changeset/wild-flowers-yawn.md, packages/core/src/index.ts
Resolves #3784 
Just exported the getOperationName function
=> chore: export the getOperationName function
